### ISSUE TITLE
Installation sur un serveur de com et un serveur d'administration

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-Server#101]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version :  2.4.1

### Problem's description
si l'on installe OCS  sur 2 serveurs, l'un hébergeant la partie administration, l'autre la partie communication, on a un message d'erreur et l'installation de la partie 'Administration' s'arrête 

+----------------------------------------------------------+
|      Installing files for Administration server...       |
+----------------------------------------------------------+

Creating PHP directory /usr/share/ocsinventory-reports/ocsreports.
Copying PHP files to /usr/share/ocsinventory-reports/ocsreports.
Fixing permissions on directory /usr/share/ocsinventory-reports/ocsreports.
Creating database configuration file /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php.
Creating IPDiscover directory /var/lib/ocsinventory-reports/ipd.
Fixing permissions on directory /var/lib/ocsinventory-reports/ipd.
Creating packages directory /var/lib/ocsinventory-reports/download.
Fixing permissions on directory /var/lib/ocsinventory-reports/download.
Creating snmp mibs directory /var/lib/ocsinventory-reports/snmp.
Fixing permissions on directory /var/lib/ocsinventory-reports/snmp.
Creating Administration server log files directory /var/lib/ocsinventory-reports/logs.
Fixing permissions on directory /var/lib/ocsinventory-reports/logs.
Creating Administration server scripts log files directory /var/lib/ocsinventory-reports/scripts.
Fixing permissions on directory /var/lib/ocsinventory-reports/scripts.
Configuring IPDISCOVER-UTIL Perl script.
Installing IPDISCOVER-UTIL Perl script.
Fixing permissions on IPDISCOVER-UTIL Perl script.
Writing Administration server configuration to file /etc/httpd/conf.d/ocsinventory-reports.conf
chown: impossible d'accéder à « /etc/ocsinventory-server/plugins »: Aucun fichier ou dossier de ce type
chown: impossible d'accéder à « /etc/ocsinventory-server/perl »: Aucun fichier ou dossier de ce type
*** ERROR: Unable to write /etc/httpd/conf.d/ocsinventory-reports.conf, please look at error in /var/tmp/OCSNG_UNIX_SERVER-2.4.1/ocs_server_setup.log and fix !

Installation aborted !

dans ce cas il n'y a pas répertoire /etc/ocsinventory_server sur le serveur d'administration. 
et le message d'erreur n’est pas le bon car  le test  en ligne 1862 correspond à l'opération précédente ( ligne 1855 copie du fichier de conf httpd ) mais on voit bien dans la log que c'est les chown qui lèvent l'erreur.

il faudrait remonter les lignes 1857 à 1861 dans la partie installation du serveur de communication 

1857                 #Fix permissions on server side for plugin engine (perl / plugins) dir usually in etc/ocsinventory-server..
1858                 # Where are located OCS Communication server plugins configuration files
1859                 chown -R $APACHE_USER:$APACHE_GROUPE $OCS_COM_SRV_PLUGINS_CONFIG_DIR
1860                 # Where are located OCS Communication server plugins perl files
1861                 chown -R $APACHE_USER:$APACHE_GROUPE $OCS_COM_SRV_PLUGINS_PERL_DIR
1862                 if [ $? -ne 0 ]
1863                         then
1864                                 echo "*** ERROR: Unable to write $APACHE_CONFIG_DIRECTORY/$ADM_SERVER_APACHE_CONF_FILE, please look at error in $SETUP_LOG and fix !"
1865                                 echo
1866                                 echo "Installation aborted !"
1867                                 exit 1
1868                 fi

**Comment by gillesdubois** [comment]
Bonjour,

Effectivement, le problème est résolu dans la master et avec la sortie de la 2.8 (millieu septembre).

Cordialement,
Gilles.
