### ISSUE TITLE
Unable to Install Plugins: Err_02

### ISSUE THREAD

**Issue by rburkholder2305** [OCSInventory-NG/OCSInventory-Server#102]
### General informations
Operating system : Centos 7

### Server informations
Perl version : v5.16.3
Mysql / Mariadb / Percona version :  5.7.22

### Server installation method ( Only one choice )
- [x] RPM Package
- [ ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
Whenever I attempt to install any plugin from the plugins manager, the installation fails with error "The communication server encountered the following error on install :  Err_02". I confirmed that the plugin directory is not being created in /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/. Apache:Apache is the owner of this directory and has read/write permissions. 
I set SELinux to permissive to test and SELinux is not causing an issue. 
Nothing is logged in the httpd error_log.
OCSInventory-Reports and OCSInventory-Server reside on the same server so it is not a network issue.
I'm not sure what else to try, is anyone else having this issue?

**Comment by rburkholder2305** [comment]
Nothing?

**Comment by GabrielBTA** [comment]
I have exactly the same problem.

**Comment by kefeto** [comment]
Same thing here ...

**Comment by mmorev** [comment]
Same thing there. Ubuntu 16.04.4, ocs 2.4.1 from git releases. Cannot see anything accordable in logs.

**Comment by gillesdubois** [comment]
Hi,

This issue is no longer relevant since the new plugin engine don't use web services anymore.
Stay tuned for 2.6 Stable and its new plugin engine.

Thx for your contribution.

Regards,
Gilles Dubois.
