### ISSUE TITLE
clean plugin uninstall fails in version 2.4.1 and causes Err_05 on attempt for re-install

### ISSUE THREAD

**Issue by feisenko** [OCSInventory-NG/OCSInventory-Server#104]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Linux

### Server informations
Perl version : 5.26.1
Mysql / Mariadb / Percona version :  Mysql 5.7.16

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
because in Apache/Ocsinventory/Plugins/Modules.pm in line 121 a numeric compare instead of a text compare is done, plugins will not really uninstall and so an attempt for re-install will fail, because the install checks for already existing plugin directory and returns error "Err_05" 
My proposed solution:
change line 121 from:
if($pluginNameUc != ""){
to
if($pluginNameUc ne ""){

Best regards,
Franz

**Comment by gillesdubois** [comment]
Hi,

A new plugin engine has been made in the 2.6RC which remove these behaviors.
Thx for your report.

Gilles Dubois.
