### ISSUE TITLE
Need documentation for Rest API

### ISSUE THREAD

**Issue by kapouik** [OCSInventory-NG/OCSInventory-Server#105]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

Fedora 27

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  

### Server installation method ( Only one choice )
- [x] RPM Package
- [ ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
There is no documentation for Rest API

**Comment by LeoVillaretArrobe** [comment]
Hi,

I am searching for the docs too, but it seems there is no one right now.

### Explanation
You have something like below in your Apache configuration :
```
<Location /ocsapi>
    SetHandler perl-script
    PerlResponseHandler Plack::Handler::Apache2
    PerlSetVar psgi_app '/usr/local/share/perl/5.24.1/Api/Ocsinventory/Restapi/Loader.pm'
</Location>
```

And the routes ares defined at [Api::Ocsinventory::Restapi::Loader](https://github.com/OCSInventory-NG/OCSInventory-Server/blob/master/Api/Ocsinventory/Restapi/Loader.pm)

### Example

Example at line 50 you have `get '/v1/computers' => sub {`, so :
- the path is : *http://your_server* **/ocsapi/v1/computers**
- the method is **GET**

### Compatiblity issue
I cannot test it because the Perl code is compatible with Perl from 5.14 to 5.23 ([refer to this stackoverflow post](https://stackoverflow.com/a/41192741)).

I just saw an error in `Api::Ocsinventory::Restapi::ApiCommon.pm` line 179 because I am using Perl 5.24 (Debian stretch default version) so there is 2 choices :
1. downgrade Perl version
2. update the Perl code

I am waiting for the next OCS version to use the API.

### Feedback

Can you test it and tell me if my forecast is right ?

**Comment by gillesdubois** [comment]
Hi,

Thx for your feedback.
See : http://wiki.ocsinventory-ng.org/#rest-api

Regards,
Gilles Dubois.

**Comment by helicrenz** [comment]
Hello @gillesdubois ,

I just tried mine not found. Any idea?


Regards,

Romeo

**Comment by gillesdubois** [comment]
Hi,

FYI, the rest API is case sensitive.
Can you send me your error log just in case ?

Regards,
Gilles Dubois.

**Comment by helicrenz** [comment]
hello @gillesdubois ,

**tail -50 /var/log/apache2/error.log**


Scalar value @part_query[...] better written as $part_query[...] at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Interface/AssetCategory.pm line 53.
Scalar value @args[...] better written as $args[...] at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Interface/AssetCategory.pm line 53.
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
[Tue Sep 04 06:25:02.123883 2018] [ssl:warn] [pid 24131] AH01909: www.ocs.xxxxxxxxxx.net:443:0 server certificate does NOT include an ID which matches the server name
[Tue Sep 04 06:25:02.124088 2018] [mpm_prefork:notice] [pid 24131] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l mod_perl/2.0.10 Perl/v5.24.1 configured -- resuming normal operations
[Tue Sep 04 06:25:02.124099 2018] [core:notice] [pid 24131] AH00094: Command line: '/usr/sbin/apache2'
[Tue Sep 04 11:37:58.137848 2018] [php7:warn] [pid 38350] [client 100.121.38.1:26188] PHP Warning:  vsprintf(): Too few arguments in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 74, referer: https://ocs.xxxxxxxxxx.net/
[Tue Sep 04 11:37:58.137927 2018] [php7:warn] [pid 38350] [client 100.121.38.1:26188] PHP Warning:  mysqli_query(): Empty query in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 103, referer: https://ocs.xxxxxxxxxx.net/


**tail -f  /var/log/apache2/access.log**


"GET /css/forms.css HTTP/1.1" 200 1651 "https://ocs.xxxxxxxxxx.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
100.121.38.1 - - [04/Sep/2018:11:38:00 +0200] "GET /libraries/select2/css/select2.min.css HTTP/1.1" 200 2411 "https://ocs.xxxxxxxxxx.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
100.121.38.1 - - [04/Sep/2018:11:38:00 +0200] "GET /css/dataTables-custom.css HTTP/1.1" 200 1574 "https://ocs.xxxxxxxxxx.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
100.121.38.1 - - [04/Sep/2018:11:38:00 +0200] "GET /css/ocsreports.css HTTP/1.1" 200 3164 "https://ocs.xxxxxxxxxx.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
100.121.38.1 - - [04/Sep/2018:11:38:00 +0200] "GET /css/header.css HTTP/1.1" 200 1369 "https://ocs.xxxxxxxxxx.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
100.121.38.1 - - [04/Sep/2018:11:38:00 +0200] "GET /js/tooltip.js HTTP/1.1" 200 1104 "https://ocs.xxxxxxxxxx.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
100.121.38.1 - - [04/Sep/2018:11:38:01 +0200] "GET /favicon.ico HTTP/1.1" 200 371070 "https://ocs.xxxxxxxxxx.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
::1 - - [04/Sep/2018:11:38:11 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2l mod_perl/2.0.10 Perl/v5.24.1 (internal dummy connection)"
100.121.38.1 - - [04/Sep/2018:11:38:52 +0200] "GET /ocsapi/v1/my/routes HTTP/1.1" 404 700 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
100.121.38.1 - - [04/Sep/2018:11:38:52 +0200] "GET /favicon.ico HTTP/1.1" 200 371070 "https://ocs.xxxxxxxxxx.net/ocsapi/v1/my/routes" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"

Regards,

Romeo

**Comment by helicrenz** [comment]
@gillesdubois ,

when checking my z-ocsinventory-server.conf. I dont have 

<Location /ocsapi>
    SetHandler perl-script
    PerlResponseHandler Plack::Handler::Apache2
    PerlSetVar psgi_app '/usr/local/share/perl/5.24.1/Api/Ocsinventory/Restapi/Loader.pm'
</Location>


Do i need to add this on my configuration?


Regards,

Romeo

**Comment by helicrenz** [comment]
hello @gillesdubois ,

Any update?


Regards,


Romeo

**Comment by helicrenz** [comment]
Hello @gillesdubois ,


Do you have update? Im getting 404 error not found using perl version 5.24.1

I already install 

sudo apt-get install libswitch-perl
Cpan -i Mojolicious::Lite
Cpan -i Plack::Handler

When i install ocs server it was able to detech it. 



Regards,

Romeo

**Comment by gillesdubois** [comment]
Hi,

Have you activated your zz-ocsinventory-restapi.conf file ?

Regards,
Gilles Dubois.

**Comment by helicrenz** [comment]
Do you mean upon installation if the rest api is activated? or do i need to run ./zz-ocsinventory-resapi.conf to activate it?

**Comment by helicrenz** [comment]
Hello @gillesdubois ,

Thanks for the response i manage to fix the issue. for the API.

ln -s /etc/apache2/conf-available/zz-ocsinventory-restapi.conf /etc/apache2/conf-enabled/zz-ocsinventory-restapi.conf
chown -R www-data:www-data /var/lib/ocsinventory-reports
apachectl -t
systemctl restart apache2


Regards,

Romeo
