### ISSUE TITLE
Missing include in Module Ocsinventory/Server/Inventory/Update.pm

### ISSUE THREAD

**Issue by mgoette** [OCSInventory-NG/OCSInventory-Server#108]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

    OS Name :		    Linux x86_64
    Version :           3.10.0-862.3.2.el7.x86_64
    RAM installed :     7805 MB
    Free RAM :          6192 MB
    CPU :               Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
    Distribution :      CentOS Linux 7 (Core)
    PHP Version :		5.6.36
    Web Server :        Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.36 mod_perl/2.0.10 Perl/v5.16.3
    Database Server :   Ubuntu 16.04 version 10.0.34-MariaDB-0ubuntu0.16.04.1
    Version OCSReports: 2.4.1

### Problem's description
I guess you forgot to include the following line in Ocsinventory/Server/Inventory/Update.pm:
use Apache::Ocsinventory::Interface::AssetCategory;

This leads to the following problem:
[Thu May 24 14:29:53.675622 2018] [perl:error] [pid 2110] [client x.x.x.x:55054] Undefined subroutine &Apache::Ocsinventory::Server::Inventory::Update::set_asset_category called at /usr/local/share/perl5/Apache/Ocsinventory/Server/Inventory/Update.pm line 48.\n

Best regards,
Maik

**Comment by gillesdubois** [comment]
Hi,

Thx for your report this problem has been fixed.

Regards,
Gilles Dubois.
