### ISSUE TITLE
MMotherboard and MModel not getting written into the database

### ISSUE THREAD

**Issue by wcom939** [OCSInventory-NG/OCSInventory-Server#109]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Windows/Linux

### Server informations
Perl version :  ?
Mysql / Mariadb / Percona version :   ?

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
For both linux and windows agents the MMotherboard and MModel fields are not getting written see https://github.com/OCSInventory-NG/WindowsAgent/issues/85 for more info.

Seems like the code changes here never got merged into the server application, but did get merged into reports/agents:
https://www.ocsinventory-ng.net/forums.ocsinventory-ng.org/viewtopic.php?id=5579

**Comment by gillesdubois** [comment]
Hi,

Thx for your report.

A fix has been made for server : https://github.com/OCSInventory-NG/OCSInventory-Server/pull/161 

Regards,
Gilles Dubois.
