### ISSUE TITLE
OCS_INVENTORY_WRITE_DIFF ne fonctionne pas avec des tables possédant un champ DateTime 

### ISSUE THREAD

**Issue by TiVince** [OCSInventory-NG/OCSInventory-Server#11]
OCS_INVENTORY_WRITE_DIFF ne fonctionne pas avec des tables possédant un champ DateTime ( ou Date)

pour reproduire les problèmes (tests réalisés avec l’agent 2.0.5 et 2.1.1.1) :
- activer l’option INVENTORY_WRITE_DIFF dans la console
- déboguer les variables $comp_db et $comp_xml du module Apache/Ocsinventory/Server/Inventory/Update.pm ( situées lignes 106 & 107)

-ajouter / supprimer un logiciel (ou positionner mask => 0 dans le fichier Map.pm pour la section softwares) pour déclencher les comparaisons XML vs BDD

1) l’agent OCS retourne les dates sous le format AAAA/MM/JJ
la BD  stocke les dates sous le format  AAAA-MM-JJ 00:00:00
La comparaison est toujours en échec 
 exemple avec la  table softwares :

comp_xml :Langue neutreMicrosoft .NET Framework 4.5.2Microsoft Corporation2015/12/05{3911CF56-9EF2-39BA-846A-C27BD3CD0685}04.5.51209321
comp_db  :Langue neutreMicrosoft .NET Framework 4.5.2Microsoft Corporation2015-12-05 00:00:00{3911CF56-9EF2-39BA-846A-C27BD3CD0685}04.5.51209321

2) l’agent OCS retourne la valeur 0000//0/0/00 lorsqu’il ne peut pas déterminer la date (au moins pour la section softwares)
cette valeur est transformée en 0000-00-00 00:00:00 dans la base 

comp_xml :OCS Inventory NG Agent 2.1.1.1OCS Inventory NG Team0000//0/0/00OCS Inventory NG Agent02.1.1.1321
comp_db  :OCS Inventory NG Agent 2.1.1.1OCS Inventory NG Team0000-00-00 00:00:00OCS Inventory NG Agent02.1.1.1321

3) pour la table drives :

-aucune date n’est retournée par l’agent, la BD stocke la date par défaut:

comp_xml :D:0CD-Rom Drive00
comp_db  :D:0CD-Rom Drive000000-00-00

contournement : donner une valeur fallback dans Map.pm au champs CREATEDATE

```
 CREATEDATE => {fallback=>'0000-00-00'}
```

**Comment by gillesdubois** [comment]
Bonjour,

De ce que je vois, vos tests ont été réalisé seulement sur l'agent windows, je vais tenter de reproduire le problème sur un agent Unix :
  - Si celui-ci souffre du même bug cela sera donc un problème serveur.
  - Si seul l'agent windows souffre de ce problème l'issue sera déplacée dans l'agent windows et un fix sera mis en place dès que possible.

Si vous avez des précision entre-temps n'hésitez pas a mettre a jour la demande.

Merci de participer au projet ocs !
Cordialement, Gilles Dubois.

**Comment by StCyr** [comment]
Hello @gillesdubois 

Je viens de faire une PR pour résoudre un problème similaire (ie: problème de format de date): https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/334

Je pense que le problème se produit depuis la version 5.6.4 de MySQL, car, à partir de cette version les info de datetime sont stockées en millisecondes par défaut.

Une solution simple à ce problème consiste à créer les tables SQL en utilisant DATETIME(0) plutôt que DATETIME ( DATETIME(0) empêche le stockage au format milliseconde). Par exemple:

```sql
CREATE TABLE `softwares` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HARDWARE_ID` int(11) NOT NULL,
  `PUBLISHER` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `VERSION` varchar(255) DEFAULT NULL,
  `FOLDER` text,
  `COMMENTS` text,
  `FILENAME` varchar(255) DEFAULT NULL,
  `FILESIZE` int(11) DEFAULT '0',
  `SOURCE` int(11) DEFAULT NULL,
  `GUID` varchar(255) DEFAULT NULL,
  `LANGUAGE` varchar(255) DEFAULT NULL,
  `INSTALLDATE` DATETIME(0) DEFAULT NULL,  <<<<<<<<<<<<< replace DATETIME par DATETIME(0) ici
  `BITSWIDTH` int(11) DEFAULT NULL,
  PRIMARY KEY (`HARDWARE_ID`,`ID`),
  KEY `NAME` (`NAME`),
  KEY `VERSION` (`VERSION`),
  KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
```

À tester si cette définition est compatible avec MySQL<5.6.4 cependant.

Une autre solution consiste à CASTer tout les SELECT sur des DATETIME vers DATETIME(0). Par exemple (voir ma PR mentionné ci-dessus pour plus de détail si nécessaire):

```php
  $list_fields = array($l->g(475) => 'FILEID',
-        $l->g(593) => 'from_unixtime(FILEID)',
+        $l->g(593) => 'CAST(from_unixtime(FILEID) AS DATETIME(0))',
         'SHOWACTIVE' => 'NAME',
         $l->g(440) => 'PRIORITY',
         $l->g(464) => 'FRAGMENTS',
```

À confirmer également que cela fonctionne sous MySQL<5.6.4
