### ISSUE TITLE
Problème d'import local avec OCS 2.4.1

### ISSUE THREAD

**Issue by cyberbof** [OCSInventory-NG/OCSInventory-Server#113]
Operating system : 
Mac OS 10.11 or 10.13
    Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/5.6.36 mod_perl/2.0.10 Perl/v5.16.3
    Version du client de base de données : libmysql - 5.5.56-MariaDB
    Extension PHP : mysqli Documentation
    Version de PHP : 5.6.36

### Server installation method ( Only one choice )
 Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
Le répertoire de LOGS n'est pas ouvert en écriture (par défaut: /var/lib/ocsinventory-reports/logs) et j'ai controlé les droits même en chmod 777 il ne prend pas.
Autrement j'ai ce problème d'importation :
Erreur HTTP/1.1 500 Internal Server Error avec un import local !
Wed Jun 20 18:23:34 2018;12475;318;CORI-ADMIN002-2018-06-20-08-18-24;::1;OCS_local_7011;session;missing
Wed Jun 20 18:23:34 2018;12475;114;CORI-ADMIN002-2018-06-20-08-18-24;::1;OCS_local_7011;inventory;no_session
Wed Jun 20 18:23:34 2018;12475;104;CORI-ADMIN002-2018-06-20-08-18-24;::1;OCS_local_7011;inventory;incoming
Wed Jun 20 18:23:34 2018;12475;515;CORI-ADMIN002-2018-06-20-08-18-24;::1;OCS_local_7011;end;error

**Comment by gillesdubois** [comment]
Bonjour,

Pouvez-vous essayer avec la version 2.5 ?

Cordialement,
Gilles Dubois.
