### ISSUE TITLE
Motherboard and graphics card details are not fetch in server 

### ISSUE THREAD

**Issue by Dhakshinkarthic** [OCSInventory-NG/OCSInventory-Server#114]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 18.04

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  10.3.7

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [* ] Manual installation

### OCS Inventory informations
Ocs server version : 1:10.3.7

### Problem's description
Hi Guys,

I have a motherboard and graphics card not fetching issue in OCS server. Please tell me its a plugin issue or installation issue?
And I want another info. what agent is perfect to install the ubuntu and windows systems.  please guide me to fix the issue.

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed in the latest version, can you try to upgrade your OCS Inventory Server ?

Regards,
Gilles Dubois.
