### ISSUE TITLE
Quelques fautes de frappe dans setup.sh

### ISSUE THREAD

**Issue by xdelatour** [OCSInventory-NG/OCSInventory-Server#115]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
*Describe your problem here*

Dans certains messages d'erreur du script setup.sh, des noms de variables ne sont pas précédés par le symbole dollar et ne seront donc pas remplacés par leur valeur au moment de l'affichage.

Exemple ligne 1551 :
    `echo "*** ERROR: Unable to create ADM_SERVER_STATIC_DIR/$ADM_SERVER_STATIC_REPORTS_DIR, please look at error in $SETUP_LOG and fix !"`

Cela concerne la variable ADM_SERVER_STATIC_DIR lignes 1551 et 1593 et ADM_SERVER_VAR_DIR lignes 1673, 1707, 1741 et 1774.

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed with the pull request above.

Regards,
Gilles Dubois.
