### ISSUE TITLE
Duplicate computers

### ISSUE THREAD

**Issue by dioubernardo** [OCSInventory-NG/OCSInventory-Server#116]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 14.04

### Server informations
Perl version : 5.18.2
Mysql / Mariadb / Percona version :  Mysql 5.5.60

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
In Config > Config > Server I configured AUTO_DUPLICATE_LVL to Serial + macaddress + uuid

my database has the following records

id 2647
![image](https://user-images.githubusercontent.com/3487994/42644103-1cd864f6-85d1-11e8-8941-4ba85f5f9599.png)
![image](https://user-images.githubusercontent.com/3487994/42644142-3759b5c8-85d1-11e8-9f76-7e526da72e65.png)
![image](https://user-images.githubusercontent.com/3487994/42644178-4ec2060c-85d1-11e8-932f-445e5a1c7936.png)

id 2752
![image](https://user-images.githubusercontent.com/3487994/42644208-632b6836-85d1-11e8-84d6-535d5339f0f5.png)
![image](https://user-images.githubusercontent.com/3487994/42644239-77aeb1f0-85d1-11e8-89cc-fa4d81674f5c.png)
![image](https://user-images.githubusercontent.com/3487994/42644269-8af0e59e-85d1-11e8-8981-bae3e73852cd.png)

This is just an example because we have several other duplicate computers.

**Comment by gillesdubois** [comment]
Hi,

The duplicate problem has been fixed with the latest version of the server (2.6RC) and agent (2.6.0.0) which will be released soon.

Regards,
Gilles Dubois.
