### ISSUE TITLE
IPDiscovery counter does not seems right

### ISSUE THREAD

**Issue by dytrip77** [OCSInventory-NG/OCSInventory-Server#119]
OS Version : Centos 7.5
PHP Version : 7.2.8
Web Server : Apache/2.4.6 (CentOS) PHP/7.2.8 mod_perl/2.0.10 Perl/v5.16.3
Database Server : MariaDB Server version 10.3.8-MariaDB
Version OCSReports: 2.4.1

### Problem's description
Weird counter in IPDiscovery

![capture2ocs](https://user-images.githubusercontent.com/22068278/42914992-e576a4a0-8b2f-11e8-8ea1-9692600f5ccc.JPG)

**Comment by gillesdubois** [comment]
Hi,

Thx for your report.
This bug have been fixed in the new release (2.5)

Regards,
Gilles Dubois.
