### ISSUE TITLE
Why including PHP Pear files ?

### ISSUE THREAD

**Issue by guimard** [OCSInventory-NG/OCSInventory-Server#121]
Hello,
since 2.5, OCS-Reports includes PHPMailer _(which is a library with a bad security history)_. Why do you include it in your source code instead of prerequisite ? You may to patch frequently it due to CVE

**Comment by gillesdubois** [comment]
Hi @guimard,

This problem is being processed, we are testing our code by using the distribution phpmailer lib.
If our tests are ok we will remove the pear files from the reports.

Regards,
Gilles Dubois.

**Comment by kapouik** [comment]
As initial possibility to export phpmailer:
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/76654f26ade3cd71ca1bacee5e30b31c5b611463

I have create a branch to begin the work on it.

**Comment by gillesdubois** [comment]
Hi,

We are and will be using composer from now.
There won't be any PHP librairies in our code anymore.

Regards,
Gilles Dubois.
