### ISSUE TITLE
Security: privacy breach

### ISSUE THREAD

**Issue by guimard** [OCSInventory-NG/OCSInventory-Server#122]
### OCS Inventory informations
Ocs server version : 2.5

### Problem's description
Instead of using `themes/OCS/banniere.png`, `ocsreports/templates/OCS_template.html` calls https://i.imgur.com/1sDetbn.png

**This is clearly a privacy breach**. Please change this !

**Comment by gillesdubois** [comment]
Hi,

We are aware of the issues on mail notifications. (that not the only one)
OCS Inventory Team is working hard on fixing them all.

Thanks for your report.
You will be notified when a patch will be available.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi, the problem has been fixed. (sse PR mentionned above)
Instead of using a third party website we are using our CDN.

**Comment by guimard** [comment]
@gillesdubois: hello, this is not satisfactory, there is always a form of user tracking. Why don't you embed image into the mail ? _(src=...base64)_

**Comment by guimard** [comment]
Other way, points to the origin server

**Comment by guimard** [comment]
Note also that many MUA don't display external images

**Comment by gillesdubois** [comment]
@guimard

The problem is base64 encoded images are not really well supported by mail provided and mail servers. Base 64 based content is blocked most of the time.

Point to the origin server can be nice idea, but ocsreports can is not always accessible in the whole network. We can't be sure that the image will be displayed. 

In the case the user don't want to use the CDN, he can use a custom template

**Comment by guimard** [comment]
My problem is that I can't publish this in Debian. Can I remove the whole table ?

**Comment by guimard** [comment]
@gillesdubois: Is this image really needed ?

**Comment by guimard** [comment]
Other way, use MIME to embed image. This is fully supported by any MUA (except mutt :smile:)

**Comment by gillesdubois** [comment]
If it only bother you for packaging, can we remove the image for the debian version ? Or provide an alternative template without images.

**Comment by guimard** [comment]
@gillesdubois: yes, I need only a patch to remove this _(however, I find that external images in mail is not good practice)_
