### ISSUE TITLE
PHP Warning: array_key_exists() 

### ISSUE THREAD

**Issue by tomJa99** [OCSInventory-NG/OCSInventory-Server#127]
### General informations
Operating system : Centos 6.9

### Server informations
Perl version : 5.10.1
Mysql / Mariadb / Percona version :  MySQL 5.1.73
PHP: 5.6

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.5 

### Problem's description

Hi,
I recently updated my OCS Inventory Server from version 2.4 to 2.5. Whenever I try to use the multicriteria search, I get this php warning: 
PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /usr/share/ocsinventory-reports/ocsreports/require/search/Search.php on line 754.
I currently use PHP 5.6.

Greetings 
tomJa99

**Comment by RudyLaurent** [comment]
Hi @tomJa99 ,

This issues has already been fixed : 
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/532.

Regards,
Rudy Laurent.
