### ISSUE TITLE
OCSInventory-Server 2.5 api not working

### ISSUE THREAD

**Issue by helicrenz** [OCSInventory-NG/OCSInventory-Server#133]
Hello,

Im trying to access api but im only getting not found here is my server spec

**Operating system**

OS Name : Linux x86_64
Version : 4.9.0-6-amd64
RAM installed : 3946 MB
Free RAM : 3483 MB
CPU : Intel(R) Xeon(R) CPU E5540 @ 2.53GHz
Distribution : Debian GNU/Linux 9 (stretch)

**Software**

PHP Version : 7.2.8
Web Server : Apache/2.4.25 (Debian)
Database Server : Debian 9.1 version 10.1.26-MariaDB-0+deb9u1
Version OCSReports: 2.5

i already enable web service still im getting not found anyone any idea?

  PerlSetEnv OCS_OPT_WEB_SERVICE_ENABLED 1
  PerlSetEnv OCS_OPT_WEB_SERVICE_RESULTS_LIMIT 100
  PerlSetEnv OCS_OPT_WEB_SERVICE_PRIV_MODS_CONF "WEBSERV_PRIV_MOD_CONF_FILE"

Be careful: you must restart apache to make settings taking effects

 Configure engine to use the settings from this file
 PerlSetEnv OCS_OPT_OPTIONS_NOT_OVERLOADED 0

 Try to use other compress algorithm than raw zlib
 GUNZIP and clear XML are supported
PerlSetEnv OCS_OPT_COMPRESS_TRY_OTHERS 1

Regards,

Romeo

**Comment by helicrenz** [comment]
hello @gillesdubois ,

Any idea? im getting error 404 when i tried to access  ocs.XXXX.com/ocsapi/v1/my/routes

**Comment by helicrenz** [comment]
@gillesdubois , hello Gilles any idea how can i check why its not working

**Comment by gillesdubois** [comment]
Hi,

Did you following this documentation ? http://wiki.ocsinventory-ng.org/11.Rest-API/Introduction/

Regards,
Gilles Dubois.

**Comment by proyectotau** [comment]
Hello

I think `/v1/my/routes` is missing from _Api/Ocsinventory/Restapi/Loader.pm_
