### ISSUE TITLE
[Fri Sep 14 14:54:05.721723 2018] [perl:error] [pid 6497] [client 10.10.10.171:41784] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/System.pm line 282.\n

### ISSUE THREAD

**Issue by AnnoyingTechnology** [OCSInventory-NG/OCSInventory-Server#135]
### General informations
Operating system : 
Agent : Debian buster
Server : Debian stretch

### Server informations
Perl version : 5.24.1
Mysql / Mariadb / Percona version :  10.1.26

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.5

### Problem's description

I installed the server and it appears to be running properly after the lengthy installation process.
Upon installing an agent, thru APT on a workstation : 
a) the agent doesn't create a service on the workstation, is one supposed to manually manage the process' life?
b) when lauching the agent, it complains about `[error] Cannot establish communication : 500 Internal Server Error` 
which, on the server's `/var/log/apache2/error.log` gives : 
`[Fri Sep 14 14:54:05.721723 2018] [perl:error] [pid 6497] [client 10.10.10.171:41784] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/System.pm line 282.\n `

**Comment by mellofone** [comment]
I have the exact same issue and error on Ubuntu 18.04.1 LTS.

**Comment by AnnoyingTechnology** [comment]
I have personally stopped my testing of OCS, this software seems too far away from being mature and appropriate for a production environment.

**Comment by fisherhu** [comment]
You have to double check the db configuration. At least in three places:
/usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php
/etc/apache2/conf-enabled/zz-ocsinventory-restapi.conf
/etc/apache2/conf-enabled/z-ocsinventory-server.conf

**Comment by gillesdubois** [comment]
Hi,

Like @fisherhu said rollback and do error are related to the configuration files mention above.

Most likely a database misconfiguration.

Regards,
Gilles Dubois.

**Comment by gustavocagninzup** [comment]
```sql
grant all privileges on *.* to "ocs"@"%" IDENTIFIED BY "ocs";
```
Solved my problem, database didn't connect with the remote host

**Comment by GillesRonsin** [comment]
> You have to double check the db configuration. At least in three places: /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php /etc/apache2/conf-enabled/zz-ocsinventory-restapi.conf /etc/apache2/conf-enabled/z-ocsinventory-server.conf

using docker version, none of these files are present in the container.

the db is connected because I can log in UI: 'reports' works well
my 'rollback' issue is coming only when agents try to send Prolog

my server is TLS configured behind traefik and self signed certificate
