### ISSUE TITLE
Error in agent update: Quantifier follows nothing in regex

### ISSUE THREAD

**Issue by giltachy** [OCSInventory-NG/OCSInventory-Server#137]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOs 7

### Server informations
Perl version : 5.16.3
Mysql / Mariadb / Percona version :  mariadb 5.5.60

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.5 

### Problem's description
When some machines try to update (agent version 2.4 on windows) the below error is reported on error log on server

Quantifier follows nothing in regex; marked by <-- HERE in m/* <-- HERE Office*/ at /root/perl5/lib/perl5/Apache/Ocsinventory/Interface/SoftwareCategory.pm line 77.

**Comment by gillesdubois** [comment]
Hi,

This regex problem has been fixed in the 2.6 version.

Regards,
Gilles Dubois.
