### ISSUE TITLE
Question: How to push data by event?

### ISSUE THREAD

**Issue by nohnaimer** [OCSInventory-NG/OCSInventory-Server#140]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOS 7.5 x64

### Server informations
Perl version : 5.16.3
Percona version :  5.7.22-22

### Server installation method ( Only one choice )
- RPM Package

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
Everything works well, except for this [error](https://github.com/OCSInventory-NG/OCSInventory-Server/issues/48)!
But the question is different:
Is it possible to somehow push the data into my api when the user login changes? That is, when changing the user’s login field, send the username and computer name to my api, not only save it to the database ocs inventory.

**Comment by gillesdubois** [comment]
Hi,

Unfortunately, without further developments, you won't be able to push to a third party API on event.

Regards,
Gilles Dubois.
