### ISSUE TITLE
search with various criteria is blank

### ISSUE THREAD

**Issue by demoli2** [OCSInventory-NG/OCSInventory-Server#143]
### General informations
Operating system : Debian Wheezy amd64. Yes it's old !

### Server informations
Perl version : v5.14.2
Mysql version :  5.0.51a

### Server installation method ( Only one choice )
- Install SH

### OCS Inventory informations
Ocs server version :  2.5

### Problem's description

the page "search with various criteria" is blank. The others pages are OK.
/var/log/apache2/error.log :
`PHP Fatal error:  Can't use method return value in write context in /usr/share/ocsinventory-reports/ocsreports/require/search/TranslationSearch.php on line 224, referer: https://xxxxxx/ocsreports/index.php?function=visu_search`
Line 224 : `   if(empty($l->g($this->translationArray[$name]))){`

Any idea ?

**Comment by gillesdubois** [comment]
Hi,

You need to upgrade your PHP.

For everything related to the webconsole plz create an issue here instead : 
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues

Regards,
Gilles Dubois.
