### ISSUE TITLE
File cd_Hpmgmt.php is empty!!!

### ISSUE THREAD

**Issue by jeisoft** [OCSInventory-NG/OCSInventory-Server#146]
Hi!
I have installed this plugin but it doesnt show anything under Miscellaneous section.
Maybe it is coz this file is empty???
Watch!
https://github.com/PluginsOCSInventory-NG/HPmgmt/blob/master/cd_Hpmgmt/cd_Hpmgmt.php

**Comment by MyTheValentinus** [comment]
Hello,
This plugin do not offer data display into interface.
And it's the wrong repository to post plugin issue based.
If you want you can submit pull request.
Thanks
