### ISSUE TITLE
Apache IfModule mod_php5 need to be upgraded for php7

### ISSUE THREAD

**Issue by nirgal** [OCSInventory-NG/OCSInventory-Server#15]
File `etc/ocsinventory-reports.conf` contains `<IfModule mod_php5.c>`

**Comment by gillesdubois** [comment]
Hi,

The problem is that the majority of people still have php5 installed.
We need a workaround which take php5 and php7 at the same time.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Fixed https://github.com/OCSInventory-NG/OCSInventory-Server/commit/a1f550f14404dffeed7369481512fad815485630
