### ISSUE TITLE
Stored XSS in /ocsinventory upload

### ISSUE THREAD

**Issue by vsimhv** [OCSInventory-NG/OCSInventory-Server#153]
### General informations
Operating system : CentOS 6.10 (not related)

### Server informations
Perl version : 5.10.1
Mysql / Mariadb / Percona version : 5.5.62  

### Server installation method ( Only one choice )
- [ ] Install SH

### OCS Inventory informations
Ocs server version : 2.5 

### Problem's description
The User-agent field, which can be spoofed by the uploader, is not being sanitized correctly by the parser and allows for some HTML tags, including p, i, center, font, br. This useragent field is being displayed in the webapplication and therefore can be used to attack authenticated user.

**Comment by simhpl** [comment]
I was wondering, is there even a valid reason to have UserAgent displayed in the application? What is the use case for having it there?

**Comment by gillesdubois** [comment]
This CVE has been fixed and is not present anymore.

Regards,
Gilles Dubois.
