### ISSUE TITLE
Cannot install any plugins

### ISSUE THREAD

**Issue by lechardonneret** [OCSInventory-NG/OCSInventory-Server#156]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 18.04.1
Apache v2.4.29
PHP v7.2.10

### Server informations
Perl version : 5.26.1
Mysql / Mariadb / Percona version :  
Mysql v 5.7.24

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.6RC

### Problem's description
*I downloaded plugins at https://github.com/PluginsOCSInventory-NG, I copy them to / usr / share / ocsinventory-reports / ocsreports, when I try to install them from my console, no plugins is detected on my server "there is no extention to install" ; I dont know what's wrong  on my config help me please thank you.*

**Comment by lechardonneret** [comment]
I see that the version 2.6RC architecture has been modified, the folder download was replaced by the folder extension is where we must put the plugins folder uncompress, now in the console I see my plugins but when I click On install the page remains blank on error.log I have the following error message: "Error: Call to undefined function install_install_Chekfiles () in /usr/share/ocsinventory-reports/ocsreports/require/extensions/ExtensionManager.php: 167 \ nStack trace: \ n # 0 /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_extensionmanager/ms_extensionmanager.php(79): ExtensionManager-> installExtension ('Chekfiles') \ n # 1 / usr / share /ocsinventory-reports/ocsreports/require/header.php(444): require ('/ usr / share / ocsi ...') \ n # 2 /usr/share/ocsinventory-reports/ocsreports/index.php(44) ): require ('/ usr / share / ocsi ...') \ n # 3 {main} \ n thrown in /usr/share/ocsinventory-reports/ocsreports/require/extensions/ExtensionManager.php on line 167, referer : h TTPs: //localhost/ocsreports/index.php function = ExtensionManager?
[Mon Dec 31 14: 04: 27.958418 2018] [perl: error] [pid 3755] [client 10.0.128.19:49584] Not a HASH reference at /usr/local/share/perl/5.26.1/Apache/Ocsinventory/ Server / Capacities / Ipdiscover.pm line 74. \ n "

**Comment by gillesdubois** [comment]
Hi,

To install 2.6 extensions you need to get the rework branch of the plugin you want to install.

Let's take winusers as an example : https://github.com/PluginsOCSInventory-NG/winusers/tree/rework

Download the content of the git repository and put in /usr/share/ocsinventory-reports/extensions/winusers/

Then install it trough the web console (you may need to log / relog)

To install the communication server part us this documentation : http://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/

Regards,
Gilles Dubois.

**Comment by lechardonneret** [comment]
Bonsoir GILLES,
merci pour votre réponse je vais tester ça au bureau demain,  une autre chose que j'ai remarqué aussi en version 2.6 les onglets de mes données administratives ont été permuter l'onglet B et à la place de D. les autres C et A = "TAG" sont restés dans leur position, comment puis je régler ça je ne maitrise pas le développement en PHP.
Crdlt.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by charleneauger** [comment]
Bonjour @lechardonneret ,
Quelle était votre ancienne version de votre serveur OCS ?

Cordialement,
Charlène Auger

**Comment by penflame** [comment]
Bonjour,
J'ai exactement les meme erreurs avec l'installation Web ou via le script Python:
>cd /usr/share/ocsinventory-reports/ocsreports/extensions
>git clone https://github.com/PluginsOCSInventory-NG/officepack.git
>python3 /usr/share/ocsinventory-reports/ocsreports/tools/install_plugin.py
ERROR: check if map.pm and [pluginName].conf exist

Et via l'interface Web:
PHP Fatal error:  Uncaught Error: Call to undefined function extension_install_officepack() in /usr/share/ocsinventory-reports/ocsreports/require/extensions/ExtensionManager.php:167\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_extensionmanager/ms_extensionmanager.php(79): ExtensionManager->installExtension('officepack')\n#1 /usr/share/ocsinventory-reports/ocsreports/require/header.php(444): require('/usr/share/ocsi...')\n#2 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#3 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/require/extensions/ExtensionManager.php on line 167, referer: https://inventaire.4sys.fr/ocsreports/?function=extensionmanager

    Version de PHP : 7.0.33
    Serveur Web : Apache/2.4.25 (Debian)
    Serveur SQL : MySQL Community Server (GPL) version 5.7.24
    Version OCSReports: 2.6RC

**Comment by bensonzhou** [comment]
same problem about extension install ,   extension manager   can not show the dropbox  and the install  button.

**Comment by charleneauger** [comment]
Hi @lechardonneret @bensonzhou @penflame ,

Many fixes have been made for the extension engine. Thank you for downloading a nightly server to have the corrections:
http://download.ocsinventory-ng.org/nightly/

Best regards,
Charlene Auger

**Comment by lechardonneret** [comment]
Hi, 
Je confirme problème résolu après mis à jour du serveur vers 2.6.
Merci.
