### ISSUE TITLE
Problem connect agent with server in sql the file Groups.pm and System.pm  - 2.6_RC

### ISSUE THREAD

**Issue by AlbertoTorre** [OCSInventory-NG/OCSInventory-Server#158]
### General informations
Operating system : RedHat 7.5 enterprise

### Server informations
Perl version : This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 38 registered patches, see perl -V for more detail)

Mysql / Mariadb / Percona version :  
- MYSQL 8.0.13
- Apache/2.4.6 (Red Hat Enterprise Linux)
- PHP 7.1.25 (cli) (built: Dec  8 2018 13:52:58) ( NTS )
  Copyright (c) 1997-2018 The PHP Group
  Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
  with Zend OPcache v7.1.25, Copyright (c) 1999-2018, by Zend Technologies

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.6_RC
Agent:  OCS-NG_WINDOWS_AGENT_v2.4.0.0;

### Problem's description
DBD::mysql::db do failed: Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' at /usr/local/share/perl5/Apache/Ocsinventory/Server/System.pm line 193.
DBD::mysql::db do failed: Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' at /usr/local/share/perl5/Apache/Ocsinventory/Server/System.pm line 193.
DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups
    g LEFT OUTER JOIN locks l
    ON l.HARDWARE_ID=g.HARDWARE_ID
    WHE' at line 2 at /usr/local/share/perl5/Apache/Ocsinventory/Server/Groups.pm line 72.

**Comment by grogyroger** [comment]
Hello,

We have exactly the same issue:

:mysql::db do failed: Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/System.pm line 193.
--
  | DBD::mysql::db do failed: Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/System.pm line 193.
  | DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups
  | g LEFT OUTER JOIN locks l
  | ON l.HARDWARE_ID=g.HARDWARE_ID
  | WHE' at line 2 at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Groups.pm line 72.

Do you had any answer ?

Regards
Grégory

**Comment by chirpingr0se** [comment]
I have the exact same issue. 

The first part with "NO_AUTO_CREATE_USER" is easy to fix:
If you use mysql Server 8+, you have to remove (in every file) this option in the sql_mode syntax with none.  Example change the line 223 (ocs server 2.7) in System.pm
From: 
("SET sql_mode='NO_AUTO_CREATE_USER','Some-other-option-which-name-i-forgot'"); 
To: 
"(SET sql_mode=''");
restart your Apache2.service

Also this fixed my problem that I got blank informations from my Windows Agents into reports.
(Unless i didn't remove the NO_AUTO_CREATE_USER in sql_mode, I wasn't even able to start or get an page of reports)

Now I try to find a fix for the error at line 72 in Groups.pm...

**Comment by gillesdubois** [comment]
Hi,

It has already been fixed : https://github.com/OCSInventory-NG/OCSInventory-Server/pull/246
It will be available with the upcomming 2.8 version.

Regards,
Gilles Dubois.
