### ISSUE TITLE
RESTAPI- List IP Discover Networks Elements return null

### ISSUE THREAD

**Issue by dust63** [OCSInventory-NG/OCSInventory-Server#167]
### General informations
Operating system : Cent OS 7

### Server informations
Perl version : 5.16.3
Mysql / Mariadb / Percona version :  MariaDB 10.3.12

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.5

### Problem's description
I get my network list with the route http://myocsserver/ocsapi/v1/ipdiscover/

When I tried to get network devices from a network range I have null result.
I use the route http://myocsserver/ocsapi/v1/ipdiscover/192.168.1.0

In OCS reports portal I see 395 machines in the discover network that I want to interogate by the API.

For the computer API Routes, all is ok.

Regards.

**Comment by gillesdubois** [comment]
Hi,

We recently reworked the IPDiscover along with the REST API.
The next version will fix this behavior.

Regards,
Gilles.
