### ISSUE TITLE
[REST API] memory leak (garbage collecting ?)

### ISSUE THREAD

**Issue by N3RG4L** [OCSInventory-NG/OCSInventory-Server#168]
### General informations
Operating system : 4.14.88-88.76.amzn2.x86_64 (amazon linux 2)

### Server informations
Perl version : v5.16.3
Mysql / Mariadb / Percona version :  5.6.35

### Server installation method ( Only one choice )
- [X] Install SH

### OCS Inventory informations
Ocs server version :  2.5

### Problem's description
Memory leak, when calling Rest API.
Example : /ocsapi/v1/computers?start=0&limit=400
Everytime I send a request, memory is used in the server, and not freed after, so by requesting multiple times the request, the server gets stuck, and begins to drop oom (out of memory) and killing processes.

Best regards,

**Comment by gillesdubois** [comment]
Hi,

We've made some improvments in the latest version on memory usage.
Please note that if you want to use less memory, you can still reduce the limit number.

Apache and Mojolicious configuration can also impact API's performence.

Regards,
Gilles Dubois.
