### ISSUE TITLE
set FQDN as hostname

### ISSUE THREAD

**Issue by fourti** [OCSInventory-NG/OCSInventory-Server#171]
### General informations
Operating system : CentOS7

### Server informations
Perl version : 5.16.3
Mysql / Mariadb / Percona version :  5.7.11

### Server installation method ( Only one choice )
- [ x ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
I would like to set the hostname as FQDN.
Right now it's just "host1" with workgroup "example.com"

I would like to see the hostname as "host1.example.com"

**Comment by charleneauger** [comment]
Hi,

We don't plan on implementing this kind of behavior since we already register the domain name.
having the FQDN machine name is not a plus for us.

Regards,
Charlene Auger
