### ISSUE TITLE
Recherche multicritères par joker * 

### ISSUE THREAD

**Issue by lechardonneret** [OCSInventory-NG/OCSInventory-Server#175]
### General informations
Operating system : 
Ubuntu Linux x86_64
### Server informations
Perl version : V 5.26.1
Mysql / Mariadb / Percona version :  
Mysql v 5.7.25 
### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.6

### Problem's description

Bonjour,
en voulant créer des groupes dynamique par recherche multicritères ,je sélectionne ACCOUNT INFO et TAG
ma requête c'est de regrouper toutes les machines ayant le TAG A/B/C , en faisant une recherche par joker * ,je met A/B/* néant aussi A/* rien seul la recherche A qui génère les machines A/B/C.
J’espère avoir bien expliquer le bug, merci de prendre le problème en considération.
Cordialement MOUNIR.

**Comment by charleneauger** [comment]
Bonjour @lechardonneret,

La recherche multicritères n'utilise pas les jokers. Il suffit de faire votre recherche avec LIKE.
Exemple: Accountin TAG LIKE A/B

Cordialement,
Charlène Auger

**Comment by lechardonneret** [comment]
> Bonjour @lechardonneret,
> 
> La recherche multicritères n'utilise pas les jokers. Il suffit de faire votre recherche avec LIKE.
> Exemple: Accountinfo TAG LIKE A/B
> 
> Cordialement,
> Charlène Auger

Merci pour l'infos.
