### ISSUE TITLE
IPDiscovery with MySql 8 set DATE to 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by phil0135** [OCSInventory-NG/OCSInventory-Server#177]
### General informations
Operating system : openSUSE 42.3 (x86_64)

### Server informations
Perl version : v5.26.3 
Mysq version :  8.0.15

### Server installation method ( Only one choice )
- [X ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description

If executed on MySQL >= 8 the SQL Update Statement in Line 251 in Apache/Ocsinventory/Server/Capacities/Ipdiscover.pm sets column DATE to 0000-00-00 00:00:00 and not to CURRENT_TIMESTAMP. 

The statement should be:
`$update_req = $dbh->prepare('UPDATE netmap SET IP=?,MASK=?,NETID=?,DATE=NOW(), NAME=? WHERE MAC=?');`

Best regards, 

Philipp

**Comment by charleneauger** [comment]
Hi @phil0135 

This bug has been fixed. The fix is available on the new version 2.8.1.

Best regards,
Charlene
