### ISSUE TITLE
Enterprise Linux 7 (with EPEL) x86_64 repositories are not update with latest version

### ISSUE THREAD

**Issue by gokuatkai** [OCSInventory-NG/OCSInventory-Server#178]
Hello,
`Enterprise Linux 7 (with EPEL) x86_64` repositories does not contain the latest versions of the packages.

**Comment by kapouik** [comment]
All rpm for the server are allready build. I'm currently writing the new documentation for the installation (many change with the last RPM) and wait the release of the agent to publish all.

RPM is comming :)

**Comment by gillesdubois** [comment]
RPM are here for quite some times now, i'm closing this issue.
