### ISSUE TITLE
All Computers replay in dynamic groups gives me: "You have an error in your SQL syntax"

### ISSUE THREAD

**Issue by wytchmaster** [OCSInventory-NG/OCSInventory-Server#180]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 9.0

### Server informations
Perl version : 5.24.1
Mysql / Mariadb / Percona version :  10.1.38

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.6

### Problem's description
When searching with various criteria and creating a dynamic group from the result, everything seems ok. Computers are added as expected. When entering the dynamic group afterwards and trying to recheck computers via "all computer (replay) I get:

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'softwares.BITSWIDTH = '64'' at line 1

The corresponding SQL-query is shown as follows:

> 1) => SELECT DISTINCT hardware.ID FROM hardware INNER JOIN softwares on hardware.id = softwares.hardware_id WHERE softwares.NAME LIKE '%vlc%' softwares.BITSWIDTH = '64'

I already deleted the group and recreated it, but the error stays the same. It used to work with older versions of OCS.

**Comment by wytchmaster** [comment]
Update: The computers are deleted from the group after accessing "All Computers (replay)" link in the dynamic group view. They were there before clicking the "All Computers (replay)" link.

**Comment by gillesdubois** [comment]
Hi,

Can you try to install a nightly setup ? 
The bug has been fixed in the master branch a month ago.

Regards,
Gilles Dubois.
