### ISSUE TITLE
DOWNLOAD_URI_FRAG in HTTPS

### ISSUE THREAD

**Issue by Dream91300** [OCSInventory-NG/OCSInventory-Server#181]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOs 7.6

### Server informations
Perl version : 5.16
Mariadb version :  10.1.36

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.6

### Problem's description
Hi,
I wan't to deploy some application with OCS, but I have an issu with the download only (inventory is Ok). My OCS server is only in HTTPS so I can't modify DOWNLOAD_URI_FRAG in HTTPS. How to make this?
Thank's

**Comment by gillesdubois** [comment]
Hi,

A feature has been requested on the reports repository.
It will be added in the next release.

Regards,
Gilles Dubois.
