### ISSUE TITLE
Fresh install

### ISSUE THREAD

**Issue by CedricReymond** [OCSInventory-NG/OCSInventory-Server#188]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
ubuntu 18.04
### Server informations
Perl version : latest
Mysql / Mariadb / Percona version :  
latest
tried both mariadb and Mysql

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : latest

### Problem's description
*Describe your problem here*
Bonjour,
J'ai fait plusieurs fois l'install sur un nouveau serveur.
Suivi la procédure. Aucune erreur dans les logs, j'arrive bien jusqu'a:
OK, Administration server installation finished 😉 
mais impossible d'appeler le la page ocsreport/install.php 
je n'arrive pas a aller plus loin.

**Comment by gillesdubois** [comment]
Bonjour,

Pensez a activer les configurations Apache par défaut celle-ci sont désactivée.

Gilles Dubois.
