### ISSUE TITLE
Download file is not Gzipped

### ISSUE THREAD

**Issue by lucasdiedrich** [OCSInventory-NG/OCSInventory-Server#19]
Hello,

Can you guys please check how the compression of the [tar file](https://github.com/OCSInventory-NG/OCSInventory-Server/archive/2.2.tar.gz). The name of the file contains **.tar.gz**, but it is not gzipped, so when i execute the command:

> tar -zxvf OCSNG_UNIX_SERVER-2.2.tar.gz

Return this:

> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now

**Comment by gillesdubois** [comment]
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/76
