### ISSUE TITLE
Issue with adding inventory on linux machines

### ISSUE THREAD

**Issue by killmasta93** [OCSInventory-NG/OCSInventory-Server#191]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 16.04

### Server informations
Perl version : This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi

Mysql / Mariadb / Percona version :  
mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X ] Manual installation

### OCS Inventory informations
Ocs server version : 2.6

### Problem's description
I was wondering if someone has had the same issue with the version 2.6 i install the agent with this

on version 2.5 works fine

 apt install ocsinventory-agent

then put the IP http

then inventory command with this

      ocsinventory-agent -t servers --password=PWD mypass -u inventory -f

on ubuntu 16 and 14 worked but on debian 9 and ubuntu 18 wont show on the inventory not sure why

           Mon Aug 26 15:50:11 2019;24196;114;prometheus- 2019-08-25-11-02-06;192.168.3.254;OCS- NG_unified_unix_agent_v2.0.5;inventory;no_session

**Comment by fbomj** [comment]
Hi,
Have you errors in ocsinventory-agent.log file? 2.0.5 agent version is too old and no more supported.
Update to latest version.
Regards

**Comment by killmasta93** [comment]
Thanks for the reply so i manually installed the 2.4.2 agent on linux, and it worked but is there a repository which has the 2.4.2 on ubuntu 18 and debian 9?

**Comment by gillesdubois** [comment]
> When I am trying to add a new layout from OCS Inventory an error is occurring as "Access Denied"

Hi @BhavyaSree1605, I dont understand why you put it there. In the case you have a problem please open an issue and don't comment on a closed one :)

Btw, layout permissions are not set by default, could you check your profiles and make sure ms_layout is checked ? 

Regards,
Gilles.
