### ISSUE TITLE
Enabling SSL/HTTPS

### ISSUE THREAD

**Issue by mriske** [OCSInventory-NG/OCSInventory-Server#196]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Fedora 30

### Server informations
Perl version : 
Mysql / **Mariadb** / Percona version :  10.3.17-MariaDB

### Server installation method ( Only one choice )
- [x] RPM Package
- [ ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.6

### Problem's description
Installed OCS via the RPM Package and used this tutorial: http://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server-with-rpm/
Now i want to enable SSL/HTTPS to be able to deploy Software through OCS, which requires SSL enabled.
I see in various tutorials that i need to have access to a file under 
**/etc/httpd/conf.d/z-ocsinventory-server.conf** or something similar

Problem: There is no such file anywhere on the server.
How can i secure the server OR can i deploy Software without using SSL/HHTPS at all?

**Comment by gillesdubois** [comment]
Hi,

RPM path are slightly different.
You can setup SSL on the Apache level if you want it to be easier.

Regards,
Gilles Dubois.
