### ISSUE TITLE
[BUG] 500 Internal Server Error and accountinfos;missing

### ISSUE THREAD

**Issue by AlroneRhyn** [OCSInventory-NG/OCSInventory-Server#197]
**OCS Inventory version**
Version : 2.5

**Describe the bug**
Error on client : [error] Cannot establish communication : 500 Internal Server Error
Error on server :  
```Wed Sep 18 16:19:11 2019;1371;321;NA;10.97.208.131;OCS-NG_unified_unix_agent_v2.4.2;system;gzip
Wed Sep 18 16:19:11 2019;1371;319;FR-PAN-596-2019-09-18-15-43-06;10.97.208.131;OCS-NG_unified_unix_agent_v2.4.2;session;found
Wed Sep 18 16:19:11 2019;1371;104;FR-PAN-596-2019-09-18-15-43-06;10.97.208.131;OCS-NG_unified_unix_agent_v2.4.2;inventory;incoming
Wed Sep 18 16:19:11 2019;1371;528;FR-PAN-596-2019-09-18-15-43-06;10.97.208.131;OCS-NG_unified_unix_agent_v2.4.2;accountinfos;missing
Wed Sep 18 16:19:11 2019;1371;515;FR-PAN-596-2019-09-18-15-43-06;10.97.208.131;OCS-NG_unified_unix_agent_v2.4.2;end;error
```

**Expected behavior**
Some Macosx Clients don't register into ocs.

I tried to pass this modification : https://github.com/OCSInventory-NG/OCSInventory-Server/issues/40 without success.

Do you need anything else ?

Thank you for your help

**Comment by target74** [comment]
Hello, maybe related, I had an issue with same error when injecting fusioninventory-esx xml after server upgrade.
Old ocs server version was 2.1 on perl 5.10 / Centos6.9 
New ocs server version is 2.6 on perl 5.16 / Oracle Linux 7.7

It seems that dynamic valorization of constant does not work as expected.

See following rows in Constants.pm:

my $checksum_max_value = &get_checksum();
use constant CHECKSUM_MAX_VALUE => $checksum_max_value;

if tested, $checksum_max_value has the correct calculated value, but constant is empty.
Maybe it's something related to perl version or perl compilation flag.

At the moment I applied this patch as workaround:

--- Constants.pm.orig   2020-03-26 13:55:05.229541758 +0100
+++ Constants.pm.new    2020-03-26 13:58:47.155986368 +0100
@@ -57,7 +57,15 @@
 use constant OPTION_TYPE_SYNC => 0;
 use constant OPTION_TYPE_ASYNC => 1;

-my $checksum_max_value = &get_checksum();
+my $checksum_max_value;
+BEGIN {
+  my $checksum;
+
+  for my $section (keys %DATA_MAP){
+    $checksum|=$DATA_MAP{$section}->{mask};
+  }
+  $checksum_max_value = $checksum;
+}
 use constant CHECKSUM_MAX_VALUE => $checksum_max_value;

 # To enable user to set how auto-duplicates works

**Comment by Tarbos** [comment]
@pchamo 2147483647 is the largest positive number in a 32 bit integer and that is the problem:
The ID in the software table is autoincrementing and reached the maximal possible number causing internal server error 500. We solved this by converting ID to bigint instead of int.

**Comment by pchamo** [comment]
I realized about that, thank you.

**Comment by charleneauger** [comment]
Hi,

Server 2.5 is no longer supported. Please reopen an issue if you still encounter this issue in recent release.

Regards,
Charlene
