### ISSUE TITLE
Physical mac address is not inventoried ?

### ISSUE THREAD

**Issue by lechardonneret** [OCSInventory-NG/OCSInventory-Server#199]
It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.

General informations
Operating system :
Ubuntu Linux x86_64

Server informations
Perl version : V 5.26.1
Mysql / Mariadb / Percona version :
Mysql v 5.7.25

Server installation method ( Only one choice )
 RPM Package
[x ] Install SH
 Manual installation
OCS Inventory informations
Ocs server version : 2.6

Problem's description

Hi;

In the duplicates section I have machines that have the same mac address, they have all inventoried the "Ras Async Adapter" and not the real mac address of the physical network card of the machine, the deployed agent has version 2.4.00 for windows.

**Comment by charleneauger** [comment]
Hi @lechardonneret 

Can you try with a new version of the server and Windows Agent ? A lot of fix has been committed since you created this issue, I would recommend you to update to the latest version available.

Best regards,
Charlene
