### ISSUE TITLE
Bad entry in the help menu

### ISSUE THREAD

**Issue by kapouik** [OCSInventory-NG/OCSInventory-Server#20]
There is a bad entry in the help menu : Old Forums.
The old forums is not anymore online and this entry must be removed. 

I find this references :
OCSInventory-ocsreports/config/main_menu.xml:      <menu-elem id="ms_forums">
OCSInventory-ocsreports/config/main_menu.xml:        <url>ms_forums</url>
OCSInventory-ocsreports/config/profiles/admin.xml:    <page>ms_forums</page>
OCSInventory-ocsreports/config/profiles/dde_teledeploy.xml:    <page>ms_forums</page>
OCSInventory-ocsreports/config/profiles/ladmin.xml:    <page>ms_forums</page>
OCSInventory-ocsreports/config/profiles/sadmin.xml:    <page>ms_forums</page>
OCSInventory-ocsreports/config/urls.xml:  <url key="ms_forums">

and of course, the file OCSInventory-ocsreports/plugins/main_sections/ms_help/ms_forums.php

**Comment by MyTheValentinus** [comment]
Done. https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/0e702df7ef5c02cfbba707ed740b1a7d49dcfdee
