### ISSUE TITLE
How to configure ocsinventory-injector.pl with SSL and cacert.pem?

### ISSUE THREAD

**Issue by Wilyton** [OCSInventory-NG/OCSInventory-Server#204]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Oracle Linux 7.7

### Server informations
Perl version : 5.16
Mysql / Mariadb / Percona version :  Mariadb 5.5.64

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [x] Manual installation

### OCS Inventory informations
Ocs server version : 2.6

### Problem's description
No problem at the moment, but I would like to know how to configure the ocsinventory-injector.pl script with SSL and the cacert.pem certificate to encrypt sending data from the slave server to the master server.

Congratulations to everyone on the OCS development team, the application has worked very well in the company where I work. The tutorial at https://wiki.ocsinventory-ng.org/ was of great value for the implementation of the application.

Congratulations

**Comment by gillesdubois** [comment]
Hi @Wilyton ,

You can use the following documentation.
https://wiki.ocsinventory-ng.org/08.Multi-site-network-architecture/Synchronisation-between-OCS-server-master-slaves/#synchronsation-of-one-inventory-using-https

Regards,
Gilles Dubois.
