### ISSUE TITLE
Local import

### ISSUE THREAD

**Issue by bajlek** [OCSInventory-NG/OCSInventory-Server#205]
Hello I have strange behaviour of OCS server. I use it a long time without any problem, all client computers is conntected to the intranet and sending prologues to OCS inventory server. Yesterday I want to import one computer that is not connected to intranet. So I install OCS Agent (took exe from configuration from OCS Inventory server). I change ini file to run localy and restart service, after 5-6 minutes I have OCS file with size about 50kB. I put this OCS file to USB flash and try to import it from my computer that have access to ocsinventory server. 

I tried to import it from web UI and also from perl script from Ubuntu server. Everytime I have succesfull information about import.

Now the strange thing...

If I open "All computers" there is NO information about local imported one. 
![image](https://user-images.githubusercontent.com/27892518/70228538-c9e2d800-1754-11ea-88b9-cafe99eb069a.png)

But if I open Inventory > Search with various criteria I can FOUND this local imported computer. 
![image](https://user-images.githubusercontent.com/27892518/70228438-a7e95580-1754-11ea-8a39-47c14f00048a.png)

What the heck? :-) What am I doing wrong?

**Comment by gillesdubois** [comment]
Hi,

This bug has been resolved with the latest version.
Please, see our nightly build to fix the problems : 
http://download.ocsinventory-ng.org/nightly/

Regards,
Gilles Dubois.

**Comment by bajlek** [comment]
Tested and it seems that it worked! Thanks!
