### ISSUE TITLE
[QUESTION] Manage 200k of machines with OCS

### ISSUE THREAD

**Issue by wiltonsr** [OCSInventory-NG/OCSInventory-Server#206]
Hello,

What is the best/recommended way of create an OCS Inventory Server Infraestructure to manage 200k of machines that report 3 times of a day?

The [wiki says](https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server/) that 2 servers can inventory 10k of machines.

So in my case I will need 40 servers? How I should configure the database of this servers? Use a Multi Master replication with Galera Cluster?

**Comment by gillesdubois** [comment]
Hi @wiltonsr ,

Managing 200k of assets is possible and is a common case for our product.

The wiki is a bit misleading on this part.
For 200k assets I recommend to split your OCS Instance like this scheme: 
![image](https://user-images.githubusercontent.com/9396603/71575851-c4c43f00-2aee-11ea-90fd-53e4106ccfa0.png)

The database and the communication server will have the higher load and will to have better specs than the others component. (like 6-8 vCPU / 64G of ram for the database AND the communication server)

You can also install more than one communication server to split the load. 

A multi-master cluster like Galera won't help much, it will improve the performences but one standalone server should be enough.

Also, I recommend you to check our professional offer. The community edition doesn't have any official support or any guarantee which is (in my opinion) a bit unsecure with your assets number.

[Our professional offer](https://ocsinventory-ng.org/?page_id=140&lang=en)
[Contact US](https://ocsinventory-ng.org/?page_id=126&lang=en)

Regards,
Gilles Dubois.
