### ISSUE TITLE
[BUG] Missing mysql ssl support for Rest API.

### ISSUE THREAD

**Issue by cgregoirovh** [OCSInventory-NG/OCSInventory-Server#208]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
Debian Stretch (9)

### Server informations
Mariadb with ssl support

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X] Manual installation

### OCS Inventory informations
Ocs server version : 
2.6 nightly 08/01/2020

### Problem's description
After testing the latest ocs version with mysql ssl support, it appears that the mysql ssl support is missing on the rest api part.

Please see the PR to add it.

Thanks

**Comment by charleneauger** [comment]
Hi @cgregoirovh ,

Thankx for your report ! Your PR has been merged :)

Best regards,
Charlene Auger
