### ISSUE TITLE
Ldap casse le menu et les droits de mon compte local super admin

### ISSUE THREAD

**Issue by qforgeot** [OCSInventory-NG/OCSInventory-Server#21]
Bonjour, 
J'ai un problème sur la version 2.2.1.
J'ai effectué une mise à jour depuis la version 2.1.2 qui possédait déjà la config ldap à la fois dans l'interface de configuration et dans les fichiers auth.php et identity.php

Lors de la mise à jour, j'ai du remettre la ligne $list_methode=array(0=>"ldap.php",1=>"local.php"); dans les fichiers auth et idendity (comme indiqué dans le wiki).

Lorsque je me logue avec un user du ldap, pas de problèmes, par contre avec mon user local admin, mon profil est cassé, je n'ai plus de droits pour modifier, créér un user, je n'ai plus accès au plugins, j'avais caché les warning du GUI etc...
 En plus, le menu a un comportement bizarre :+1: 
![erreur ocs](https://cloud.githubusercontent.com/assets/20244552/16618225/85844804-4388-11e6-8797-b239c16d83f6.jpg)

Dites moi quoi envoyer pour faire l'analyse du problème.

**Comment by MyTheValentinus** [comment]
Bonjour @qforgeot 
Avez-vous essayé de mettre à jour les profils? 

![17-45-13](https://cloud.githubusercontent.com/assets/6104498/16624390/b5e51adc-43a1-11e6-9528-309ab78a60af.png)

Bonne journée

**Comment by qforgeot** [comment]
Bonjour,
Merci pour votre réponse,
Voilà ce que j'ai, et quand je valide, il ne se passe rien [image: Images
intégrées 1]

Bien cordialement / Best regards,

Quentin Forgeot

Ennov / Service Hébergement / Hosting Department
[image: Ennov Logo]

Email qforgeot@ennov.com

Office +33 (0)5 33 00 31 82

Visit us http://www.ennov.com

2016-07-06 17:47 GMT+02:00 Valentin Deville <notifications@github.com>:

**Comment by MyTheValentinus** [comment]
Hello,
Up ? Aucune nouvelle ?

**Comment by gillesdubois** [comment]
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/150
