### ISSUE TITLE
cp: cannot stat 'ocsreports/*': No such file or directory

### ISSUE THREAD

**Issue by koppert** [OCSInventory-NG/OCSInventory-Server#22]
I tried to install , but I got the error: 

+----------------------------------------------------------+
|      Installing files for Administration server...       |
+----------------------------------------------------------+

Creating PHP directory /usr/share/ocsinventory-reports/ocsreports.
Copying PHP files to /usr/share/ocsinventory-reports/ocsreports.
*** ERROR: Unable to copy files in /usr/share/ocsinventory-reports/ocsreports, please look at error in /home/alclogti/download/OCSInventory-Server/ocs_server_setup.log and fix !

**ocs_server_setup.log**

cp: cannot stat 'ocsreports/*': No such file or directory

setup.sh:1445

I searched the ocsreports within the installation directory and I did not find.

Thanks!

**Comment by MyTheValentinus** [comment]
Hello @koppert,
Please use release to install OCS. You can find releases on this page https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases

Thanks for using OCS Inventory
Have nice day

**Comment by koppert** [comment]
Thanks!

**Comment by avaloncio** [comment]
============================================================
Installing Administration server
============================================================
Checking for Administration Server directories...
Using directory /usr/share/ocsinventory-reports for static files
Using /var/lib/ocsinventory-reports as writable/cache directory
Checking for DBI PERL module
PERL module DBI is available
Checking for DBD::mysql PERL module
PERL module DBD::mysql is available
Checking for XML::Simple PERL module
PERL module XML::Simple is available
Checking for Net::IP PERL module
PERL module Net::IP is available
Creating PHP directory /usr/share/ocsinventory-reports/ocsreports
Copying PHP files to /usr/share/ocsinventory-reports/ocsreports
**cp: cannot stat 'ocsreports/*': No such file or directory**

**Comment by Dirk23** [comment]
Hi. I have exact the same error when updating from 2.5 to 2.6
What can i do?

**Comment by Cesarius1970** [comment]
Try with :

(on debian/ubuntu)

sudo a2enconf ocsinventory-reports

sudo a2enconf z-ocsinventory-server

sudo chown www-data:www-data -R /var/lib/ocsinventory-reports

sudo systemctl restart apache2

Saludos,

César Vergara Buenaventura
Consultor Técnico TIC
RPC *+51.982096889*

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
16/10/19
09:46:27

**Comment by Dirk23** [comment]
Sorry, but nothing of this was successful.

![ocs](https://user-images.githubusercontent.com/4200682/66998162-09396480-f0d4-11e9-93f2-1d800f902a46.png)

**Comment by Cesarius1970** [comment]
Glad to read it!

Saludos,

César Vergara Buenaventura
Consultor Técnico TIC
RPC *+51.982096889*

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
17/10/19
08:34:07

**Comment by Mega2112** [comment]
> César Vergara Buenaventura Consultor Técnico TIC RPC *+51.982096889*

Cesar, ¿Como te puedo contactar para hablar sobre algo referente a OCS Inventory (soy de Mexico
Saludos
Manuel H
