### ISSUE TITLE
Rest API Problem with a List X computers details route

### ISSUE THREAD

**Issue by aacker53640** [OCSInventory-NG/OCSInventory-Server#221]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 9.0

### Server informations
Perl version : 5.24.1
Mysql / Mariadb / Percona version :  10.1.44-MariaDB

### Server installation method ( Only one choice )
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.5

### Problem's description
I got a problem when i try a route : 
http://myocsserver/ocsapi/v1/computers?start={startoffset}&limit={limitoffset}
I'm using it like this : https://website/ocsapi/v1/computers?start=0&limit=50
It says "We're sorry, something went wrong", when i open my error.log in apache2 i got this : 

DBD::mysql::db selectall_arrayref failed: Table 'ocsweb.service' doesn't exist at /usr/local/share/perl/5.24.1/Api/Ocsinventory/Restapi/ApiCommon.pm line 102.
[2020-03-27 14:19:14.46465] [6022] [error] DBD::mysql::db selectall_arrayref failed: Table 'ocsweb.service' doesn't exist at /usr/local/share/perl/5.24.1/Api/Ocsinventory/Restapi/ApiCommon.pm line 102

Can someone explain me what i did wrong to get this error ? Maybe a wrong install or how can i fix it ?

**Comment by whasf** [comment]
It says right in the log file snip you provided, you're missing the "service" table in your database

**Comment by aacker53640** [comment]
Hi, 
Yes i know, but how can i get this database ? I need a sql script from OCS and i don't know where to find

**Comment by aacker53640** [comment]
After some research and reading the sql file of ocs, there is no service table, so there is a problem with the api query i think, can someone help me with that ?

**Comment by gillesdubois** [comment]
Hi,

Service is an OCS Inventory plugins.
Please check plugins.ocsinventory-ng.org

If you have this error it mean that the plugin has been installed in the past and has been removed incorrectly.

Regards,
Gilles.
