### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Arkadietz** [OCSInventory-NG/OCSInventory-Server#222]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : RedHat

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  
MariaDB - 5.5.64
Perl - 5.16.3
### Server installation method ( Only one choice )
- [x ] RPM Package
- [ ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.7

### Problem's description
Hello,

Most probably this is not a issue but general feature questions
I am interesting that your product is capable to support the following:
Here is an example: You have some Linux host with running some RedHat on it.
Also you have databases and different application.
Does your product will show or there is an option to show
- who is responsible as team for the Linux (RedHat), who is responsible for application and for database (so you should see some queue (a group and the person inside)).

P.S Where I can find a screenshots on your latest 2.7 release?

**Comment by gillesdubois** [comment]
Hi @Arkadietz ,

Your idea is really nice but OCS is not intended to be a assets manager but only an assets inventory and deployment tool. What you want (if i understand right) is more related to a CMDB software that coulld connect and get data from OCS.

Unfortunatly, we don't offer any screenshot, you can use our docker images to have a quick installation.

Regards,
Gilles Dubois.
