### ISSUE TITLE
Duplicates only one host?

### ISSUE THREAD

**Issue by killmasta93** [OCSInventory-NG/OCSInventory-Server#224]
### General informations
Operating system : ubuntu 16.04

### OCS Inventory informations
Ocs server version :  2.5

### Problem's description
Hi,

I was wondering if someone else has had this issue before, Very odd just have only 1 computer which keeps showing duplicate

and the client is running 2.4 we tried also 2.3

https://imgur.com/c91OpmO.png

Thank you

**Comment by gillesdubois** [comment]
Hi,

Please update to the latest releases, we had reconciliation issues with old agent.
You will also have to update the server alongside.

Regards,
Gilles Dubois.

**Comment by killmasta93** [comment]
thank you that did the trick
