### ISSUE TITLE
Setup error checking MySQL version

### ISSUE THREAD

**Issue by FrancoisRibiere** [OCSInventory-NG/OCSInventory-Server#225]
### General informations
Operating system : 
CentOS 8.1
### Server informations
Perl version : 
Mysql version :  8.0.17
### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.1 
commit: 0328730

### Problem's description
During the manual setup from git sources, setup.sh on lines 152 and 153 tries to determine which version of MySQL is installed.
But, the evaluation result of "mysql -V" does not correspond anymore. It cut spaces on 6th element, while now, the 4th is needed (4th returned 8.0.17, the 6th returns Linux).

**Comment by kapouik** [comment]
MySQL 8 is not supported by OCS Inventory. Please switch on MariaDB.
