### ISSUE TITLE
Unix Server : TeleDeployment - missing info file

### ISSUE THREAD

**Issue by FerreCh** [OCSInventory-NG/OCSInventory-Server#229]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 18.04 Desktop LTS 

### Server informations
Perl version : 5.26.1
Mariadb version : 10.1.44 

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.7
Ocs clients version : 2.6.1

### Problem's description

As I try to use the deployment feature from a Unix OCS Server to an Unix agent, the client receives the package but reject it because he doesn't find the "info file". It seems that OCS fails to create/send the "info file" of the package.

I use self-signed certificate, the certificate is shared between the server and the client.

Server certificate location: /etc/ssl/certs/ocsng.pem

In "/etc/apache2/conf-enabled/z-ocsinventory-server.conf", the SSL Mode is enabled and set on SSL_MODE_PREFERRED and the key and cert paths are correct.

Client certificate location : /var/lib/ocsinventory-agent/https:__<server_hostname>:443_ocsinventory/cacert.pem

The CN on the certificate is the hostname of the Machine where the OCS Server is.

Logs on client Side :

/var/log/ocsinventory-agent.log :

[Wed May  6 18:29:32 2020][debug] =BEGIN=SERVER RET======
[Wed May  6 18:29:32 2020][debug] $VAR1 = '<?xml version=\'1.0\' encoding=\'UTF-8\'?>
<REPLY>
  <RESPONSE>NO_ACCOUNT_UPDATE</RESPONSE>
</REPLY>
';
[debug] Calling handlers : `end_handler'
[debug] [download] Calling download_end_handler
[info] [download] Beginning work. I am 4346.
[debug] [download] No info file found for 1588777867!!
[info] [download] Cleaning 1588777867 package.
[info] [download] No more package to download.
[debug] [download] End of work...

Logs on server side :

/var/log/ocsinventory-server/activity.log :

;2201;2001;client-ocs-2020-05-06-09-50-08;<Client_IP_Adress>;OCS-NG_unified_unix_agent_v2.6.1;download;1588770988(ERR_DOWNLOAD_INFO)

/var/log/apache2/error.log :

[ssl:warn] [pid 4306] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name

Thanks in advance for anyone who can help me.

**Comment by gillesdubois** [comment]
Hi @FerreCh ,

``` 
In "/etc/apache2/conf-enabled/z-ocsinventory-server.conf", the SSL Mode is enabled and set on SSL_MODE_PREFERRED and the key and cert paths are correct.

Client certificate location : /var/lib/ocsinventory-agent/https:__<server_hostname>:443_ocsinventory/cacert.pem
```

It seem there is a mis-understanding here, SSL_MODE in z-ocsinventiry-server.conf is related to SQL over SSL connection and is not related to HTTPS connection (needed to deploy a package)

To have a working deployment you need : 
- To enable deployment in the web console (config -> deployment)
- Have a SSL certificate with CN set as the name of the server
- Enable SSL in apache and use the certificate created above 
- Make sure SSL is properly activated on apache
- Put the certificate on the agent 
- Set SSL=1 (win agent only)

Regards,
Gilles Dubois.
