### ISSUE TITLE
Install package for Debian?

### ISSUE THREAD

**Issue by nmaas87** [OCSInventory-NG/OCSInventory-Server#231]
### General informations
Operating system :  Debian Buster / 10.4

### Server informations
Perl version : 5.28.1
Mariadb  version :  10.3.22

### Server installation method ( Only one choice )
- [x] RPM Package
- [ ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version :  2.5

### Problem's description
We had an old Debian installation we want to upgrade from Debian 8 to Debian 10. However, this always fails. The main information we can find, is that you should install OCS on Debian 10 via the install_script. Searching the Debian package database, we find that only OCS 2.5 is available, which is quite old. Are there any plans to update the Debian package or are there scripts available, so that one can build the .deb package for easier installation and maintenance for themselfes?

Best regards
Nico

**Comment by gillesdubois** [comment]
Hi @nmaas87 ,

A debian package is on the way for the OCS Inventory Agent.
If you really want to setup the server from a repository we will recommend to use a redhat based distro so you have access to our rpm repository.

Regards,
Gilles Dubois.
