### ISSUE TITLE
Intégrate Apache Guacamole Remote Desktop

### ISSUE THREAD

**Issue by lexcorp** [OCSInventory-NG/OCSInventory-Server#237]
Intégrate Apache Guacamole Remote Desktop with Ocs Inventory for audit tasks, validation of equipment specifications, support, updates, etc.

https://guacamole.apache.org/

Apache Guacamole is a clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH.

We call it clientless because no plugins or client software are required.

Thanks to HTML5, once Guacamole is installed on a server, all you need to access your desktops is a web browser.

Apache Guacamole is and will always be free and open source software. It is licensed under the Apache License, Version 2.0, and is actively maintained by a community of developers that use Guacamole to access their own development environments.

Apache Guacamole is built on its own stack of core APIs which are thoroughly documented, including basic tutorials and conceptual overviews in the online manual. These APIs allow Guacamole to be tightly integrated into other applications, whether they be open source or proprietary.

**Comment by kapouik** [comment]
Please don't post your issue on all repositories.

I close this one.
