### ISSUE TITLE
Not a HASH reference at /usr/local/share/perl/5.28.1/Apache/Ocsinventory/Server/Capacities/Snmp/Inventory.pm line 111

### ISSUE THREAD

**Issue by guillaumeesposito** [OCSInventory-NG/OCSInventory-Server#238]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 10

### Server informations
Perl version : 5.28.1
Mysql / Mariadb / Percona version :  MariaDB 10.3.22

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.8 (commit 14d6807)

### Problem's description
Hello,

The SNMP Scan is working but when the agent post the XML on the server, it triggers a Internal Server Error (500) because of this line /usr/local/share/perl/5.28.1/Apache/Ocsinventory/Server/Capacities/Snmp/Inventory.pm line 111.

After debugging the server code, I found that this code : 
```
#Getting data for the several snmp devices that we have in the xml
  foreach my $snmp_key (keys %{$snmp_devices}){
    my @columns;
    my @bind_num;
    my @arguments;
    my @update;
    my $i = 1;

    foreach my $snmp_infos (keys %{$snmp_devices->{$snmp_key}}) {
      push @columns, $snmp_infos;
      push @bind_num, '?';
      push @arguments, $snmp_devices->{$snmp_key}->{$snmp_infos};
      push @update, $snmp_infos." = ?";
    }
```
is not going through all founded snmp_devices. The `$snmp_key` only gets `DEVICE` as value and there is only one iteration for the first loop.

Thank you for your help.
Regards,
Guillaume

**Comment by charleneauger** [comment]
Hi @guillaumeesposito ,

I tested SNMP Scan but I haven't this error on my server apache log. What is your Unix Agent version ?

Regards,
Charlene

**Comment by guillaumeesposito** [comment]
Hello @charleneauger ,

I used the latest release, version 2.6.1

Regards,
Guillaume

**Comment by charleneauger** [comment]
Hi @guillaumeesposito ,

Ok, I think you encounter this error because the SNMP has been reworked on the master branch of the Unix Agent, thus stable release doesn't include this rework yet.
Since your Agent does not contain this new implementation, it doesn't send valid data to the server.

Best regards,
Charlene Auger

**Comment by guillaumeesposito** [comment]
Hi @charleneauger ,

Thank you for your quick reply and your time. I will test the Unix Agent with the version from the master branch then.

Regards,
Guillaume
