### ISSUE TITLE
IPDiscover : persistance des données

### ISSUE THREAD

**Issue by tsmr** [OCSInventory-NG/OCSInventory-Server#24]
Version OCS : 2.2.1

Actuellement dans IPdiscover, je me retrouve avec des données obsolètes (exemple : découverte réseau datant de Juin)
![image](https://cloud.githubusercontent.com/assets/13178158/18161693/54076b08-7033-11e6-8c0f-4e01d3c93d15.png)

Il serait intéressant de pouvoir définir un paramètre de suppression automatique des enregistrements IPDiscover datant de plus de XX jours

**Comment by gillesdubois** [comment]
Bonjour,

Il es vrai que les données ipdiscover peuvent rapidement se polluer avec des données obsolète.
C'est une très bonne idée, je soumets l'idée et fait un retour des que possible.

Cordialement,
Gilles Dubois.

**Comment by mylanndupuy72** [comment]
Bonjour,

Je déterre ce post mais est-ce que vous avez des nouvelles car c'est vrai que sur un parc informatique c'est assez embêtant. Je suis sur la version 2.3.

Cordialement. 
Mylann

**Comment by mylanndupuy72** [comment]
Bonjour,
Avez-vous un retour sur ce sujet ?

Cordialement.
Mylann.

**Comment by gillesdubois** [comment]
Bonjour,

Cette feature est désormais disponible.

Cordialement,
Gilles.
