### ISSUE TITLE
[FEATURE] Rest API for CVE

### ISSUE THREAD

**Issue by dust63** [OCSInventory-NG/OCSInventory-Server#247]
Is it possible to have a route to list all CVE available on OCS. It should be nice also to know wich hardware IDs are linked to each cve ?

**Comment by charleneauger** [comment]
Hi @dust63 

We add your feature on our roadmap. We will get back to you when the feature is implemented.

Best regards,
Charlene

**Comment by charleneauger** [comment]
Hi @dust63 ,

The route to list CVE has been added with PR #292 

Best regards,
Charlene Auger
