### ISSUE TITLE
CVE Reporting : No data available in Table

### ISSUE THREAD

**Issue by lble44** [OCSInventory-NG/OCSInventory-Server#251]
Hello,

Here is my system information : 

### General informations
![image](https://user-images.githubusercontent.com/69039920/91724110-1a307e80-eb9d-11ea-89c9-37c348601e62.png)

### Server installation method ( Only one choice )
- [ ] Install SH

OCS Server configuration for CVE Search management :
![image](https://user-images.githubusercontent.com/69039920/91724651-e86be780-eb9d-11ea-92df-def7273bb606.png)

### Problem's description
I have a problem on CVE Reporting functionality. I launched the 08/11 the cron_cve.php and some files were downloaded as you can see below in "Information" --> "CVE History" :
![image](https://user-images.githubusercontent.com/69039920/91724885-3bde3580-eb9e-11ea-89c2-c899bb4428c5.png)

But now when I launch again the script "cron_cve.php", here is the result :
![image](https://user-images.githubusercontent.com/69039920/91725117-9081b080-eb9e-11ea-8aa7-d93b28ea5df8.png)

And most importantly, I have "No data available in table" in "Inventory" --> "CVE Reporting" as you can see below :
![image](https://user-images.githubusercontent.com/69039920/91725343-e22a3b00-eb9e-11ea-9436-1a749591de52.png)

Thank's in advance to have a look on this issue.

Regards.

**Comment by gillesdubois** [comment]
Hi,

Here is a list of what could be the issue.

1/ CVE Url :
You are using the default and public CVE Search server which is NOT recommended at all. Please setup your own server to have more control on which query is sent and how the server is responding. A stable docker image exist if you don't want to bother with installing a CVE Search Server.

2/ CVE Matching : 
Please take a look at this : http://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/CVE-Search-match-regex/

Regards,
Gilles.
