### ISSUE TITLE
OCS Agent 2.6 higher Load on Webserver

### ISSUE THREAD

**Issue by ChrisWelcome** [OCSInventory-NG/OCSInventory-Server#253]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 64 Bit 

### OCS Inventory information
Windows agent version : 2.6

### Problem's description
*Describe your problem here*
After we updated the agents to 2.6 the load on the OCS Inventory Webserver increased 3 times.

**Comment by charleneauger** [comment]
Hi,

A lot of fixes/improvements have been made on the management of duplicates since version 2.6.
Please re-open an issue if you still encounter the problem with recent server versions.

Regards,
Charlene
