### ISSUE TITLE
Documentation not clear on LDAP

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/OCSInventory-Server#254]
### General informations
Operating system :  Centos7

### Server informations
Perl version :  PHP 7.2.33
Mysql / Mariadb / Percona version :  MariaDB-server-10.3.24

### Server installation method ( Only one choice )
- [ x] RPM Package
- [ ] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.7

### Problem's description
I'd like to use LDAP and reading the documentation I'm not sure if I need to edit the PHP or not as the opening statement says no php needs to be touched whereas the second paragraph says you must edit a php file. BTW is there any how-to guide I can reference?

```
Since nightly of 25th june of 2020 and the 2.8 version of OCS Inventory we don't need to edit the PHP files anymore.

After configuring the LDAP connection from web console, you will need to edit the var.php file located in /usr/share/ocsinventory-reports/ocsreports folder (by default).
```
https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Synchronization-between-OCS-and-LDAP/

**Comment by gillesdubois** [comment]
Hi,

The only edit needed is the value in the var.php file.
No other file need to be touched.

This statement is indeed confusing, i'm fixing it soon.

Regards,
Gilles Dubois.
