### ISSUE TITLE
SNMP Scan issue

### ISSUE THREAD

**Issue by guillaumeesposito** [OCSInventory-NG/OCSInventory-Server#257]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 10

### Server informations
Perl version : 5.28.1
Mysql / Mariadb / Percona version :  MariaDB 10.3.22

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.8.0 (latest release)
Ocs Unix Agent version : 2.8.0 (latest release)

### Problem's description
Hello,

As a follow up to this issue #238 I have updated both the OCS Server and Unix Agent to the latest release 2.8.0 (thank you for that release by the way). I still did not manage to make the SNMP Scan feature works, or maybe I did not understand well how it should work.

What I would like to do : 
I have some equipments (printers, firewalls, switches...) that I would like to be recognize as computers by OCS Server (so they appear in section "All computers"). Then OCS would get the list of installed softwares on it. The goal is then to use the CVE Reporting feature to alert on eventual vulnerabilities for those softwares.

What I have configured:
- I have a machine in the same network that my equipment. It has `IPDISCOVER` enable on the network and `SNMP_SWITCH` functionality on (with the `SNMP_NETWORK` configured to scan the /24 network, containing the equipment);
- In the section `Configuration > General configuration > SNMP`, I have `SNMP` on and I have upload MIBs files corresponding to my equipment in the directory `SNMP_MIB_DIRECTORY`;
- I have configured properly the SNMP Communities used by my equipment into `Manage > Network scan > Manage SNMP communities`;
- In the section `Configuration > SNMP configuration` I have created a type with the OID and the corresponding string value. I also created Labels that I want to fetch and used the MIBs files to make the match between Label and OID (with Reconciliation set to Yes).

What I have as results:
I have one equipment that appear in section `Inventory > SNMP` with the type and labels I created.

What I don't understand:
What is the difference between `Ocsinventory::Agent::Modules::Snmp` and `Ocsinventory::Agent::Modules::SnmpScan` module ? I see you commented this [line](https://github.com/OCSInventory-NG/UnixAgent/blob/d3e72da77f0073624c7cd5c1a2663bb721211f7f/etc/ocsinventory-agent/modules.conf#L7) on the UnixAgent. When I use the `SnmpScan` module, I see that after the agent has scanned the network, it sends an XML with a lot of information (it is exactly these information that I want to get) and the XML is formed like : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <COMMON>
         [...] Usefull information [...]
      </COMMON>
      [...]
    </DEVICE>
    <DEVICE>
      [...]
    </DEVICE>
  </CONTENT>
  <DEVICEID>[someid]</DEVICEID>
  <QUERY>SNMP</QUERY>
</REQUEST>
```
Ater the `COMMON` section I also have a lot of information like the list of CPUs, networks, installed softwares, etc...
When I comment the line and only use `Snmp` module the agent gets much less information (it gets the labels I created in the configuration) and sends to the server an XML like : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <[name of the type I created in the configuration]>
      <[LABEL1]>[...]</[LABEL1]>  # Label created in the configuration
      <[LABEL2]>[...]</[LABEL2]>
    </[SAME]>
  </CONTENT>
  <DEVICEID>[someid]</DEVICEID>
  <QUERY>SNMP</QUERY>
</REQUEST>
```

The problem is when I use `SnmpScan` and when the agent sends its XML with all the information I have a "Communication error with the server (error 500)". The error on the server side is `Not a HASH reference at /usr/local/share/perl/5.28.1/Apache/Ocsinventory/Server/Capacities/Snmp/Inventory.pm line 111`.

Don't hesitate to tell me if you need more information.
Thank you very much for your time and help.

Regards,
Guillaume Esposito

**Comment by groulot** [comment]
I have exactly the same problem.
Operating system :  Ubuntu 18.04
Perl version : 5.26.1
Server: 2.8
Unix agent version : 2.8

SNMP XML report sent by the Agent to the server:
```
<REQUEST>
  <CONTENT>
    <snmp_rfc1213>
      <Contact>&quot;John Doe&quot;</Contact>
      <Description>Linux box 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64</Description>
      <Location>&quot;Server room&quot;</Location>
      <Name>my-server</Name>
    </snmp_rfc1213>
  </CONTENT>
  <DEVICEID>ocs-box-2020-10-02-11-14-34</DEVICEID>
  <QUERY>SNMP</QUERY>
</REQUEST>
```

**Comment by guillaumeesposito** [comment]
Hello guys,

Any news about this issue ? 🙂 

Thanks
Guillaume Esposito

**Comment by gillesdubois** [comment]
Hi,

Could you enabled DBI_PRINT_ERROR in the z-ocsinventory-server.conf file ?
It will give me more informations on the problem itself.

Also, please remind that SNMP engine will fail if your model use reserved mysql keywords.

Regards,
Gilles.

**Comment by groulot** [comment]
Hello, I enabled DBI_PRINT_ERROR. 

Here are my results.

The posted SNMP report:
```
[debug] sending: <?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <snmp_rfc1213>
      <Contact>&quot;My company&quot;</Contact>
      <Description>Linux OXIDIZED 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64</Description>
      <Location>&quot;Cloud&quot;</Location>
      <Name></Name>
    </snmp_rfc1213>
    <snmp_rfc1213>
      <Contact>&quot;My company&quot;</Contact>
      <Description>Linux ocs-test 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64</Description>
      <Location>&quot;Cloud&quot;</Location>
      <Name></Name>
    </snmp_rfc1213>
    <snmp_rfc1213>
      <Contact>&quot;My company&quot;</Contact>
      <Description>Linux ocs-test 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64</Description>
      <Location>&quot;Cloud&quot;</Location>
      <Name></Name>
    </snmp_rfc1213>
  </CONTENT>
  <DEVICEID>ocs-test-2020-10-02-11-14-34</DEVICEID>
  <QUERY>SNMP</QUERY>
</REQUEST>

[error] Cannot establish communication : 500 Internal Server Error
```

Here is the Apache error log line:
```
[Thu Nov 12 15:08:37.981714 2020] [perl:error] [pid 86122] [client 10.0.3.47:58122] Not a HASH reference at /usr/local/share/perl/5.26.1/Apache/Ocsinventory/Server/Capacities/Snmp/Inventory.pm line 111.\n
```

And the OCS Log:
```
Thu Nov 12 16:15:20 2020;88462;1004;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;ipdiscover;incoming
Thu Nov 12 16:15:20 2020;88462;100;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;prolog;accepted
Thu Nov 12 16:15:20 2020;88462;311;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;session;started
Thu Nov 12 16:15:29 2020;88463;1004;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;ipdiscover;incoming
Thu Nov 12 16:15:29 2020;88463;100;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;prolog;accepted
Thu Nov 12 16:15:29 2020;88463;311;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;session;started
Thu Nov 12 16:17:34 2020;88464;319;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;session;found
Thu Nov 12 16:17:34 2020;88464;104;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;inventory;incoming
Thu Nov 12 16:17:35 2020;88464;113;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;inventory;u:networks
Thu Nov 12 16:17:35 2020;88464;113;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;inventory;u:repository
Thu Nov 12 16:17:35 2020;88464;113;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;inventory;u:videos
Thu Nov 12 16:17:35 2020;88464;113;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;inventory;u:cpus
Thu Nov 12 16:17:35 2020;88464;113;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;inventory;u:storages
Thu Nov 12 16:17:35 2020;88464;320;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;session;end
Thu Nov 12 16:17:35 2020;88464;101;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;inventory;transmitted
Thu Nov 12 16:24:23 2020;88469;100;ocs-test-2020-10-02-11-14-34;10.0.3.47;OCS-NG_unified_unix_agent_v2.8.0;snmp;inventory incoming
```
