### ISSUE TITLE
[FEATURE] Add dicover agent hardware id on ipdiscover/{network} route

### ISSUE THREAD

**Issue by dust63** [OCSInventory-NG/OCSInventory-Server#258]
Actually in the ipdiscover/{network} route you can't know the agent that discover the network.
Can you add the hardware id of the agent on the messages return by the rest api please.

**Comment by dust63** [comment]
Sorry it's clone

**Comment by gillesdubois** [comment]
Hi @dust63 

Since its a clone im closing it :) 

Gilles.
