### ISSUE TITLE
Web Service does not return machines that checked in recently

### ISSUE THREAD

**Issue by jcwhit1** [OCSInventory-NG/OCSInventory-Server#26]
We are accessing the web service as described here:
http://wiki.ocsinventory-ng.org/index.php?title=Developers:Web_services

The service works OK and returns data, but it appears to only return machines that have NOT been seen within the last 3 days.  In other words, if a machine has contacted the server recently, then it does not come back in the query get_computers_v1.

**Comment by MyTheValentinus** [comment]
Hello @jcwhit1 
I have tested and i recognize this issue as a bug.
I investigate

**Comment by MyTheValentinus** [comment]
Hello @jcwhit1 
The bug was fixed.
Thanks

**Comment by ceeram** [comment]
There is 2 problems here:
- $begin should not have been removed, this is set by OFFSET in soap requests.
- IMO ordering should be done on something that does not change, for instance the ID, to assure you will get all computers with multiple requests using offsets. If the ordering is on a dynamic field, a computer can be missed when trying to retrieve them all, when it has been updated between 2 requests.
I will make a PR to at least add back $being, as there currently is no way to use OFFSET.
I would prefer on changing the ORDER as well to default to ORDER BY id ASC, so first 100 results will always return the same 100 computers. Perhaps adding in an option for custom sorting could be added as well, if users need custom/different sorting.

**Comment by jcwhit1** [comment]
Regarding the original bug, I believe it may have been due to limiting to 100 results, which we did not realize was a setting.  So there may not have been a bug at all, but as this thread has gone on, it may be helpful to set an order as you say to always return the same ones under a limit.  Thanks.

**Comment by ceeram** [comment]
PR including fix for OFFSET and adding additional custom sort options here: #39
