### ISSUE TITLE
Can't install all plugins on 2.8

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/OCSInventory-Server#261]
### General information
Operating system :  Centos 7.8
Perl version : v5.16.3
Mysql / Mariadb / Percona version :  MariaDB-server-10.3.24-1.el7.centos.x86_64

### OCS Inventory informations
Ocs server version : 2.8

### Problem's description
I have the bitlocker plugin active but as soon as I copy another plugin like the chromeextensions plugin and extract it to /usr/share/ocsinventory-reports/ocsreports/extensions I can't install any further plugins. The Plugin Manager page stops showing anything below "Extension Install".

Everything underneath "Extension Install" is removed until I delete the newly extracted plugin's directory:
![image](https://user-images.githubusercontent.com/13314239/95197400-d7844680-07d9-11eb-905d-6c5764f7cbb4.png)

When I delete the directory for chromeextensions and refresh OCS the  "Extension Install" returns to normal again.
![image](https://user-images.githubusercontent.com/13314239/95197571-16b29780-07da-11eb-96b7-745b205c5751.png)

I'm going to see if I can install any other plugin besides the bitlocker one and will update my findings here.

### Inventory log file ( optional )
This gets triggered 340 times in the Apache error log when I refresh the Extension Manager page.
`Use of uninitialized value $os in string eq at /usr/local/share/perl5/Apache/Ocsinventory/Interface/SoftwareCategory.pm line 145.
`

**Comment by daniejstriata** [comment]
I tested "Operating system install date". It did not break Plugin Manager but I still got the error printed:
`
Use of uninitialized value $os in string eq at /usr/local/share/perl5/Apache/Ocsinventory/Interface/SoftwareCategory.pm line 145.
`

**Comment by daniejstriata** [comment]
Trying to install Winupdate broke Plugin Manager

**Comment by daniejstriata** [comment]
Security was able to install without breaking Plugin Manager access.

**Comment by gillesdubois** [comment]
Hi,

I don't think you are installing plugins the right way.
Can you tell me in a few step how you are installing them ?
Also did you follow on official wiki to perform the installation ?

Regards,
Gilles.

**Comment by daniejstriata** [comment]
@gillesdubois I'm not going to use Plugins going forward. Thank you. I'm closing this.
