### ISSUE TITLE
Issue on server installing

### ISSUE THREAD

**Issue by killmasta93** [OCSInventory-NG/OCSInventory-Server#262]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : windows server 2012r2

### OCS Inventory informations
Ocs server version : 2.8
![image](https://user-images.githubusercontent.com/13953629/95488665-6f5d6e00-095b-11eb-8867-ab78b2c0e8d2.png)

### Problem's description
Installing though GPO using the network packager when server reboots get this error 

![image](https://user-images.githubusercontent.com/13953629/95488539-4a68fb00-095b-11eb-8338-57eec5d4b466.png)

This is the script though GPO bat 

```
@echo off
cd
start \\192.168.1.200\shares\publica\sistemas\inventory\inventory.exe
```
thank you

**Comment by charleneauger** [comment]
Hi @killmasta93 

In order to have a fully working windows agent, you need to be sure that all updates are installed.
Some old DLL might not be bundled in our agent.

Best regards,
Charlene
