### ISSUE TITLE
Hostname are truncated to 15chars

### ISSUE THREAD

**Issue by dust63** [OCSInventory-NG/OCSInventory-Server#266]
Operating system : Cent OS 7

Server informations
Perl version : 5.16.3
Mariadb : 10.3.12

Server installation method ( Only one choice )
 RPM Package
 Install SH
 Manual installation
OCS Inventory informations
Ocs server version : 2.7

Problem's description
If the hostaname lenght is more than 15chars the hostname is truncated.

**Comment by gillesdubois** [comment]
Hi @dust63 ,

Is that a displaying problem or database data are also truncated ?

Regards,
Gilles.

**Comment by dust63** [comment]
Yes it's also truncated in database.

**Comment by dust63** [comment]
I think the problem come from the agent that send the netbios name instead of the hostname.
If you type hostname in cmd, you have full hostname not truncated to 15chars. Do I need to close this issue and reopen one on windows agent project ?

**Comment by charleneauger** [comment]
Hi,

This bug has been fixed. Please see the windows agent PR : https://github.com/OCSInventory-NG/WindowsAgent/pull/258

Regards,
Charlene
