### ISSUE TITLE
Documentation reference

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/OCSInventory-Server#27]
Hello,

As I (try to) update the Android Agent, i'm searching for a documentation of all possibles tags **and values** that can be send by the agent.
I wasn't able to find this. I just find the DTD elements.

Is it anywhere ?
If no, should be a great idea to add this imho :)

**Comment by AnaelMobilia** [comment]
Could fusioninventory documentation defined as correct ?
=> https://github.com/fusioninventory/fusioninventory.github.io/blob/master/documentation/dev/spec/protocol/inventory.md

**Comment by gillesdubois** [comment]
Duplicate : https://github.com/OCSInventory-NG/AndroidAgent/issues/12
