### ISSUE TITLE
Software category cannot match the correct software

### ISSUE THREAD

**Issue by xupei30** [OCSInventory-NG/OCSInventory-Server#272]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Linux x86_64

### Server informations
Apache/2.4.6 (CentOS) PHP/7.4.11 mod_perl/2.0.11
Perl version : Perl/v5.16.3
Mysql  :  5.7

### OCS Inventory informations
Ocs server version : 2.8

### Problem's description
I have set the software asset type: antivirus software. My regular match is OfficeScan, but the result matches the number of software 2000 +

![soft](https://user-images.githubusercontent.com/59216351/98314781-b057a980-2011-11eb-8850-0cac875487cc.png)

**Comment by gillesdubois** [comment]
Hi @xupei30 

I would say that the regular expression is not processed properly.

Here is what I can recommend you : 

1 / Create a category only comparing the software name (keep "Advanced settings" unchecked when adding a new software) Test with a software name that only have alphanumeric character

2 / Do the same as the step one but with Chinese / Mandarin character.

The goal is to check if OCS can manage specific Chinese / Mandarin character. I know that we had some issues in the past years with Russian.

Thanks for your contribution.

Regards,
Gilles.

**Comment by xupei30** [comment]
Hi Gilles
   I tried both of the methods you gave, and the results are the same as before, matching 1000 + unrelated software.
1. I tried to use the software name with English characters instead of using advanced mode. As a result, a lot of wrong software was found;
2. I try to use the software name with English characters and enable advanced mode, and a large number of wrong software are matched;
3. I try to use the software name with English characters and use the regular wildcard "*", but the result is still a lot of wrong software.
PS: I use dynamic groups to filter out the right software.
Thank you very much
![Uploading ocs.png…]()

**Comment by xupei30** [comment]
> Hi @xupei30
> 
> I would say that the regular expression is not processed properly.
> 
> Here is what I can recommend you :
> 
> 1 / Create a category only comparing the software name (keep "Advanced settings" unchecked when adding a new software) Test with a software name that only have alphanumeric character
> 
> 2 / Do the same as the step one but with Chinese / Mandarin character.
> 
> The goal is to check if OCS can manage specific Chinese / Mandarin character. I know that we had some issues in the past years with Russian.
> 
> Edit : One workaround could be to create a dynamic group from the multi search. That could help you to temporary fix the problem while waiting for a fix.
> 
> Thanks for your contribution.
> 
> Regards,
> Gilles.
Hi Gilles
![Uploading ocs.png…]()

I tried both of the methods you gave, and the results are the same as before, matching 1000 + unrelated software.
1. I tried to use the software name with English characters instead of using advanced mode. As a result, a lot of wrong software was found;
2. I try to use the software name with English characters and enable advanced mode, and a large number of wrong software are matched;
3. I try to use the software name with English characters and use the regular wildcard "*", but the result is still a lot of wrong software.
PS: I use dynamic groups to filter out the right software.
Thank you very much

**Comment by gillesdubois** [comment]
Hi @xupei30 

Could you try the following thing : 
1 - Edit z-ocsinventory-server.conf file
2 - Set DBI_PRINT_ERROR to 1
3 - Restart Apache
4 - Wait for some inventory to comes in

I would like to see if there is any SQL / Database error.

Thanks,
Gilles.

**Comment by xupei30** [comment]
Hi @gillesdubois 
     I've put OCS_ OPT_ DBI_ PRINT_ The error value is set to 1 and restart Apache .
However, I did not find the relevant information in the MySQL error log（/var/log/mysqld.log）
I have enabled the debug of OCS and saved the debug results to PDF. Is it helpful for you to check
[OCS Inventory.pdf](https://github.com/OCSInventory-NG/OCSInventory-Server/files/5514036/OCS.Inventory.pdf)

Thank you very much

**Comment by gillesdubois** [comment]
Hi,

Could you also check the apache error log ?

Regards,
Gilles.

**Comment by xupei30** [comment]
@gillesdubois 
Hi，
apache error_log retrieved an error log:
   Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in /var/www/html/ocsreports/require/search/AccountinfoSearch.php on line 132, referer: http://10.10.10.97/ocsreports/index.php?function=visu_all_soft

error_ Log is Apache error_ Log to filter out OCS server related logs
[error_log.txt](https://github.com/OCSInventory-NG/OCSInventory-Server/files/5522201/error_log.txt)

**Comment by charleneauger** [comment]
Hi @xupei30 

Can you send us a XML inventory file ? On your windows, execute the ocsinventory.exe command with /XML parameter.

Best regards,
Charlene Auger

**Comment by gillesdubois** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Gilles.
