### ISSUE TITLE
UTF-8 text in the API output is not correctly encoded

### ISSUE THREAD

**Issue by gfdsa** [OCSInventory-NG/OCSInventory-Server#277]
### General informations
We have some strings in the hardware table now which are utf-8 encoded. These show up just fine in the web interface. But when presented via the API request the utf-8 characters are not there.
### Server informations
Perl version : This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi
Mysql Server version: 5.7.32-0ubuntu0.18.04.1 (Ubuntu)

### OCS Inventory informations
Ocs server version : 
```
$Apache::Ocsinventory::VERSION = '2.7';
$Apache::Ocsinventory::BUILD_VERSION = '751';
```
### Problem's description
Here is how it shows up in the web UI:
![image](https://user-images.githubusercontent.com/2156341/99830910-a760ef00-2b5e-11eb-9d75-2ae2c4c0df8c.png)
Here is the database record:
![image](https://user-images.githubusercontent.com/2156341/99831097-e131f580-2b5e-11eb-893b-39a0a601a3af.png)
And here is the API request/response:
![image](https://user-images.githubusercontent.com/2156341/99832157-6cf85180-2b60-11eb-98e6-a6a0e059c1d1.png)

My last perl coding was 12 years ago or something so I was just poking randomly around, and I've tracked it to how the Mojolicious renderer is being called from the `Loader.pm`. It calls the render method passing it `text` and this somehow re-encodes the string. If the string is passed as `data` this just doesn't happen:
```
-        $c->render(format => 'json', text  => Api::Ocsinventory::Restapi::Computer::Get::ComputerId::get_computer($id));
+        $c->render(format => 'json', data  => Api::Ocsinventory::Restapi::Computer::Get::ComputerId::get_computer($id));
```
![image](https://user-images.githubusercontent.com/2156341/99832053-4b976580-2b60-11eb-9ad3-b3ae824b01da.png)

Now, I can sure PR it just to fix my pain but I have no idea what I am doing :shrug:

**Comment by charleneauger** [comment]
Hi @gfdsa 

UTF-8 encoding on API Rest has been fixed on the new server version 2.8.1.

Best regards,
Charlene Auger
