### ISSUE TITLE
issue shows To Be Filled By O.E.M.

### ISSUE THREAD

**Issue by killmasta93** [OCSInventory-NG/OCSInventory-Server#278]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations

```
    Linux x86_64
    4.4.0-193-generic
    1951 MB
    1157 MB
    Common KVM processor
    Ubuntu 16.04 LTS

    7.0.33
    Apache/2.4.18 (Ubuntu)
    (Ubuntu) version 5.7.32-0ubuntu0.16.04.1

```

### OCS Inventory informations
Ocs server version :   2.8

### Problem's description
Hi currently we have an issue with 3 computers on the hardware info it shows to be filled by OEM and also shows another computer System manufacturer the issue is that when i try importing to GLPI it wont show to import 

Thank you

**Comment by farzadha2** [comment]
same here i have the same issue few computers any  updates on this?

**Comment by gillesdubois** [comment]
Hi,

The server only show data sent by the agent.
Can you create an issue on the corresponding agent ? Unix / Windows ?

Regards,
Gilles.

**Comment by killmasta93** [comment]
those computers were later removed so for now everything is working fine 
thank you
