### ISSUE TITLE
Problème "Taille disque (MB)" reportée

### ISSUE THREAD

**Issue by xnae** [OCSInventory-NG/OCSInventory-Server#28]
Bonjour,

La taille totale d'un disque dur de 1 To s'inscrit 1 MB dans la base de données "ocsweb" et dans l'affichage "ocsreports" comme le montre le fichier "export.txt" ci-joint.

Est-il possible de corriger ce problème ?

Environnement:
- #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
- OCSNG_UNIX_SERVER-2.2.1
- Ocsinventory-Unix-Agent-2.1.1

[export.txt](https://github.com/OCSInventory-NG/OCSInventory-Server/files/522801/export.txt)

**Comment by gillesdubois** [comment]
Bonjour,

Votre problème est plus lié a l'agent unix qu'au serveur ocs.
Pouvez-vous ré-ouvrir votre issue a cette adresse ? https://github.com/OCSInventory-NG/UnixAgent/issues

Merci d'avance,
Gilles Dubois.
