### ISSUE TITLE
Documentation issue?

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-Server#284]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### Problem's description
*Describe your problem here*

In file /Api/Ocsinventory/Restapi/README.md it's written:

    Prerequisites :

    Apache::DBI Mojo::Json Mojolicious::Lite Swagger Mojolicious Plack Switch

However, in file setup.sh, it's written:

                                # Dependencies :
                                # => Mojolicious::Lite
                                # => Plack
                                # => Switch

What's true?

**Comment by gillesdubois** [comment]
Hi @StCyr 

The truth is what in indicated in the setup.
Swagger is more for developmment purpose, I'll fix that now.

Regards,
Gilles.
