### ISSUE TITLE
ERR_BAD_DIGEST

### ISSUE THREAD

**Issue by alancivita** [OCSInventory-NG/OCSInventory-Server#288]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :Ubuntu 18.04.5

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  

### OCS Inventory informations
Ocs server version : 2.8.1

### Problem's description
*Describe your problem here*
OCS was working fine till 2 days ago then suddenly stopped deploying packages with the following error:
This happens for every package that we try to deploy.
The only thing we did was an apt update which updated some packages on Ubuntu.
There are no network connection problems, we are in LAN and everything is working fine.

DOWNLOAD => Building package <1608038295>
	PACKAGE => Verifying fragment files of package <1608038295>
	PACKAGE => Checking free disk space for package <1608038295>
	PACKAGE => Building ZIP for package <1608038295>
	PACKAGE => Verifying ZIP signature for package <1608038295>
	WARNING *** PACKAGE => Failed verifying signature for Package <1608038295>
ERROR *** DOWNLOAD => Failed to build package <1608038295>
	DOWNLOAD => Pausing for fragment latency (10 seconds)
	DOWNLOAD => Pausing for cycle latency (60 seconds)
	DOWNLOAD => Processing packages for cycle 3 on Wednesday, December 16, 2020 09:58:33
ERROR *** DOWNLOAD => Will not register package <1608038044> in history: result <ERR_BAD_DIGEST> not a success
DOWNLOAD => Sending result code <ERR_BAD_DIGEST> for package <1608038044>
	DID_CHECK => Read DeviceID <PST34556-0344-2020-52-40-10-34-29> and MACs <Xx:xx:xx:xx:xxxxx:xx:xx:xx:xx:xx> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <cacert.pem>
	COM SERVER => Sending HTTP Post request to URL <http://ocs.xxxxx:8888/ocsinventory>
	COM SERVER => HTTP Post response received <HTTP Status Code #200>
	COM SERVER => Cleaning cURL library
	DOWNLOAD => Result code request successfully sent
	DOWNLOAD => Pausing for fragment latency (10 seconds)
ERROR *** DOWNLOAD => Will not register package <1608038295> in history: result <ERR_BAD_DIGEST> not a success

php.ini setting are as follows:

    <IfModule mod_php7.c>
        AddType application/x-httpd-php .php
        php_flag file_uploads           on
        # Some PHP tuning for deployment feature up to 8 MB
        # post_max_size must be greater than upload_max_filesize
        # because of HTTP headers
        php_value post_max_size         300M
        php_value upload_max_filesize   299M
        # You may have to uncomment following on errors
        #php_value max_execution_time -1
        #php_value max_input_time -1

Any tips?

**Comment by StCyr** [comment]
No tip but a lot of such errors here on Windows too. We are troubleshooting them for days already

**Comment by StCyr** [comment]
Here's a link for Windows agents: https://github.com/OCSInventory-NG/WindowsAgent/issues/202

**Comment by onasiis** [comment]
Same problem over here.

**Comment by StCyr** [comment]
This is a very nasty bug: I've ended up re-installing the ocsi agent on all my clients using GPO

**Comment by gillesdubois** [comment]
Hi @StCyr 

Could you check the info file from the package that trigger the BAD_DIGEST on the agents ?

Regards,
Gilles.

**Comment by StCyr** [comment]
Sorry wrong bug. My comment was more related to https://github.com/OCSInventory-NG/WindowsAgent/issues/202

**Comment by gillesdubois** [comment]
Hi, 

Ok, this issue has been fixed on the agent. 
There is now a specific method in order to update it.

Regards,
Gilles.

**Comment by StCyr** [comment]
What do you mean by "There is now a specific method in order to update it."? Which method? This one => https://wiki.ocsinventory-ng.org/05.Deployment/Windows/Summary/#update-windows-agent ?

For the record, here's our procedure to create an OCSInventory agent package: [OCSIAgent-270122-0952-2.pdf](https://github.com/OCSInventory-NG/OCSInventory-Server/files/7949022/OCSIAgent-270122-0952-2.pdf)
