### ISSUE TITLE
wrong info in "storage"

### ISSUE THREAD

**Issue by ddk85** [OCSInventory-NG/OCSInventory-Server#29]
I have 2 different hdd in my server, but in OCS it looks a little bit strange
![ocs_storage1](https://cloud.githubusercontent.com/assets/12098788/19343184/3607b868-9146-11e6-95b2-f961733d3d56.png)

Same model - wrong
different size - correct
same firmware - wrong

**Comment by gillesdubois** [comment]
Hi,

Your issue is more related to the unix agent.
Please open an issue here : https://github.com/OCSInventory-NG/UnixAgent/issues

NB : The more informations you give on your system ( OS / Unix agent version / Server version ) the more accurate the answer will be.

Regards,
Gilles Dubois.
