### ISSUE TITLE
Hardware, Network, Devices are empty

### ISSUE THREAD

**Issue by ServiceMRE** [OCSInventory-NG/OCSInventory-Server#298]
### General informations
Operating system : Centos 7

### Server informations
Perl version : 5.16.3
Mysql / Mariadb / Percona version :  MariaDB Server version 5.5.68-MariaDB

### OCS Inventory informations
Ocs server version : 2.8.1-nightly-2021-01-26

### Problem's description
there is empty information in Hardware, Network and Devices for all new computer.
![image](https://user-images.githubusercontent.com/78038849/105876019-cd8f8900-5ffe-11eb-8e41-e070cca9ba23.png)

No error in apache and mariadb

I set mariadb debug mode to check SQL inssert query. The query is good, but empty:

                  494 Query     INSERT INTO networks(`HARDWARE_ID`,`TYPEMIB`,`IPGATEWAY`,`IPMASK`,`VIRTUALDEV`,`STATUS`,`MACADDR`,`SPEED`,`TYPE`,`IPDHCP`,`IPSUBNET`,`MTU`,`DESCRIPTION`,`IPADDRESS`) VALUES('143195','','','','','','','','','','','','','')

The software table has data.

Do you have any idea?

**Comment by gillesdubois** [comment]
Hi,

Could you perform a DESCRIBE on the tables that are empty ?
I suspect that there is a missing columns.

Regards,
Gilles.

**Comment by ServiceMRE** [comment]
Hello,
There is the results for every tables where data are "null" :

```
MariaDB [ocsweb]> describe cpus;
+-----------------------+--------------+------+-----+---------+----------------+
| Field                 | Type         | Null | Key | Default | Extra          |
+-----------------------+--------------+------+-----+---------+----------------+
| ID                    | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID           | int(11)      | NO   | MUL | NULL    |                |
| MANUFACTURER          | varchar(255) | YES  |     | NULL    |                |
| TYPE                  | varchar(255) | YES  |     | NULL    |                |
| SERIALNUMBER          | varchar(255) | YES  |     | NULL    |                |
| SPEED                 | varchar(255) | YES  |     | NULL    |                |
| CORES                 | int(11)      | YES  |     | NULL    |                |
| L2CACHESIZE           | varchar(255) | YES  |     | NULL    |                |
| CPUARCH               | varchar(255) | YES  |     | NULL    |                |
| DATA_WIDTH            | int(11)      | YES  |     | NULL    |                |
| CURRENT_ADDRESS_WIDTH | int(11)      | YES  |     | NULL    |                |
| LOGICAL_CPUS          | int(11)      | YES  |     | NULL    |                |
| VOLTAGE               | varchar(255) | YES  |     | NULL    |                |
| CURRENT_SPEED         | varchar(255) | YES  |     | NULL    |                |
| SOCKET                | varchar(255) | YES  |     | NULL    |                |
+-----------------------+--------------+------+-----+---------+----------------+

MariaDB [ocsweb]> describe bios;
+---------------+--------------+------+-----+---------+-------+
| Field         | Type         | Null | Key | Default | Extra |
+---------------+--------------+------+-----+---------+-------+
| HARDWARE_ID   | int(11)      | NO   | PRI | NULL    |       |
| SMANUFACTURER | varchar(255) | YES  |     | NULL    |       |
| SMODEL        | varchar(255) | YES  |     | NULL    |       |
| SSN           | varchar(255) | YES  | MUL | NULL    |       |
| TYPE          | varchar(255) | YES  |     | NULL    |       |
| BMANUFACTURER | varchar(255) | YES  |     | NULL    |       |
| BVERSION      | varchar(255) | YES  |     | NULL    |       |
| BDATE         | varchar(255) | YES  |     | NULL    |       |
| ASSETTAG      | varchar(255) | YES  | MUL | NULL    |       |
| MMANUFACTURER | varchar(255) | YES  |     | NULL    |       |
| MMODEL        | varchar(255) | YES  |     | NULL    |       |
| MSN           | varchar(255) | YES  |     | NULL    |       |
+---------------+--------------+------+-----+---------+-------+

MariaDB [ocsweb]> describe controllers;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| ID           | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID  | int(11)      | NO   | MUL | NULL    |                |
| MANUFACTURER | varchar(255) | YES  |     | NULL    |                |
| NAME         | varchar(255) | YES  |     | NULL    |                |
| CAPTION      | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION  | varchar(255) | YES  |     | NULL    |                |
| VERSION      | varchar(255) | YES  |     | NULL    |                |
| TYPE         | varchar(255) | YES  |     | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+

MariaDB [ocsweb]> describe drives;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| ID          | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID | int(11)      | NO   | MUL | NULL    |                |
| LETTER      | varchar(255) | YES  |     | NULL    |                |
| TYPE        | varchar(255) | YES  |     | NULL    |                |
| FILESYSTEM  | varchar(255) | YES  |     | NULL    |                |
| TOTAL       | int(11)      | YES  |     | NULL    |                |
| FREE        | int(11)      | YES  |     | NULL    |                |
| NUMFILES    | int(11)      | YES  |     | NULL    |                |
| VOLUMN      | varchar(255) | YES  |     | NULL    |                |
| CREATEDATE  | date         | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+

MariaDB [ocsweb]> describe memories;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| ID           | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID  | int(11)      | NO   | MUL | NULL    |                |
| CAPTION      | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION  | varchar(255) | YES  |     | NULL    |                |
| CAPACITY     | varchar(255) | YES  |     | NULL    |                |
| PURPOSE      | varchar(255) | YES  |     | NULL    |                |
| TYPE         | varchar(255) | YES  |     | NULL    |                |
| SPEED        | varchar(255) | YES  |     | NULL    |                |
| NUMSLOTS     | smallint(6)  | YES  |     | NULL    |                |
| SERIALNUMBER | varchar(255) | YES  |     | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+

MariaDB [ocsweb]> describe modems;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| ID          | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID | int(11)      | NO   | MUL | NULL    |                |
| NAME        | varchar(255) | YES  |     | NULL    |                |
| MODEL       | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION | varchar(255) | YES  |     | NULL    |                |
| TYPE        | varchar(255) | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+

MariaDB [ocsweb]> describe monitors;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| ID           | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID  | int(11)      | NO   | MUL | NULL    |                |
| MANUFACTURER | varchar(255) | YES  |     | NULL    |                |
| CAPTION      | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION  | varchar(255) | YES  |     | NULL    |                |
| TYPE         | varchar(255) | YES  |     | NULL    |                |
| SERIAL       | varchar(255) | YES  |     | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+

MariaDB [ocsweb]> describe networks;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| ID          | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID | int(11)      | NO   | MUL | NULL    |                |
| DESCRIPTION | varchar(255) | YES  |     | NULL    |                |
| TYPE        | varchar(255) | YES  |     | NULL    |                |
| TYPEMIB     | varchar(255) | YES  |     | NULL    |                |
| SPEED       | varchar(255) | YES  |     | NULL    |                |
| MTU         | varchar(255) | YES  |     | NULL    |                |
| MACADDR     | varchar(255) | YES  | MUL | NULL    |                |
| STATUS      | varchar(255) | YES  |     | NULL    |                |
| IPADDRESS   | varchar(255) | YES  | MUL | NULL    |                |
| IPMASK      | varchar(255) | YES  |     | NULL    |                |
| IPGATEWAY   | varchar(255) | YES  | MUL | NULL    |                |
| IPSUBNET    | varchar(255) | YES  | MUL | NULL    |                |
| IPDHCP      | varchar(255) | YES  |     | NULL    |                |
| VIRTUALDEV  | tinyint(1)   | YES  |     | 0       |                |
+-------------+--------------+------+-----+---------+----------------+

MariaDB [ocsweb]> describe ports;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| ID          | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID | int(11)      | NO   | MUL | NULL    |                |
| TYPE        | varchar(255) | YES  |     | NULL    |                |
| NAME        | varchar(255) | YES  |     | NULL    |                |
| CAPTION     | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION | varchar(255) | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+

MariaDB [ocsweb]> describe printers;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| ID          | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID | int(11)      | NO   | MUL | NULL    |                |
| NAME        | varchar(255) | YES  |     | NULL    |                |
| DRIVER      | varchar(255) | YES  |     | NULL    |                |
| PORT        | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION | varchar(255) | YES  |     | NULL    |                |
| SERVERNAME  | varchar(255) | YES  |     | NULL    |                |
| SHARENAME   | varchar(255) | YES  |     | NULL    |                |
| RESOLUTION  | varchar(50)  | YES  |     | NULL    |                |
| COMMENT     | varchar(255) | YES  |     | NULL    |                |
| SHARED      | int(11)      | YES  |     | NULL    |                |
| NETWORK     | int(11)      | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+

MariaDB [ocsweb]> describe slots;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| ID          | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID | int(11)      | NO   | MUL | NULL    |                |
| NAME        | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION | varchar(255) | YES  |     | NULL    |                |
| DESIGNATION | varchar(255) | YES  |     | NULL    |                |
| PURPOSE     | varchar(255) | YES  |     | NULL    |                |
| STATUS      | varchar(255) | YES  |     | NULL    |                |
| PSHARE      | tinyint(4)   | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+


MariaDB [ocsweb]> describe sounds;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| ID           | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID  | int(11)      | NO   | MUL | NULL    |                |
| MANUFACTURER | varchar(255) | YES  |     | NULL    |                |
| NAME         | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION  | varchar(255) | YES  |     | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+


MariaDB [ocsweb]> describe storages;
+--------------+--------------+------+-----+---------+----------------+
| Field        | Type         | Null | Key | Default | Extra          |
+--------------+--------------+------+-----+---------+----------------+
| ID           | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID  | int(11)      | NO   | MUL | NULL    |                |
| MANUFACTURER | varchar(255) | YES  |     | NULL    |                |
| NAME         | varchar(255) | YES  |     | NULL    |                |
| MODEL        | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION  | varchar(255) | YES  |     | NULL    |                |
| TYPE         | varchar(255) | YES  |     | NULL    |                |
| DISKSIZE     | int(11)      | YES  |     | NULL    |                |
| SERIALNUMBER | varchar(255) | YES  |     | NULL    |                |
| FIRMWARE     | varchar(255) | YES  |     | NULL    |                |
+--------------+--------------+------+-----+---------+----------------+


MariaDB [ocsweb]> describe videos;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| ID          | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID | int(11)      | NO   | MUL | NULL    |                |
| NAME        | varchar(255) | YES  |     | NULL    |                |
| CHIPSET     | varchar(255) | YES  |     | NULL    |                |
| MEMORY      | varchar(255) | YES  |     | NULL    |                |
| RESOLUTION  | varchar(255) | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+

```

Thanks

**Comment by gillesdubois** [comment]
Can you also describe the hardware table ?

Thanks.

**Comment by ServiceMRE** [comment]
Of course:

`
MariaDB [ocsweb]> describe hardware;
+----------------+---------------------+------+-----+---------+----------------+
| Field          | Type                | Null | Key | Default | Extra          |
+----------------+---------------------+------+-----+---------+----------------+
| ID             | int(11)             | NO   | PRI | NULL    | auto_increment |
| DEVICEID       | varchar(255)        | NO   | MUL | NULL    |                |
| NAME           | varchar(255)        | YES  | MUL | NULL    |                |
| WORKGROUP      | varchar(255)        | YES  | MUL | NULL    |                |
| USERDOMAIN     | varchar(255)        | YES  |     | NULL    |                |
| OSNAME         | varchar(255)        | YES  | MUL | NULL    |                |
| OSVERSION      | varchar(255)        | YES  |     | NULL    |                |
| OSCOMMENTS     | varchar(255)        | YES  |     | NULL    |                |
| PROCESSORT     | varchar(255)        | YES  |     | NULL    |                |
| PROCESSORS     | int(11)             | YES  |     | 0       |                |
| PROCESSORN     | smallint(6)         | YES  |     | NULL    |                |
| MEMORY         | int(11)             | YES  | MUL | NULL    |                |
| SWAP           | int(11)             | YES  |     | NULL    |                |
| IPADDR         | varchar(255)        | YES  |     | NULL    |                |
| DNS            | varchar(255)        | YES  |     | NULL    |                |
| DEFAULTGATEWAY | varchar(255)        | YES  |     | NULL    |                |
| ETIME          | datetime            | YES  |     | NULL    |                |
| LASTDATE       | datetime            | YES  |     | NULL    |                |
| LASTCOME       | datetime            | YES  |     | NULL    |                |
| QUALITY        | decimal(7,4)        | YES  |     | NULL    |                |
| FIDELITY       | bigint(20)          | YES  |     | 1       |                |
| USERID         | varchar(255)        | YES  | MUL | NULL    |                |
| TYPE           | int(11)             | YES  |     | NULL    |                |
| DESCRIPTION    | varchar(255)        | YES  |     | NULL    |                |
| WINCOMPANY     | varchar(255)        | YES  |     | NULL    |                |
| WINOWNER       | varchar(255)        | YES  |     | NULL    |                |
| WINPRODID      | varchar(255)        | YES  |     | NULL    |                |
| WINPRODKEY     | varchar(255)        | YES  |     | NULL    |                |
| USERAGENT      | varchar(50)         | YES  |     | NULL    |                |
| CHECKSUM       | bigint(20) unsigned | YES  | MUL | 262143  |                |
| SSTATE         | int(11)             | YES  |     | 0       |                |
| IPSRC          | varchar(255)        | YES  |     | NULL    |                |
| UUID           | varchar(255)        | YES  |     | NULL    |                |
| ARCH           | varchar(10)         | YES  |     | NULL    |                |
| CATEGORY_ID    | int(11)             | YES  |     | NULL    |                |
| ARCHIVE        | int(11)             | YES  |     | NULL    |                |
+----------------+---------------------+------+-----+---------+----------------+
`

**Comment by GUPVF** [comment]
Hello! I have the same problem. I'm looking forward to hearing from you.

**Comment by diegonmeza** [comment]
Hello! I have the same problem. I try with 2.8 agent for Windows and 2.6 agent for Linux, and got the same results.

**Comment by lbania-it** [comment]
The same here
Freebsd newest agent and server , no bios information. 
Tried older agent also do not work.
With older server works perfectly

**Comment by rbernardes** [comment]
Same here! Waiting fora workaround (ubuntu 20.04/mariadb 10.5)

**Comment by RobinhoZ** [comment]
Here also the same issue, lets hope for fix (ubuntu 20.04/mariadb 10.5)

**Comment by GUPVF** [comment]
For himself found a temporary solution to the problem:
installed version 2.8 and installed mysql 5.5.26. While everything works.
Waiting to resolve the issue with the latest version.

**Comment by gillesdubois** [comment]
Hi,

Unfortunately we can't reproduce the issue mentionned even with the same operating system.
More in-depth testing will be performed.

If someone can send us an (anonymized) SQL dump of their OCS database to contact@ocsinventory-ng.org it would be appreciated.

Regards,
Gilles Dubois.

**Comment by ServiceMRE** [comment]
Hello,
How do you anonymize the SQL Dump?
Regards?

**Comment by RobinhoZ** [comment]
i have the same question. i have a completely new ocs installation without any personalizations, i think this dump would be ok.

**Comment by gillesdubois** [comment]
It really depend on what you think is sensitive data.
In the case the data is pretty much clear and empty you can send the dump as it is without worrying too much.

Regards,
Gilles.

**Comment by ServiceMRE** [comment]
@RobinhoZ : if your dump is pretty empty, could you send yours? Mine is big.

**Comment by RobinhoZ** [comment]
Mail is out, thank you very much for your support!

**Comment by ServiceMRE** [comment]
I just have a question, if the sql insert command is adding empty value, it's logic that the database contain empty line.
My question is, why the insert command is adding empty value? There a link between this and the database structure?

**Comment by lbania-it** [comment]
> For himself found a temporary solution to the problem:
> installed version 2.8 and installed mysql 5.5.26. While everything works.
> Waiting to resolve the issue with the latest version.

I have fresh Freebsd installation 12.2
installed ocsinventory-server from pkg
ocsinventory-ocsreports-2.8        
ocsinventory-server-2.8            
installed oncs-agent 2.8
mysql-server 5.5
![image](https://user-images.githubusercontent.com/78254306/106801900-90f90880-6662-11eb-8f43-08768619dbb0.png)
**Still no bios informarmation**
![image](https://user-images.githubusercontent.com/78254306/106802004-aff79a80-6662-11eb-9488-7a9994caa507.png)

**Can see only Processor and Disks rest in blank**
![image](https://user-images.githubusercontent.com/78254306/106802150-d4ec0d80-6662-11eb-8fb8-247e99227053.png)

On the newest 2.8.1 reproduced the same issue

**Comment by gillesdubois** [comment]
Hi,

We found the cause of the problem, we are currently fixing it.

Regards,
Gilles.

**Comment by RobinhoZ** [comment]
good news, thanks for your response, we will wait :)

**Comment by ServiceMRE** [comment]
Great, thanks

**Comment by rbernardes** [comment]
I applied the fix, but, apparently not work.
I force all the clients again.

'
MariaDB [ocs]> describe cpus;
+-----------------------+--------------+------+-----+---------+----------------+
| Field                 | Type         | Null | Key | Default | Extra          |
+-----------------------+--------------+------+-----+---------+----------------+
| ID                    | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID           | int(11)      | NO   | MUL | NULL    |                |
| MANUFACTURER          | varchar(255) | YES  |     | NULL    |                |
| TYPE                  | varchar(255) | YES  |     | NULL    |                |
| SERIALNUMBER          | varchar(255) | YES  |     | NULL    |                |
| SPEED                 | varchar(255) | YES  |     | NULL    |                |
| CORES                 | int(11)      | YES  |     | NULL    |                |
| L2CACHESIZE           | varchar(255) | YES  |     | NULL    |                |
| CPUARCH               | varchar(255) | YES  |     | NULL    |                |
| DATA_WIDTH            | int(11)      | YES  |     | NULL    |                |
| CURRENT_ADDRESS_WIDTH | int(11)      | YES  |     | NULL    |                |
| LOGICAL_CPUS          | int(11)      | YES  |     | NULL    |                |
| VOLTAGE               | varchar(255) | YES  |     | NULL    |                |
| CURRENT_SPEED         | varchar(255) | YES  |     | NULL    |                |
| SOCKET                | varchar(255) | YES  |     | NULL    |                |
+-----------------------+--------------+------+-----+---------+----------------+
15 rows in set (0.001 sec)


MariaDB [ocs]> describe hardware;
+----------------+---------------------+------+-----+---------+----------------+
| Field          | Type                | Null | Key | Default | Extra          |
+----------------+---------------------+------+-----+---------+----------------+
| ID             | int(11)             | NO   | PRI | NULL    | auto_increment |
| DEVICEID       | varchar(255)        | NO   | MUL | NULL    |                |
| NAME           | varchar(255)        | YES  | MUL | NULL    |                |
| WORKGROUP      | varchar(255)        | YES  | MUL | NULL    |                |
| USERDOMAIN     | varchar(255)        | YES  |     | NULL    |                |
| OSNAME         | varchar(255)        | YES  | MUL | NULL    |                |
| OSVERSION      | varchar(255)        | YES  |     | NULL    |                |
| OSCOMMENTS     | varchar(255)        | YES  |     | NULL    |                |
| PROCESSORT     | varchar(255)        | YES  |     | NULL    |                |
| PROCESSORS     | int(11)             | YES  |     | 0       |                |
| PROCESSORN     | smallint(6)         | YES  |     | NULL    |                |
| MEMORY         | int(11)             | YES  | MUL | NULL    |                |
| SWAP           | int(11)             | YES  |     | NULL    |                |
| IPADDR         | varchar(255)        | YES  |     | NULL    |                |
| DNS            | varchar(255)        | YES  |     | NULL    |                |
| DEFAULTGATEWAY | varchar(255)        | YES  |     | NULL    |                |
| ETIME          | datetime            | YES  |     | NULL    |                |
| LASTDATE       | datetime            | YES  |     | NULL    |                |
| LASTCOME       | datetime            | YES  |     | NULL    |                |
| QUALITY        | decimal(7,4)        | YES  |     | NULL    |                |
| FIDELITY       | bigint(20)          | YES  |     | 1       |                |
| USERID         | varchar(255)        | YES  | MUL | NULL    |                |
| TYPE           | int(11)             | YES  |     | NULL    |                |
| DESCRIPTION    | varchar(255)        | YES  |     | NULL    |                |
| WINCOMPANY     | varchar(255)        | YES  |     | NULL    |                |
| WINOWNER       | varchar(255)        | YES  |     | NULL    |                |
| WINPRODID      | varchar(255)        | YES  |     | NULL    |                |
| WINPRODKEY     | varchar(255)        | YES  |     | NULL    |                |
| USERAGENT      | varchar(50)         | YES  |     | NULL    |                |
| CHECKSUM       | bigint(20) unsigned | YES  | MUL | 262143  |                |
| SSTATE         | int(11)             | YES  |     | 0       |                |
| IPSRC          | varchar(255)        | YES  |     | NULL    |                |
| UUID           | varchar(255)        | YES  |     | NULL    |                |
| ARCH           | varchar(10)         | YES  |     | NULL    |                |
| CATEGORY_ID    | int(11)             | YES  |     | NULL    |                |
| ARCHIVE        | int(11)             | YES  |     | NULL    |                |
+----------------+---------------------+------+-----+---------+----------------+
36 rows in set (0.002 sec)

![image](https://user-images.githubusercontent.com/4452250/106933381-96ecf900-66f7-11eb-95d3-e41d42e3b5c3.png)

**Comment by rbernardes** [comment]
Its works! Deleted all the colected linfo and force the client is the tip!

**Comment by RobinhoZ** [comment]
It works! Thank you very much and have a nice day / weekend

**Comment by ServiceMRE** [comment]
Hi,
Thanks for the fix.
It's working with "new computer", but for computer which have "empty" entry (perhaps not all of them), there is no update

**Comment by kvolk2git** [comment]
Hi! I have a same problem.

`
PHP Version :
Web Server :
Database Server :
Version OCSReports:
7.4.3
Apache/2.4.41 (Ubuntu)
Ubuntu 20.04 version 10.3.25-MariaDB-0ubuntu0.20.04.1
2.8.1
`

There were no problems during installation and after, but after running the agent on the computers, information about the hardware and network is not displayed, there are no values in the database tables. At the same time, in the "Software" and "Administrative data" sections, the lines are there and the information is displayed.

![01](https://user-images.githubusercontent.com/78740198/107229616-1992f280-6a2f-11eb-8552-511c34e1cae9.jpg)
![02](https://user-images.githubusercontent.com/78740198/107229618-1ac41f80-6a2f-11eb-845f-9b8d71931a34.jpg)
![03](https://user-images.githubusercontent.com/78740198/107229622-1bf54c80-6a2f-11eb-95e9-44cfcd0f4607.jpg)
![04](https://user-images.githubusercontent.com/78740198/107229626-1c8de300-6a2f-11eb-97e3-68f1a6abcf0b.jpg)

**Comment by kvolk2git** [comment]
The problem has not been solved? I removed the log of requests to the database from the client and there is completely no data about the hardware, only a couple of lines and data about the software, maybe this is the client's problem?

**Comment by kvolk2git** [comment]
I made changes from the patch to the file, rebooted the server, and deleted the data. The new data is loaded correctly.
 /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Inventory/Data.pm

https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1121

**Comment by JayPi01** [comment]
Same problem here. Installed ocsinventory server as described in this howto: https://www.osradar.com/how-to-install-ocs-inventory-server-on-ubuntu-20-04/ . Because vendor/autoload.php was not found did a 'cd /usr/share/ocsinventory-reports/ocsreports' and 'composer install'. 

'Administrative data' and 'Software' are ok, 'Hardware', 'Network' and 'Devices' are empty. When the agent (2.8.0) is called to produce local output like 'ocsinventory-agent --local /tmp' all hardware is visible in the created file.
Please help.

**Comment by charleneauger** [comment]
Hi @JayPi01 ,

To fix this bug, apply the patch #301 on your server, restart apache, delete the data and send an new inventory.

Best regards,
Charlene Auger

**Comment by JayPi01** [comment]
@charleneauger

Thanks a lot! The fix works.

Best regards,
 Jörg

**Comment by jpesguerra** [comment]
Can somebody provide a detailed step on how to fix this issue?

**Comment by jpesguerra** [comment]
> Can somebody provide a detailed step on how to fix this issue?

anyone?

**Comment by jpesguerra** [comment]
> @charleneauger
> 
> Thanks a lot! The fix works.
> 
> Best regards,
> Jörg

how?

**Comment by JayPi01** [comment]
@jpesguerra 
download Data.pm from here:
https://github.com/OCSInventory-NG/OCSInventory-Server/tree/master/Apache/Ocsinventory/Server/Inventory
and replace the original Data.pm here:
/usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Inventory
Maybe its save to rename the original one. :)

**Comment by jpesguerra** [comment]
Thanks!



John Esguerra
Business IT Manager

+63 998 5909394  | +63 02 657 1860  | carousell.ph

40/Floor, Unionbank Plaza, Meralco Ave, Ortigas Center, Pasig City, Metro
Manila

[image:
https://lh6.googleusercontent.com/_cgT2VfTIeb6hCzSO9mmXFqZSdR-QaV7FhC-uQd2nE9bfDRDhSF8Dxn3pnOkr5966tCBxspylpMc6T8Oe7T8cLmiFHTAC6ZrgQPghIrpTrWpHjap5tq74Qds2CM5z2X0DPq1OCbv]

**Comment by jpesguerra** [comment]
> @jpesguerra
> download Data.pm from here:
> https://github.com/OCSInventory-NG/OCSInventory-Server/tree/master/Apache/Ocsinventory/Server/Inventory
> and replace the original Data.pm here:
> /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Inventory
> Maybe its save to rename the original one. :)

Thanks!
