### ISSUE TITLE
OCSAgent and TLS 1.2

### ISSUE THREAD

**Issue by Lud3rik** [OCSInventory-NG/OCSInventory-Server#30]
Hello team,

After putting this line on my apache config, I noticed that OCS Agent was unable to send information

SSLProtocol -all +TLSv1.2

So I was forced to write "SSLProtocol -all +SSLv3 +TLSv1.2" in order to 
- make agent communicate with server
- make my webserver accesible by web

Is it scheduled to add the support of TLS in the next version?

**Comment by gillesdubois** [comment]
Hi,

I need more informations to answer you.
Which agent version are you using ? Which OS ?

Regards,
Gilles Dubois.

**Comment by Lud3rik** [comment]
Hi,

OCSNG-Windows-Agent-2.1.1.3 / Windows 10

Thanks

**Comment by gillesdubois** [comment]
Hi,

Take a look at this commit : 
https://github.com/OCSInventory-NG/WindowsAgent/commit/4517a321fa7c9af505036dd47979b4bf54c8cd47

We introduced the 1.0.2 version of OpenSSL in our development branch which support TLS 1.2
When the next agent version will be released you will be able to use this statement in your config file.

Regards,
Gilles Dubois.

**Comment by Lud3rik** [comment]
Ok thanks a lot!
Be aware of poodle too :p
