### ISSUE TITLE
Editing a deployment package presents a blank screen

### ISSUE THREAD

**Issue by fourstepper** [OCSInventory-NG/OCSInventory-Server#303]
### General informations
Operating system : CentOS 7

### Server informations
Perl version : v5.16.3 
Mysql / Mariadb / Percona version :  mysql  Ver 15.1 Distrib 10.1.46-MariaDB

### OCS Inventory informations
Ocs server version : 2.7

### Problem's description
*Describe your problem here*
When trying to edit a package through Deployment > Activate > [edit icon], I encounter a blank screen with this URL:

https://example.com/ocsreports/index.php?function=tele_package&head=1&package=1612442972

https://example.com/ocsreports/index.php?function=tele_package takes me to the Package Builder (same as Deployment > Build)

This makes it impossible to edit a package.

Is there a solution to this in 2.7?

**Comment by gillesdubois** [comment]
Hi @fourstepper 

Unfortunately we don't provide a fix for 2.7. What's your reason for not upgrading to 2.8 ?

Regards,
Gilles.

**Comment by fourstepper** [comment]
Hello @gillesdubois ,

When we attempted to upgrade to 2.8, some older agents (think 2.1 - 2.3 versions) stopped working.

I am just wondering if this is fixed in 2.8 or if it could be something version-agnostic? Or rather, rephrased, is this is a known problem for 2.7?

Thanks!

**Comment by gillesdubois** [comment]
Hey,

`When we attempted to upgrade to 2.8, some older agents (think 2.1 - 2.3 versions) stopped working.`

Are you speaking about Windows ou Linux agent ?

Regards,
Gilles.

**Comment by fourstepper** [comment]
Hello @gillesdubois,

We have so far only been using WIndows agents

**Comment by gillesdubois** [comment]
Ok, please try to completely uninstall the agent and reinstall it. When there is a major gap between two versions some files doesn't update properly.

**Comment by fourstepper** [comment]
We have to figure out how to do this properly. One of the ideas was to actually update/reinstall the agents with OCS Deployment

**Comment by gillesdubois** [comment]
Hi,

With the 2.9 we removed the editing capabilities as it was causing too much problem.
The new wizard being lighter than the old one, recreating package is way faster now.

Regards,
Gilles.
