### ISSUE TITLE
HTTP 500 when receiving an inventory with an uninstalled plugin

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-Server#309]
### OCS Inventory informations
Ocs server version : 2.8

### Problem's description

1. Install a plugin
2. Deploy the agent part on all agents
3. Wait a few days
4. Uninstall the pluging on the server => Agents can't report their inventory anymore (HTTP 500)

In logs: 

    DBD::mysql::db do failed: Table 'ocsweb.<plugin_table>' doesn't exist at /usr/share/perl5/Apache/Ocsinventory/Server/Inventory/Update.pm line 98.

### Expected result

OCSInventory-Server shouldn't choke on missing plugin table.

**Comment by StCyr** [comment]
Current behaviour means I have to uninstall the agent part on all agents prior to uninstalling the server part which is a bit cumbersome

**Comment by gillesdubois** [comment]
Hi @StCyr 

If the plugin is completely uninstalled from the server it shouldn't trigger this error.
Are you sure that you remove the communication part (located in /etc/ocsinventory-server) and restart apache ?

Regards,
Gilles.

**Comment by StCyr** [comment]
Yes, you're right. I'll update the Wiki

**Comment by gillesdubois** [comment]
Ok thanks for your contribution @StCyr !

Gilles.
