### ISSUE TITLE
[API] is it possible to delete a computer from the inventory using the API?

### ISSUE THREAD

**Issue by fourstepper** [OCSInventory-NG/OCSInventory-Server#312]
As described in [here](https://wiki.ocsinventory-ng.org/11.Rest-API/DELETE-Routes/), it seems it is not possible at the moment.

Could you please confirm?

Thank you,
Robin

**Comment by gillesdubois** [comment]
Hi,

No, the API is only meant to be use with GET now. No PUT / POST / DELETE.

Gilles.
