### ISSUE TITLE
[feature] ipdiscover subnet whitelist

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-Server#316]
The ipdiscover feature is not really compatible with nomad enpoints: When our employees work from home or visit a customer they sometime scan the subnet they are on.

Aside from the mess it creates in the ipdiscover page (lots of ininteresting subnets), it raises security issues for our customers (Would you like someone coming to your company scanning your network?).

An ipdiscover subnet whitelist would solve these issues

**Comment by gillesdubois** [comment]
Hi @StCyr 

Why don't you create a group containing nomad endpoints and ban them from IPDiscover ?

Regards,
Gilles.

**Comment by StCyr** [comment]
That's a good idea that I didn't had till now :-) thanks

**Comment by gillesdubois** [comment]
Ahah no problems, hope it'll help you getting your issue fixed.

Regards,
Gilles.
