### ISSUE TITLE
 Duplicate MAC address and serial number, but not duplicate

### ISSUE THREAD

**Issue by xupei30** [OCSInventory-NG/OCSInventory-Server#318]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOS7

### Server informations
PHP Version :7.4.11
Web Server :Apache/2.4.6 (CentOS) PHP/7.4.11 mod_perl/2.0.11 Perl/v5.16.3
Database Server :MySQL Community Server (GPL) version 5.7.32
### OCS Inventory informations
Ocs server version : 2.8

### Problem's description
When I was screening duplicate assets, the system prompted that there were 14 computers with the same MAC address and serial number, but actually the MAC address and serial number of these 14 computers were not the same, and they were completely different computers

![微信图片_20210414150957](https://user-images.githubusercontent.com/59216351/114668491-65b22a00-9d33-11eb-8548-d73b3295ed42.png)

**Comment by gillesdubois** [comment]
Hi,

Duplicates has been reworked with the 2.9.
The 2.8 version had a lot of flaw in its design.

Please update to the 2.9, the displaying should be better / more intuitive.

Regards,
Gilles.
