### ISSUE TITLE
issues about REST API, some links not open sucess

### ISSUE THREAD

**Issue by heikafeiylt** [OCSInventory-NG/OCSInventory-Server#319]
### General informations
Operating system : Centos 7

### Server informations
Perl version : V5.16.3
Mysql / Mariadb / Percona version :  Apache/2.4.6 (CentOS) PHP/7.3.27 mod_perl/2.0.11 Perl/v5.16.3
mysql  Ver 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1

### OCS Inventory informations
Ocs server version : 2.8.1

### Problem's description
I've tried access the links follow DOCUMENTAION, but not all links success.

total 12 links have been refered in "Docs » 11.Rest API » GET Routes"

5 links are success, 5 links are "page not found", 2 links are "we're sorry, something went very wrong!"

detail as below:

GET Routes
myocsserver/ocsapi/v1/my/routes
page not found

List computers ID
myocsserver/ocsapi/v1/computers/listID
success

List X computers details (start, limit)
myocsserver/ocsapi/v1/computers?start={startoffset}&limit={limitoffset}
success

List one computer details
myocsserver/ocsapi/v1/computer/{ID}/{specificSection}
success

List computer that match a term
myocsserver/ocsapi/v1/computers/search?start={startoffset}&limit={limitoffset}&{searchCriteria}={valueToMatch}
success

List softwares (start, limit, soft)
myocsserver/ocsapi/v1/softwares?start={startoffset}&limit={limitoffset}&soft={software}
page not found

List SNMP Type
myocsserver/ocsapi/v1/snmps/typeList
success

List X SNMP Type details (start, limit)
myocsserver/ocsapi/v1/snmps?start={startoffset}&limit={limitoffset}
page not found

List one SNMP Type details
myocsserver/ocsapi/v1/snmp/{TABLE_TYPE_NAME}/{ID}
we're sorry, something went very wrong!

List IP Discover Networks
myocsserver/ocsapi/v1/ipdiscover/
we're sorry, something went very wrong!

List IP Discover Networks Elements
myocsserver/ocsapi/v1/ipdiscover/{networkID}
page not found

List IP Discover Elements by TAG
myocsserver/ocsapi/v1/ipdiscover/{TAG}
page not found

could you give me some suggestion? how to check it? thanks in advance.

**Comment by gillesdubois** [comment]
Hi,

Could you try with the 2.9 in nightly ? 

Link : http://download.ocsinventory-ng.org/nightly/

Regards,
Gilles.
