### ISSUE TITLE
No mass deploy possible

### ISSUE THREAD

**Issue by larieu** [OCSInventory-NG/OCSInventory-Server#32]
Operating system

OS Name :      Linux x86_64
Version :        2.6.32-642.11.1.el6.x86_64
RAM installed :      3832 Mo
Free RAM :
CPU :           Common KVM processor
Distribution :      CentOS release 6.8 (Final)

Software

PHP Version :     5.6.28 (apache2handler)
Web Server :     Apache/2.2.15 (CentOS)
Database Server :     Source distribution version 5.1.73
Version OCSReports:      2.3

OCS updated from 2.1.1 

build a new package to update OCS-NG-Windows-Agent
( 
make a zip with the exe , and build the package to run the command
`OCS-NG-Windows-Agent-Setup.exe /S /UPGRADE /NOSPLASH /NO_SYSTRAY /SSL=0 /SERVER=http://ocs.mydomain.com/ocsinventory`
)

activate, for manual only,

test on one instance as
find the appropriate computer >  cluck on the computer name >  Deployment > Add package > use advanced... NO + VALIDATE > select from the list the appropriate package and click on the small square on the right,

wait the right amount of time ( or force  the computer to contact the server ) 
the package is SUCCESS 

MASS DEPLOY

" search with various criteria " > will result in a list of 5~10 computers
select all or some of them > deploy > Mass affectation = "for selection" >  Use advanced ... for teledeply  = "NO" + VALIDATE >
without any obvious error (even on the log file ) 
Mass affectation = "for selection" >  Use advanced ... for teledeply  = "NO" + VALIDATE >
...
Mass affectation = "for selection" >  Use advanced ... for teledeply  = "NO" + VALIDATE >

NO list for packages to select from

**Comment by gillesdubois** [comment]
Hi,

I will try to reproduce the bug and will come back to you as soon as possible.
Mass actions has been reworked for the 2.3RC so you bug might be already fixed.

Regards,
Gilles Dubois.

**Comment by MyTheValentinus** [comment]
Hello  @larieu,
The bug is apparently fixed, can you test on the 2.3RC please ?
I have tested and no found bug.
Thanks
