### ISSUE TITLE
[BUG] API call issue, can't get Full computer info

### ISSUE THREAD

**Issue by YgrekIx** [OCSInventory-NG/OCSInventory-Server#321]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 20.04

### Server informations
Perl version : 5.30.0
Mysql / Mariadb / Percona version :  10.3.25-MariaDB-0ubuntu0.20.04.1

### OCS Inventory informations
Ocs server version : 2.9

### Problem's description
Can't get: /ocsapi/v1/computer/[Computer_Number]/
Can get: /ocsapi/v1/computer/[Computer_Number]/Software

Problem appear just after updating server to 2.9

Error Screen:
![image](https://user-images.githubusercontent.com/4072422/116667234-40145a00-a99c-11eb-93ab-c2ff7e195f6d.png)

**Comment by gillesdubois** [comment]
Hi @YgrekIx 

This issue has been fixed on the master, please use our nightlies or wait for the next minor version.

http://download.ocsinventory-ng.org/nightly/

Regards,
Gilles.
