### ISSUE TITLE
add select list

### ISSUE THREAD

**Issue by bluedark** [OCSInventory-NG/OCSInventory-Server#325]
Hello,
I would like to add a drop-down list in my groups and be able to display it in column with the other columns by default.
I manage to create the field of type "select" but I do not see where to add choices in it. 
Thank you !

**Comment by bluedark** [comment]
up
thanks !

**Comment by bluedark** [comment]
i found out how to add data to my SELECT column.

But I have a new problem: I manage to add this column when I am in "all computers" but I cannot search in it.

While the search works on all the other columns (which are not SELECT)

Thanks!

**Comment by gillesdubois** [comment]
Hi,

This issue is related to the reports and not the server, please recreate the issue using the template.

Regards,
Gilles.
