### ISSUE TITLE
OCS Api Computer pagination return "null" instead of null

### ISSUE THREAD

**Issue by dust63** [OCSInventory-NG/OCSInventory-Server#328]
### OCS Inventory informations
Ocs server version : 2.8

### Problem's description
*when you call the route of /computer&start=XXX&limit=XXX if you riched the end of paignation, OCS api return a string "null".
It's not a correct way. You should send null (no data) instead of a literral because it's a json object that we attempt.
The best approach for me in this case is to sent only a 204 status code to prevent client that no data are available.*

Regards.

**Comment by charleneauger** [comment]
Hi @dust63 ,

This problem is fixed in the latest versions.

Best regards,
Charlene
