### ISSUE TITLE
No Network information shown at computer harware

### ISSUE THREAD

**Issue by larieu** [OCSInventory-NG/OCSInventory-Server#33]
login into OCS Inventory

in the main > all computers
select MAC Address column 
here you are able to see computer001 <> mac 00:01:02:03:04:05
click on the "computer001" >  hardware 

scroll down to Networks
here you'll have only 

> No data available in table
> Showing 0 to 0 of 0 entries

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed in the 2.3RC you should try to perform a clean update and try again.

Regards,
Gilles Dubois.
