### ISSUE TITLE
Package Deployment - Load large file 

### ISSUE THREAD

**Issue by Goldtool** [OCSInventory-NG/OCSInventory-Server#330]
### General informations
Operating system : Debian 10

### Server informations
Mariadb version : 10.3.27
Php version : 7.3.27
Apache : 2.4.46

### OCS Inventory informations
Ocs server version : 2.9

### Problem's description
Package deployment is configured on my OCS Inventory server and works fine !

But, when I tried to create a package to store a 2.8GB zip, my browser send me a "err_connection_reset" after ~1 minute.

I saw that some changes has to be done in /etc/apache2/conf-available/ocsinventory-reports.conf like : 
- Increase : php_value post_max_size and php_value upload_max_filesize (I set these value to 3001 and 3000)

I also restart Apache service after any changes. But I still can't upload large file.

Anyone can help me ? 
Thank you in advance !

**Comment by gillesdubois** [comment]
Hi,

Please look at your php configuration.

The default value for the max execution time is 60 seconds.
Update the variable and that be ok.

Regards,
Gilles.

**Comment by Goldtool** [comment]
Dear,

Thank you for your answer but it didn't solved the issue

+ when I create package on the server directly (via localhost) I am able to create it and deploy it
