### ISSUE TITLE
Plugin isn't working

### ISSUE THREAD

**Issue by DaniKawaii** [OCSInventory-NG/OCSInventory-Server#339]
Hi!

### General informations
Operating system : Ubuntu 20.04.2 LTS

### Server informations
Perl version : Perl/v5.16.3
Mysql / Mariadb / Percona version :  MySQL Community Server (GPL) version 5.7.34

### OCS Inventory informations
Ocs server version :  2.9 (Docker)

### Problem's description
I've installed crontabTasks 2.1 plugin (https://github.com/PluginsOCSInventory-NG/crontabTasks), but I don't receive information from the machines which have the plugin's agent deployed.

The steps I did to install the plugin:
* Unziped plugin folder here: /usr/share/ocsinventory-reports/ocsreports/extensions
* Went to Extensions → Extensions Manager and clicked Install button
* Logout and login
* Created directory /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/Crontabtasks inside the container
* Copied Map.pm inside the folder of the previous step
* Copied crontabtasks.conf inside of /etc/ocsinventory-server/plugins/
* Here I restarted the container and then I saw with ps -aux that all the processes had been restarted
* Then I copied the plugin's agent part (file CronTab.pm) inside  /etc/ocsinventory-agent/Plugins or inside  /etc/ocsinventory/Plugins in other machines (in some machines I installed the agent manually, and in others using the Ansible role https://github.com/OCSInventory-NG/Ansible-Role-For-UnixAgent, that's the reason why the folder is sometimes called /ocsinventory-agent and sometimes /ocsinventory)
* I forced agent execution in those machines to update the information
* Crontabtasks table appears in Configuration tab of each machine, but it doesn't have any information. And in the logs I don't see information about the execution of the plugin.
* I can make queries on crontabtasks, but the result is always empty (that's because the table is created in mysql db, but it's empty).

The machines where I installed the plugin do have cron tasks. Is there a step that am I missing? I used https://wiki.ocsinventory-ng.org/10.Plugin-engine/Using-plugins-installer/ as a guide.

Here you can see the plugin in Extensions Manager
![image](https://user-images.githubusercontent.com/42950513/127045837-e9627f9f-dd49-4a5e-9d64-c48f88012369.png)

Here is the table in the database (it's empty).
![image](https://user-images.githubusercontent.com/42950513/127047463-9111fb0d-4981-4fa0-897b-0db9fb72767b.png)

Here is the result of a query:
![image](https://user-images.githubusercontent.com/42950513/127047798-3d0ba280-cac0-40ee-82b7-ae621e68be46.png)

Here is the plugin table in Configuration tab of a machine:
![image](https://user-images.githubusercontent.com/42950513/131518959-421a43ee-0d92-4fac-b1d2-1051b1dec7d2.png)

Thanks in advance!

**Comment by charleneauger** [comment]
Hi @DaniKawaii ,

To install unix agent plugin, copy the CronTab.pm to `/usr/local/share/perl/5.30.0/Ocsinventory/Agent/Modules`.
Next, edit the file `/etc/ocsinventory/modules.conf` and add this line : 

`use Ocsinventory::Agent::Modules::CronTab;`

Note : Crontab.pm  require the Config::CronTab lib to work.

Best regards,
Charlene
