### ISSUE TITLE
Default setup language in english

### ISSUE THREAD

**Issue by ppasserini** [OCSInventory-NG/OCSInventory-Server#34]
When you install the server for the first time, there's no way to select the install language.
You'll be able to select it only when you login on the web console.

**Comment by gillesdubois** [comment]
Hi,

The setup and first installation procedure don't have any translation.
Translation are really time consuming and we don't think that translate the setup will improve the user experience.

The setup is not using any complex english terms and won't be translated in the (near) future.

Thanks for getting in touch with us.

Regards,
Gilles Dubois.

**Comment by ppasserini** [comment]
Hi,

I agree with you when you say this is a time consuming activity (I did in
the past) and it's also true that the setup is quite simple. Nevertheless
all the strings are already translated:

have a look to (eng/fra/ita files):  2000 * SETUP voices 2000-2200 *
(2000-2029 Common voices *** 2030-2200 Setup voices)

unfortunately I'm not a programmer but, IMO, should be feasible to "grab
the browser language" and use the relative translation.

Thank you

Pierfrancesco

2016-12-28 14:36 GMT+01:00 Gilles Dubois <notifications@github.com>:
