### ISSUE TITLE
SNMP: Table 'ocsweb.DEVICE' doesn't exist 

### ISSUE THREAD

**Issue by Henri0404** [OCSInventory-NG/OCSInventory-Server#346]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
CentOS Linux 8

### Server informations
Perl version : v5.26.3
Mysql / Mariadb / Percona version :  10.3.28-1

### OCS Inventory informations
Ocs server version : 2.9.1

### Problem's description

Running SNMP discovery, just on row ended in OCS. Apache error messages:

DBD::mysql::st execute failed: Table 'ocsweb.DEVICE' doesn't exist at /usr/local/share/perl5/Apache/Ocsinventory/Server/Capacities/Snmp/Inventory.pm line 146.

[error_log.txt](https://github.com/OCSInventory-NG/OCSInventory-Server/files/7000591/error_log.txt)

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.
