### ISSUE TITLE
demo issue

### ISSUE THREAD

**Issue by agrosjea** [OCSInventory-NG/OCSInventory-Server#35]
After using login demo/demo on your website I get the folllowing error.

Catchable fatal error: Argument 1 passed to XMLUrlsSerializer::serialize() must be an instance of Urls, boolean given, called in /home/www/www_demo/html/require/config/include.php on line 57 and defined in /home/www/www_demo/html/require/config/XMLUrlsSerializer.php on line 29

**Comment by kapouik** [comment]
The demo have been update and now work correctly. We have identify the bug and will resolve it as soon as possible. 
Thanx for your report.
