### ISSUE TITLE
How to sync all agents

### ISSUE THREAD

**Issue by darjichirag235** [OCSInventory-NG/OCSInventory-Server#351]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Windows -10 

### Server informations
Perl version :  16
Mysql / Mariadb / Percona version :  15.1 Mysql

### OCS Inventory informations
Ocs server version : 2.8

### Problem's description
I want to Sync all agent with single click, and also remove duplicate agent entry.
And how increase server and agent comunication.

**Comment by gillesdubois** [comment]
Hi,

Agent communication interval can be changed with PROLOG_FRAG value in the general configuration.
We are not able to launch the inventory remotely due to our security restrictions on customer infrastructures. The agent is a pull mode only.

Regards,
Gilles.
