### ISSUE TITLE
[Feature] Add swagger contract for Rest Api

### ISSUE THREAD

**Issue by dust63** [OCSInventory-NG/OCSInventory-Server#354]
Modern application use swagger contract. https://swagger.io/specification/
Can you add this feature on OCS inventory.

**Comment by gillesdubois** [comment]
Hi,

We are currently working on a rework with an API Base framework. It'll provide Postman / Insomnia and Swagger API Specifications.

Regards,
Gilles.

**Comment by araqieldev** [comment]
Have you any idea of the release of the API documentation ?
