### ISSUE TITLE
v2.8.1 Vulnerability assessment : HttpOnly & Secure 

### ISSUE THREAD

**Issue by houssamoug** [OCSInventory-NG/OCSInventory-Server#357]
### General informations
Operating system : ubuntu 18.04

Server installation method 
- Docker image

### OCS Inventory informations
Ocs server version : 2.8.1

### Problem's description

- Possible Cross site scripting found
- Cookie(s) without HttpOnly flag set
- Cookie(s) without Secure flag set

It seems that it is fixed on https://github.com/OCSInventory-NG/OCSInventory-Server/issues/169 
but the problem persists on version 2.8.1

**Comment by gillesdubois** [comment]
Hey,

As far as I know these problems has been addressed in the 2.9 and not the 2.8.

Regards,
Gilles.
