### ISSUE TITLE
Record firewall state/config

### ISSUE THREAD

**Issue by jcpunk** [OCSInventory-NG/OCSInventory-Server#36]
Can OCS Inventory be extended to record the firewall state and configuration for UNIX (in particular Linux) systems as well as Windows hosts?

A few plugins exist here and there, but there isn't a cross platform solution.

**Comment by gillesdubois** [comment]
Hi,

You can retrieved these data using SNMP and custom MIBs.
SNMP scan is cross platform and can basically retrieve everything if you know how to create MIBs

Regards,
Gilles Dubois.
