### ISSUE TITLE
CPU > 300% . OCS Inventory 2.8 - Agents Versión 2.3.1 - 3000 agents

### ISSUE THREAD

**Issue by AllendeJavier** [OCSInventory-NG/OCSInventory-Server#361]
Good morning,

I've a problem with my OCS Inventory Server. I've migrate from version 2.3 to 2.8 but all the agents stills in 2.3.1. After that I've a lot of problems with the performance of the database 300% - 500% CPU with TOP . All the agents is in version 2.3.1.1. Any recommendations?? Migrate to 2.8 the agents and the migrate the server to the 2.8??

regards

**Comment by gillesdubois** [comment]
Hi,

The agent is not the cause.
We made several improvement with the 2.9.X we recommend you to update.

Regards,
Gilles.
