### ISSUE TITLE
Some tables do not exist

### ISSUE THREAD

**Issue by charruel1** [OCSInventory-NG/OCSInventory-Server#363]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 9.13

### Server informations
Perl version : perl 5, version 24, subversion 1 (v5.24.1)
Mysql / Mariadb / Percona version :  mysql  Ver 15.1 Distrib 10.1.48-MariaDB

### OCS Inventory informations
Ocs server version : 2.9.1

### Problem's description
*Describe your problem here*

After following the migration steps from version 2.6 to 2.9, the web is blank (it does not ask for username and password).
The apache log shows the following messages

DBD::mysql::st execute failed: Unknown column 'LEVEL' in 'field list' at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 185.
DBD::mysql::st fetchrow_hashref failed: fetch() without execute() at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 187.
DBD::mysql::st execute failed: Table 'ocsweb.snmp_types' doesn't exist at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 162.
DBD::mysql::st fetchrow_hashref failed: fetch() without execute() at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 164.
DBD::mysql::st execute failed: Table 'ocsweb.snmp_types' doesn't exist at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 162.
DBD::mysql::st fetchrow_hashref failed: fetch() without execute() at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 164.
DBD::mysql::st execute failed: Table 'ocsweb.snmp_types' doesn't exist at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 162.
DBD::mysql::st fetchrow_hashref failed: fetch() without execute() at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Capacities/Snmp.pm line 164.
DBD::mysql::st execute failed: Table 'ocsweb.software' doesn't exist at /usr/local/share/perl/5.24.1/Apache/Ocsinventory/Server/Inventory/Software.pm line 59.

**Comment by charleneauger** [comment]
Hi @charruel1 ,

There must have been a problem during your update.
In order to overcome this problem, we recommend that you run the sql update files from 2.6 (7022.sql) to 2.9.1 (7051.sql) which is located in /usr/share/ocsinventory-reports/ocsreports/files/update.

Best regards,
Charlene Auger

**Comment by charleneauger** [comment]
Hi,

Since there is no anwser, I'll now close the issue.

Regards,
Charlene.
