### ISSUE TITLE
Some SMBIOS fields are not sent to DB

### ISSUE THREAD

**Issue by drTr0jan** [OCSInventory-NG/OCSInventory-Server#37]
Fields _MMANUFACTURER_, _MMODEL_ and _MSN_ from BIOS group are not sent to DB.

Ex., I've an XML on the agent:
```
        <BIOS>
            <SMANUFACTURER>ALG soft</SMANUFACTURER>
            <SMODEL>To be filled by O.E.M.</SMODEL>
            <SSN>418393</SSN>
            <TYPE>Desktop</TYPE>
            <BMANUFACTURER>American Megatrends Inc.</BMANUFACTURER>
            <BVERSION>F15</BVERSION>
            <BDATE>10/23/2013</BDATE>
            <MMANUFACTURER>Gigabyte Technology Co., Ltd.</MMANUFACTURER>
            <MMODEL>B75M-D3H</MMODEL>
            <MSN>CG3380 03129</MSN>
            <ASSETTAG>Gigabyte Technology Co., Ltd.</ASSETTAG>
        </BIOS>
```
but some info doesn't exist in DB on a server:
```
root@localhost [ocsweb]> select SSN, MMODEL from bios where hardware_id=2025;
+--------+--------+
| SSN    | MMODEL |
+--------+--------+
| 418393 | NULL   |
+--------+--------+

```

OCSInventory-Server v.2.3 RELEASE

**Comment by drTr0jan** [comment]
It's need to remove _last_state_ file on an agent before upgrade the server.

**Comment by buhgalter** [comment]
Delete folder ocs in C:\ProgramData.
Problem is not solved

**Comment by drTr0jan** [comment]
**buhgalter**, have you runned ocsinventory.exe again after delete the folder?

**Comment by buhgalter** [comment]
Удалил агент, удалил в ProgramData, установил агент
может в каких то temp директориях может быть этот файл?

**Comment by buhgalter** [comment]
да агент 2.3.0.0

**Comment by drTr0jan** [comment]
**buhgalter**, do you have non-empty section `<BIOS><MMODEL>` in agent XMLs (`ocsinventory.exe /XML`)?

**Comment by buhgalter** [comment]
`        <BIOS>
            <SMANUFACTURER>System manufacturer</SMANUFACTURER>
            <SMODEL>System Product Name</SMODEL>
            <SSN>System Serial Number</SSN>
            <TYPE>Desktop</TYPE>
            <BMANUFACTURER>American Megatrends Inc.</BMANUFACTURER>
            <BVERSION>1407</BVERSION>
            <BDATE>06/09/2013</BDATE>
            <MMANUFACTURER>ASUSTeK COMPUTER INC.</MMANUFACTURER>
            <MMODEL>P8H61-M LX2 R2.0</MMODEL>
            <MSN>130814734202105</MSN>
            <ASSETTAG>Asset-1234567890</ASSETTAG>
        </BIOS>`

**Comment by buhgalter** [comment]
```
        <BIOS>
            <SMANUFACTURER>System manufacturer</SMANUFACTURER>
            <SMODEL>System Product Name</SMODEL>
            <SSN>System Serial Number</SSN>
            <TYPE>Desktop</TYPE>
            <BMANUFACTURER>American Megatrends Inc.</BMANUFACTURER>
            <BVERSION>1407</BVERSION>
            <BDATE>06/09/2013</BDATE>
            <MMANUFACTURER>ASUSTeK COMPUTER INC.</MMANUFACTURER>
            <MMODEL>P8H61-M LX2 R2.0</MMODEL>
            <MSN>130814734202105</MSN>
            <ASSETTAG>Asset-1234567890</ASSETTAG>
        </BIOS>
```

**Comment by buhgalter** [comment]
Пробовал останавливать службу, удалял только last_state и запускал снова

**Comment by drTr0jan** [comment]
@buhgalter I have the same problem on one PC.

**Comment by buhgalter** [comment]
@drTr0jan all PC ((

**Comment by buhgalter** [comment]
@drTr0jan Where is the function of parsing and adding to the database? In function_files.php?

**Comment by drTr0jan** [comment]
@buhgalter you sholud add to `Apache/Ocsinventory/Map.pm:108`:
```
       MMANUFACTURER => {},
       MMODEL => {},
       MSN => {},
```

**Comment by buhgalter** [comment]
@drTr0jan Added. It did not help.

**Comment by drTr0jan** [comment]
@buhgalter have you restarted the Apache service?

**Comment by buhgalter** [comment]
@drTr0jan Yes

**Comment by buhgalter** [comment]
So, аfter a long time they appeared. Thanks

**Comment by buhgalter** [comment]
@drTr0jan So, аfter a long time they appeared, but not all. Thanks
