### ISSUE TITLE
Inventory / All Software menu - No data available in table 

### ISSUE THREAD

**Issue by cp61** [OCSInventory-NG/OCSInventory-Server#372]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 8.11

### Server informations
Perl version :  v5.20.2
Mysql / Mariadb / Percona version :  Mysql Ver 5.5.62-0+deb8u1

### OCS Inventory informations
Ocs server version : 2.9.2

### Problem's description

When I go to the Inventory / All Software menu I only get the answer "No data available in table"

However when I consult each PC, in the Software tab I see all the installed applications

In my Mysql database, my Software table has many data

**Comment by charleneauger** [comment]
Hi @cp61 ,

Since 2.9, the all software page is populated by crontab. 
Have you run the crontab cron_all_software.php in /usr/share/ocsinventory-reports/ocsreports/crontab ?

If yes, do you have any errors in your apache log file ?

Best regards,
Charlene Auger

**Comment by cp61** [comment]
Bonjour Charlene, 

Merci pour ce retour, en effet c'est le crontab cron_all_software.php qui n'est pas activé.

En le lançant manuellement, les données sont bien présentes.

Pour le cron_all_software.php, pour qu'il soit automatique avez vous mis des paramètres particuliers dans le crontab en terme de d'execution ? (toutes les minutes ? heures ?) 

Merci

**Comment by charleneauger** [comment]
@cp61,

Nous conseillons d'exécuter la crontab deux fois par jour. 

Cordialement,
Charlène
