### ISSUE TITLE
CVE-Search menu missing

### ISSUE THREAD

**Issue by jpoggi** [OCSInventory-NG/OCSInventory-Server#375]
### General informations
Operating system : Ubuntu 20.04

### Server informations
Perl version : v5.16.3
Mysql / Mariadb / Percona version :  MariaDB 10.6.5 (official docker image)

### OCS Inventory informations
Ocs server version : 2.9 (official docker image)

### Problem's description
I can find the menu CVE from "Configuration > General configuration" on a fresh installation of OCS with Docker.

I've try 2.8 and 2.9 version, menu is simply missing.

**Comment by naccey** [comment]
Try this ;
Configuration > Server > ADVANCE_CONFIGURATION = ON
Visible ADVANCE_CONFIGURATION like below screenshot;

![CVE-search management](https://user-images.githubusercontent.com/15703383/169038397-571ec470-720f-429b-a9d2-1c9707ac041e.JPG)

**Comment by Lea9250** [comment]
Hi, 

The answer provided by @naccey is correct, I'll close the issue.

Regards,
Léa
