### ISSUE TITLE
LDAP connection : "User not registered"

### ISSUE THREAD

**Issue by molotovah** [OCSInventory-NG/OCSInventory-Server#376]
### General informations
Operating system : 
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

### OCS Inventory informations
PHP Version : 7.4.3
Web Server : Apache/2.4.41 (Ubuntu)
Database Server : MySQL (Ubuntu) version 8.0.27-0ubuntu0.20.04.1
Version OCSReports: 2.9.2

### LDAP Configuration
![KBJRpIk](https://user-images.githubusercontent.com/43416516/151839052-b778921d-6ca6-4d1b-955b-a47d5553f5a7.png)

### Problem's description
*It's impossible to login with an AD user. I've modified the AUTH Method from var.php file using option 2. 
Resolving my AD ip in the OCS Server works. Also tried with IP instead of domain name into "CONEX_LDAP_SERVEUR"
Would you please help ? Thanks*

**Comment by gillesdubois** [comment]
Hi,

We applied a lot of fixes on the new LDAP auth system.
Could you update to the 2.11.1 and try again ?

Regards,
Gilles.

**Comment by fabiointegra** [comment]
Hi everyone! Just to register...
Make sure: 
->  `php-ldap` is installed on server;
-> Extensions enabled in php.ini
/etc/php/8.1/apache2/php.ini (Ubuntu 20.04)
```
extension=ldap
extension=mysqli
extension=pdo_mysql
```

-> Filter LDAP (I'm using, and working - Docker and dedicated server)
CONEX_LDAP_FILTER1
&(memberOf=CN=OCS,OU=TI,DC=lab1.DC=local)
