### ISSUE TITLE
Error when try to connect to ocs server

### ISSUE THREAD

**Issue by ehermontesinos** [OCSInventory-NG/OCSInventory-Server#377]
### General informations
Operating system : Red Hat 7/8

### OCS Inventory informations
Ocs server version : OCS Server 2.8

### Problem's description
Hi,

I have a very large Linux server park (Red Hat 7/Red Hat 8), and we use the OCS Inventory tool to keep track of all the servers.
The version of the OCS Server is version 2.8.
The problem is that the agents that we have installed on the Linux servers have been installed through the corresponding repository, and when an update is made, we have verified that with version 2.9.x of the agent, it gives the following error

[Tue Feb  1 13:01:01 2022][info] Going to sleep for 35 second(s)
[Tue Feb  1 13:01:37 2022][error] Cannot establish communication : 400 Bad Request
[Tue 01 Feb 2022 01:01:37 PM WET] End of cron job (/sbin:/bin:/usr/sbin:/usr/bin)

Is it possible that this error is because the agent version is greater than the server version?

Thanks in advanced!

Regards

**Comment by charleneauger** [comment]
Hi @ehermontesinos ,

Yes, the server version must be equal or superior than the agent version. :-)

Best regards,
Charlene
