### ISSUE TITLE
Can you create a release please?

### ISSUE THREAD

**Issue by MikaelUrankar** [OCSInventory-NG/OCSInventory-Server#379]
latest release is 2.8.1 while you advertise 2.9.2 on your website, can you create a release on github please?

**Comment by gillesdubois** [comment]
Hi,

Releases are located on reports repository.
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases

Regards,
Gilles.

**Comment by MikaelUrankar** [comment]
Sure but it'll be easier for us (the FreeBSD project) if there was a release or a tag on this repository. There is the 2.8.1 tag for example.

Merci!
