### ISSUE TITLE
MACOS Monterrey [Thu Mar 17 11:57:12 2022][error] Invalid XML: not well-formed (invalid token)

### ISSUE THREAD

**Issue by klabacita** [OCSInventory-NG/OCSInventory-Server#382]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 20.04

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  MariaDB 10.x

### OCS Inventory informations
Ocs server version : 2.9.1

### Problem's description
*I have a MACOS Monterrey that I install the client, I didn't found any error during the installation, but checking the logs /var/log/ I found this message:

[Thu Mar 17 11:57:12 2022][error] Invalid XML: not well-formed (invalid token) at line 1679, column 19, byte 46867 at /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/XML/Parser.pm line 187.
XML::Simple called at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Network.pm line 106.
[Thu Mar 17 11:57:12 2022][error] Cannot submit XML! Abort...
[Thu Mar 17 11:57:37 2022][error] Invalid XML: not well-formed (invalid token) at line 1679, column 19, byte 46867 at /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/XML/Parser.pm line 187.
XML::Simple called at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Network.pm line 106.
[Thu Mar 17 11:57:37 2022][error] Cannot submit XML! Abort...
[Thu Mar 17 12:00:14 2022][error] Invalid XML: not well-formed (invalid token) at line 1679, column 19, byte 46867 at /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/XML/Parser.pm line 187.
XML::Simple called at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Network.pm line 106.
[Thu Mar 17 12:00:14 2022][error] Cannot submit XML! Abort...
[Thu Mar 17 12:02:47 2022][error] Invalid XML: not well-formed (invalid token) at line 1679, column 19, byte 46867 at /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/XML/Parser.pm line 187.
XML::Simple called at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Network.pm line 106.
[Thu Mar 17 12:02:47 2022][error] Cannot submit XML! Abort...

I try checking different options during the installation but I get the same error.

Any tips that could share to fix this?

Thanks for your support!!!

**Comment by gillesdubois** [comment]
Hi,

We released the 2.9.3 of the unix (and mac agent).
Could you try it ? https://github.com/OCSInventory-NG/UnixAgent/releases/tag/v2.9.3

Note : I'll close this issue since its not in the right repository please reopen in https://github.com/OCSInventory-NG/UnixAgent/

Regards,
Gilles.
