### ISSUE TITLE
Some client account info: TAG display LOST

### ISSUE THREAD

**Issue by naccey** [OCSInventory-NG/OCSInventory-Server#387]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 20.04.4 LTS

### Server informations
Perl version : perl 5, version 30
Mysql / Mariadb / Percona version :  MySQL Community Server - GPL version 8.0.20

### OCS Inventory informations
Ocs server version :  OCS Inventory informations Ocs server version :2.9.2

### Problem's description
*Describe your problem here*
Why some client account info: TAG display LOST
How can i fixit?

![TAG_LOST](https://user-images.githubusercontent.com/15703383/171554447-1b1cba30-8ebe-43c0-afe8-d1d50154aab1.JPG)

**Comment by Lea9250** [comment]
Hi @naccey ,

Could you check the activity.log of the server and trigger an inventory of one of these devices ?
Did the LOST tag appear with the first inventory or was it set to something else before ?

Regards,
Léa

**Comment by charleneauger** [comment]
Hi @naccey ,

Any news ?

Regards,
Charlene

**Comment by Lea9250** [comment]
Hi @naccey,

I'll close this issue since there was no answer. Feel free to reopen if needed.

Regards, 
Léa
