### ISSUE TITLE
Deadlock on local_groups and local_users tables 

### ISSUE THREAD

**Issue by wiltonsr** [OCSInventory-NG/OCSInventory-Server#388]
### OCS Inventory informations
Ocs server version: Docker Image v2.9.2

### Problem's description
My system has a large number of machines inventorying daily, around `110k`, after upgrading to `v2.9.2` Docker Image I got many errors `500`.

On logs I get:

```
DBD::mysql::db do failed: Deadlock found when trying to get lock; try restarting transaction at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Inventory/Update.pm line 103.
```

Analisying DB connections I get:

```mysql
MariaDB [ocsweb_prd]> show open tables where in_use>0;
+------------+--------------+--------+-------------+
| Database   | Table        | In_use | Name_locked |
+------------+--------------+--------+-------------+
| ocsweb_prd | local_groups |   1014 |           0 |
| ocsweb_prd | local_users  |    976 |           0 |
+------------+--------------+--------+-------------+
```

When I run the `SHOW PROCESSLIST` I get many output from the following queries:

```
DELETE FROM local_users WHERE HARDWARE_ID=12342;
DELETE FROM local_groups WHERE HARDWARE_ID=10842;
```

Maybe related with:

- https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/245ed07a9c97b366bd8c59d3587e0e45b4869db6
- https://github.com/OCSInventory-NG/OCSInventory-Server/commit/db17075363a39101c604410118f2db9e6733e6b5
- #360

**Comment by gillesdubois** [comment]
Hi @wiltonsr 

We are going to review all the pull requests when the team is back from holidays :)

Regards,
Gilles.

**Comment by gillesdubois** [comment]
Hi,

We made a lot of improvement with the 2.11.1 version on the database queries.
Could you try with the new version ?

Regards,
Gilles.

**Comment by wiltonsr** [comment]
Hello, @gillesdubois 

I'm sorry for not getting back to you sooner.

I tried again with `v2.12.2` and the issue persists.

Our workaround to prevent these errors was to change the agent to not send `local_users` and `local_groups` info and edit `Duplicate.pm` to ignore them, too.

Changing this line:

https://github.com/OCSInventory-NG/OCSInventory-Server/blob/37270536bf6dffc9db84ab14c02adb0ab3a0a32c/Apache/Ocsinventory/Server/Duplicate.pm#L267

To:

```perl
next if !$DATA_MAP{$_}->{delOnReplace} || !$DATA_MAP{$_}->{auto} || $DATA_MAP{$_}->{capacities} || $_ eq "local_users" || $_ eq "local_groups"; 
```

It's not a functional solution. Although it prevents the error, all info about `local_users` and `local_groups` are not inventoried.

I think we can reopen this issue. Let me know if you need me to provide more testing.

**Comment by wiltonsr** [comment]
Hello, @gillesdubois 

I'm sorry for not getting back to you sooner.

I tried again with `v2.12.2` and the issue was fixed.
