### ISSUE TITLE
Cannot access the build page, in the console

### ISSUE THREAD

**Issue by smansteel** [OCSInventory-NG/OCSInventory-Server#389]
I am fairly new to OCSInventory, and I installed a server. I am in the web panel and when I'm trying to build a client I connot access the page. It stays blank (cf screen cap), and every other page of the admin works...

![image](https://user-images.githubusercontent.com/59889389/172361178-10a8f2ba-efd2-47cc-a60d-c941262327cf.png)

I am stuck, do you have any idea of where this issue could come from ?

**Comment by gillesdubois** [comment]
Hi,

Could you try with the latest release ?
It seems like an old bug that had already been fixed.

Regards,
Gilles.
