### ISSUE TITLE
ocs inventory server does not update inventories

### ISSUE THREAD

**Issue by oscarbarraza** [OCSInventory-NG/OCSInventory-Server#391]
SO : Linux x86_64
Ver : 3.10.0-1062.18.1.el7.x86_64
instaled RAM : 31993 MB
free RAM free: 27383 MB
CPU : Intel(R) Xeon(R) Gold 6238 CPU @ 2.10GHz
Dist : CentOS Linux 7 (Core)

PHP : 7.3.31
Webserver : Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5 PHP/7.3.31 mod_perl/2.0.11 Perl/v5.16.3
DB : MariaDB Server version 10.3.22-MariaDB
OCSReports Ver: 2.9

For some time now our OCS server stopped updating the inventories and does not show new equipment, through manual installation the following log file is obtained:

==============================================================================
Starting OCS Inventory NG Agent on Tuesday, June 14, 2022 16:35:46.
AGENT => Running OCS Inventory NG Agent Version 2.1.1.1
AGENT => Using OCS Inventory NG FrameWork Version 2.1.1.1
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) succesfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files (x86)\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.1.1.1>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <PRUBASOCR-2022-06-14-10-08-40> and MACs <80:91:33:EA:BD:BD82:91:33:EA:BD:BD80:91:33:EA:BD:BC00:68:EB:36:25:2B80:91:33:EA:BD:BD> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <C:\ProgramData\OCS Inventory NG\Agent\cacert.pem>
	COM SERVER => Sending HTTP Post request to URL <http://X.X.X.X/ocsinventory>
	COM SERVER => HTTP Post response received <HTTP Status Code #200>
	COM SERVER => Cleaning cURL library
AGENT => Prolog successfully sent
SUPPORT => No support detected, Registration key : N/A
	AGENT => Prolog Frequency set to 10 hour(s)
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:01.

**Comment by gillesdubois** [comment]
Hi,

The agent log alone aren't enough to fix the issue.
Could you upload the activity.log and error_log of the server ?

Please anonymise sensible data before uploading these files.

Regards,
Gilles.

**Comment by Lea9250** [comment]
Hi @oscarbarraza,

Since there was no answer, I'll close the issue. Feel free to re open if needed.

Regards,
Léa
