### ISSUE TITLE
Ocs Server

### ISSUE THREAD

**Issue by Christ125dd** [OCSInventory-NG/OCSInventory-Server#394]
hello,
ocs inventory servers are compatible with windows ? I have problems with the installation under xampp

**Comment by charleneauger** [comment]
Hi @Christ125dd ,

No the server is not compatible with Windows.
You will find the compatibility matrix at this link : [Compatibility matrix](https://ocsinventory-ng.org/?page_id=1548&lang=en)

Best regards,
Charlene
