### ISSUE TITLE
Heavy DB and Network Load from blacklisted macaddr

### ISSUE THREAD

**Issue by EldoBam** [OCSInventory-NG/OCSInventory-Server#396]
### General informations
Operating system :  CentOS 7

### Server informations
Perl version :  5.16.3
Mysql / Mariadb / Percona version :  10.2.XXX

### OCS Inventory informations
Ocs server version : 2.9.2
Construct: 2 Frontend Server and 1 DB Server

### Problem's description

In a bigger environment, ~40k Clients. The inventory causes a heavy DB and network load.
2 FE Server 16 Cores cpu at 100%
1 DB Server 16 Cores at 100%

I already found a fix and created a pull request #395

**Comment by gillesdubois** [comment]
Hi @EldoBam 

We are going to review all the pull requests when the team is back from holidays :) 

Regards,
Gilles.
