### ISSUE TITLE
Motherboard Model is null

### ISSUE THREAD

**Issue by akong77** [OCSInventory-NG/OCSInventory-Server#397]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 20.04

### Server informations
Perl version : 5.30.0-9ubuntu0.2
Mysql / Mariadb / Percona version :  8.0

### OCS Inventory informations
Ocs server version : 2.10.0

### Problem's description
It's can't see motherboard model.It's show empty.How to fix it?
The agent version is 2.9.2. It's use show hardware information it's also can't see motherboard model.

**Comment by gillesdubois** [comment]
Hi,

Your report is a bit vague, is this happening on some PC or all PC are missing mb model ?

Could you generate an XML of the inventory and send it to us ?

Regards,
Gilles.

**Comment by gillesdubois** [comment]
Hi,

I'll now close this issue due to inactivity.

**Comment by nitmanby** [comment]
Yes. Does not display on all computers. agent version 2.10
