### ISSUE TITLE
WOL OCSInventory Docker Compose

### ISSUE THREAD

**Issue by ticmsbo** [OCSInventory-NG/OCSInventory-Server#398]
It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.

General informations
Docker host's operating system : Ubuntu Server 22.04 LTS
Mysql Server version : 8.0

Docker informations
Docker compose version : docker-compose version 1.29.2, build unknown
Docker version : Docker version 20.10.14, build a224086349

Problem's description
Ocs Docker Image is 2.10 with sudo docker-compose up -d command
The wake-on-lan and officepack plugin isn't working, I resolved another application WOL problem putting the proxy container in host network. Should I have to do the same here?

Thanks

**Comment by gillesdubois** [comment]
Hi,

Imo it seems more like a network related issue than a OCS one.
Indeed the magic packet sent by WOl won't got through default networking. You'll have to perform some fine tuning on the docker-compose / network configuration of the container in order to get WOL working.

Regards,
Gilles.
