### ISSUE TITLE
Import .csv files option not shown

### ISSUE THREAD

**Issue by Flix886** [OCSInventory-NG/OCSInventory-Server#399]
Serverinformation 
•	Linux x86_64
•	5.10.0-14-amd64
•	Debian GNU/Linux 11 (bullseye)
Software
•	PHP-Version : 8.1.8
•	Webserver : Apache/2.4.54 (Debian)
•	Datenbank-Server : Debian 10 version 10.3.34-MariaDB-0+deb10u1
•	Version OCSReports: 2.10.0
•	Linux x86_64
•	5.10.0-14-amd64
•	Debian GNU/Linux 11 (bullseye)
Software
•	PHP-Version : 8.1.8
•	Webserver : Apache/2.4.54 (Debian)
•	Datenbank-Server : Debian 10 version 10.3.34-MariaDB-0+deb10u1
•	Version OCSReports: 2.10.0

Hello,

the option to import a .csv-file isn't shown when i click on local import. The only thing i see is the mask to create an object. In the past the option was available. Can anybody help?

bg

![grafik](https://user-images.githubusercontent.com/85347568/183657318-bb7c9800-6629-48b3-83a3-7566f35032b8.png)

**Comment by gillesdubois** [comment]
Hi,

This feature has been removed due to security concern.
In order to inject inventory file I'll recommend to use the perl injector or powershell injector tool (available in binutils dir of this repository).

Regards,
Gilles.

**Comment by Flix886** [comment]
Ah ok, thank you. I will try it.
