### ISSUE TITLE
Outdated MANIFEST

### ISSUE THREAD

**Issue by nirgal** [OCSInventory-NG/OCSInventory-Server#4]
When "building" the package on Debian, we get these warnings during the "clean":

make[1]: Entering directory '(...)/Apache'
/usr/bin/perl "-MExtUtils::Manifest=fullcheck" -e fullcheck
Not in MANIFEST: Ocsinventory/Interface/Snmp.pm
Not in MANIFEST: Ocsinventory/Plugins.pm
Not in MANIFEST: Ocsinventory/Plugins/Apache.pm
Not in MANIFEST: Ocsinventory/Plugins/Modules.pm

I suppose you just need to update the list of files?

**Comment by gillesdubois** [comment]
Hello, Nirgal.

I will fix this as soon as possible.
Plus, Apache.pm and Modules.pm are still "WIP" that why i didn't add them to the MANIFEST
I will add all these files when my work will be done on Apache.pm and Modules.pm :)

Thx for your feedback.
