### ISSUE TITLE
Virtual Machines Not Showing up

### ISSUE THREAD

**Issue by yarlanda** [OCSInventory-NG/OCSInventory-Server#400]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
Ubuntu 22.04.1 LTS (Docker Image)

### Server informations
Perl version : v5.34.0
Mysql / Mariadb / Percona version :  mysql  Ver 8.0.30 for Linux on x86_64 (MySQL Community Server - GPL)

### OCS Inventory informations
Ocs server version : 2.10.0

### Problem's description

Basically I am trying to display all VMs Info from a Hyper-V host.
What I have done is right a powershell script that is going into the plugins folder.
This the resulted xml for each machine:

```
<VIRTUALMACHINES>
<NAME>SQ-DASHBOARD-01</NAME>
<STATUS>Operating normally</STATUS>
<SUBSYSTEM>Virtual Machine</SUBSYSTEM>
<VMTYPE>Generation2</VMTYPE>
<UUID>12345</UUID>
<VCPU>2</VCPU>
<MEMORY>1024</MEMORY>
</VIRTUALMACHINES>
```

When I do the inventory locally, the XML is filled with the above information.
But when I send the Information on the OCS Server, the information is not displayed in the Misc Section of Virtual Machines. The resulted XML when I download it from OCS does not contain that info as well.

In the temp directory I see that the information is there when the xml arrives.

Am I missing something about it?

**Comment by gillesdubois** [comment]
Hi,

Could you enable the DBI_PRINT_ERROR parameter in the z-ocsinventory-server.conf ? 
I want to check if there is no SQL error during the inventory.

Are you sure the data injected by your script are compliant with the MySQL table columns types ?

Also
