### ISSUE TITLE
Printer Serial number option not available in ocsinventory

### ISSUE THREAD

**Issue by Lamerrrr** [OCSInventory-NG/OCSInventory-Server#41]
Is there any option to get the serial numbers of the printers connected to a PC (via USB) within the software?

This option is very useful!
Transfer printers in GLPI turns into a complete ass.

**Comment by fbomj** [comment]
Hi,

Sorry for the delay of the answer. The serial number is retrieved by an agent. Which one do you use?

Regards
Frank
