### ISSUE TITLE
 I have a problem, unable to make API calls on my OCSInventory

### ISSUE THREAD

**Issue by iamfauzi16** [OCSInventory-NG/OCSInventory-Server#416]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 22.04

### Server informations
Perl version : v5.30.0
Mysql / Mariadb / Percona version :  10.3.37

### OCS Inventory informations
Ocs server version : 2.11.0

### Problem's description
*Describe your problem here*

I have a task to fetch information from my ocsinventory by using API. but I have difficulty configuring it. of the existing documentation is very minimal references.

the problem I'm facing right now when I follow the documentation the error is forbidden 403.
![image](https://user-images.githubusercontent.com/53123172/213069810-cd50a7cc-0533-478e-a002-60e2c1de5005.png)

can you help me to solve my problem?

Thank you

**Comment by charleneauger** [comment]
Hi @iamfauzi16 ,

By default, in the api conf file (`zz-ocsinventory-restapi.conf`) we required by ip.
Edit the conf file and comment `Require ip 127.0.0.1`, save and restart apache.

Best regards,
Charlene

**Comment by iamfauzi16** [comment]
This's work! thank yo @charleneauger
