### ISSUE TITLE
Combine Two Api

### ISSUE THREAD

**Issue by iamfauzi16** [OCSInventory-NG/OCSInventory-Server#417]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 22.04

### Server informations
Perl version : v5.30.0
Mysql / Mariadb / Percona version :  10.3.37

### OCS Inventory informations
Ocs server version : 2.11.0

### Problem's description
*Describe your problem here*

how to combine these two api?
1. http://myocsserver/ocsapi/v1/computers/listID

2. http://myocsserver/ocsapi/v1/computer/{ID}/{specificSection}

so I want to do data merging so that it can be read easily based on the device id

**Comment by iamfauzi16** [comment]
any updates ?

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
