### ISSUE TITLE
After update, agents failing and no computers shown in 'All Computers'

### ISSUE THREAD

**Issue by RenaeMacLeod** [OCSInventory-NG/OCSInventory-Server#419]
### General informations
Operating system : Ubuntu 22.04.2 LTS

### Server informations
Perl version : 5.34.0
Mysql / Mariadb / Percona version :  MariaDB 10.6.12

### OCS Inventory informations
Ocs server version : 2.11.1

### Problem's description
Updated the server from 2.4 to 2.11.1 and no new agent updates have happened since. I used the guide at https://wiki.ocsinventory-ng.org/03.Basic-documentation/Updating-the-server/. There were a lot of DB updates during the OCS server update but no errors were noted.

1. I found that no computers were listed in All Computers, but PHPMyAdmin showed the data was still there. I went to 'ocsreports/index.php' instead and indeed I see the computers. So there is something preventing them from showing up normally.
2. And more importantly, agents are not able to update. After turning error reporting on using OCS_Opt_DBI_Print_Error 1 I got something usable in the error.log (Unknown column Category_ID in field list). From what I've been able to dig up this has been fixed, I suspect between 2.4 and 2.11.1, but the database update did not catch this. I am not a DB guy so the one response I found telling the bug reporter to 'run the query' flew over my head.

I ran the install.php again in the hopes the DB would be fixed but no change to either issue.

Thanks for all your hard work and this great software package. I can't wait to get it running again!

Help me OCS, you're my only hope.

**Comment by RenaeMacLeod** [comment]
Agents are quite a range of versions and I see them hitting the log attempting to update, but the one I am testing with is 2.10.1.0.

**Comment by RenaeMacLeod** [comment]
Sadly no. Are you experiencing one of these issues or do you have a suggestion of something to try?

**Comment by RobertMiranda** [comment]
No, sorry. I am trying to find an open source asset management product and was recommended this one. When I saw you had no response for a couple of weeks I wanted to check if maybe you got support outside of Github from the project. This one looks like a better option with more active Github support. https://snipeitapp.com/product

**Comment by gillesdubois** [comment]
Hi @RobertMiranda @RenaeMacLeod 

I understand your frustration but please note that sometimes we have longer delay due  to our main work activities.
We try to answer as soon as possible our community, in the case you want to have timed answer with a SLA you can subscribe to our professional offer.

Just as a quick reminder, community is not equal to free support and maintenance. If you have an asset inventory project in your company, I recommend you to use the paid version of whatever OpenSource you'll be choosing to support the software and give you the insurance that everything will be fixed smoothly in timely schedules :) 

@RobertMiranda I personally don't mind recommending other software but its common sense to ask the repository owner before IMHO.

@RenaeMacLeod To answer your issue, 2.4 => 2.11 is basically a 8 year update in one shot, your CATEGORY_ID column missing can be solved by executing the following query : 

```
ALTER TABLE `hardware` ADD `CATEGORY_ID` int(11) default NULL AFTER `ARCH`;
```

In the future, I'll recommend to perform update when they comes out and not as one "big jump".

I remain available if you have any questions / trouble concerning this query.

Regards,
Gilles DUBOIS.

**Comment by RobertMiranda** [comment]
Thanks @gillesdubois. We are trying out your software as well as the one I suggested. Whatever option we choose, including neither of these options, the plan would be to get paid support. I like to support open source and that requires paying those that do the work. My intention was only to gauge the support received by @RenaeMacLeod.

**Comment by RenaeMacLeod** [comment]
@gillesdubois, thanks for that! It resolved both issues.

To your suggestion to update regularly, I had not used this for some time and have found a desire to go back to it. I did follow the recommended update procedure on the page noted above. I seem to remember reading either during the update process or on another page about which version jumps are and are not supported. I tried searching for the page just now without luck. Apololgies for not following the proper path if that's what happened. If there is a link you know of that shows which version jumps are supported for upgrading, please link me and I will save that for future reference, and others finding this page that have not started may use it for their upgrade.

Thanks again!

**Comment by charleneauger** [comment]
Hi @RenaeMacLeod ,

We didn't specify it in our documentation because as Gilles pointed out, we assume that users update regularly.
The initial problem being solved, I close the issue.

Best regards,
Charlene Auger
