### ISSUE TITLE
Map.pm reference a table "usbdevices" that does not exist in database

### ISSUE THREAD

**Issue by cadegenn** [OCSInventory-NG/OCSInventory-Server#42]
Under certain circumstances (that I did not lighten), it may lead to "duplicate;replacing_error" in log file resulting in duplicate host in database. Digging further I found that OCS Server try to delete old host informations according to Map.pm but declared table "usbdevices" does not exist, thus returning an error and stopping old host deletion.

I may not be clear, please ask me more information as needed.

**Comment by gillesdubois** [comment]
hi,

Your issue is already referenced here : https://github.com/OCSInventory-NG/OCSInventory-Server/issues/40

Thx for your contribution.

Regards,
Gilles Dubois.
