### ISSUE TITLE
Table 'ocs_db.DEVICE' doesn't exist !!!

### ISSUE THREAD

**Issue by bud4** [OCSInventory-NG/OCSInventory-Server#420]
### General informations
Operating system : CentOS Stream 8

### Server informations
Perl version : perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi
 Mariadb  version :  10.3.28

### OCS Inventory informations
Ocs server version : 2.9.2

### Problem's description
DBD::mysql::st execute failed: Table 'ocs_db.DEVICE' doesn't exist at /usr/local/share/perl5/Apache/Ocsinventory/Server/Capacities/Snmp/Inventory.pm line 146
Install from  OCSNG_UNIX_SERVER-2.9.2.tar.gz

Non snmp inventory data . Agent send data but no data on server
Could it depend on the xml sent by the client? 
Look down
`
[Wed Mar 22 12:11:35 2023][debug] sending: <?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <CARTRIDGES>
        <COLOR></COLOR>
        <DESCRIPTION>Imaging Unit</DESCRIPTION>
        <LEVEL>43200</LEVEL>
        <MAXCAPACITY>60000</MAXCAPACITY>
        <TYPE>other</TYPE>
      </CARTRIDGES>
      <CARTRIDGES>
        <COLOR></COLOR>
        <DESCRIPTION>Maintenance Kit</DESCRIPTION>
        <LEVEL>184000</LEVEL>
        <MAXCAPACITY>200000</MAXCAPACITY>
        <TYPE></TYPE>
      </CARTRIDGES>
      <CARTRIDGES>
        <COLOR></COLOR>
        <DESCRIPTION>Black Cartridge</DESCRIPTION>
        <LEVEL>1200</LEVEL>
        <MAXCAPACITY>6000</MAXCAPACITY>
        <TYPE>toner</TYPE>
      </CARTRIDGES>
      <COMMON>
        <CONTACT></CONTACT>
        <DESCRIPTION>Lexmark MS621dn version MSNGM.053.023 kernel 4.11.12-yocto-standard-0db82913aa9eda284d6d18102f00e414 All-N-1</DESCRIPTION>
        <IPADDR>172.30.10.36</IPADDR>
        <LOCATION></LOCATION>
        <MACADDR>78:8c:77:94:90:f1</MACADDR>
        <NAME>FARMA-10-36</NAME>
        <SNMPDEVICEID>51c3e5fd1da5218dc5c2e1435a32a4cd</SNMPDEVICEID>
        <TYPE>Printer</TYPE>
`

**Comment by bud4** [comment]
OCS AGENT is  > 2.8.1
Name         : ocsinventory-agent
Version      : 2.9.3
Rilascio     : 1.el8
Architecture : x86_64
Size         : 28 k
Sorgente     : ocsinventory-agent-2.9.3-1.el8.src.rpm
Repository   : epel

**Comment by charleneauger** [comment]
Hi @bud4 ,

Do you have other UNIX agents installed ?

Regards,
Charlene

**Comment by charleneauger** [comment]
Hi @bud4 ,

Please, disable SNMP scan from agent < 2.8.1 because the old SNMP scan is not compatible with server versions > 2.8.
The XML you provided in the issue description matches the old SNMP scan.

The SNMP scan feature requires SSL configuration to work.

Have you configured SNMP from `Configuration > SNMP configuration` ?

SNMP scan has been removed from Windows agent. Now scans are only performed by UNIX agents.

Best regards,
Charlene

**Comment by bud4** [comment]
@charleneauger 
Not linux agents less than 2.9 
SSL is active. In fact, the deployment is working.
SNMP is on .
![immagine](https://user-images.githubusercontent.com/14982949/229480938-852302a7-3a2e-4647-95c1-ba557051a8b9.png)
![immagine](https://user-images.githubusercontent.com/14982949/229481187-abb4005f-17ea-4f23-aa9e-5e8a8706f51c.png)
![immagine](https://user-images.githubusercontent.com/14982949/229481302-1cb7ae03-2789-43a1-a920-2a6e2f3a9e4a.png)
![immagine](https://user-images.githubusercontent.com/14982949/229481454-68bc1d97-2cd7-4ace-a349-d41bf6a374e1.png)

**Comment by bud4** [comment]
@charleneauger .
This is the log of ocsagent :
` <RESPONSE>NO_ACCOUNT_UPDATE</RESPONSE>
</REPLY>
';
[Mon Apr  3 13:12:17 2023][debug] =END=SERVER RET======
[Mon Apr  3 13:12:17 2023][debug] Calling handlers : `end_handler'
[Mon Apr  3 13:12:17 2023][debug] [download] Calling download_end_handler
[Mon Apr  3 13:12:17 2023][debug] [snmpscan] Calling snmp_end_handler
[Mon Apr  3 13:12:17 2023][info] [download] Beginning work. I am 4115059.
[Mon Apr  3 13:12:17 2023][info] [download] No more package to download.
[Mon Apr  3 13:12:17 2023][debug] [download] End of work...

`

**Comment by charleneauger** [comment]
@bud4 ,
Are these following log lines present (they are at the beginning of the aget log file) ?

```
[Mon Apr 3 14:07:16 2023][debug] [snmpscan] Calling snmp_start_handler
[Mon Apr 3 14:07:16 2023][debug] - Net::SNMP loaded
```

**Comment by charleneauger** [comment]
@bud4, if you want to scan multiple networks, you should set the SNMP_NETWORK like this `172.30.18.0/24, 172.30.81.00/24, 172.30.81.0/24, 172.30.76.0/24`.

If SNMP scanning is enabled on a machine, it runs on every inventory.
An Agent must be Ipdiscover elected (or forced manually) to be able to make SNMP scan.

**Comment by charleneauger** [comment]
@bud4 , can i close this issue ? :)

**Comment by bud4** [comment]
@charleneauger  . Yes ! Tanks a lot.
