### ISSUE TITLE
Setup.sh fails with "cannot stat 'ocsreports/*': No such file or directory"

### ISSUE THREAD

**Issue by paramazo** [OCSInventory-NG/OCSInventory-Server#424]
### General informations
Operating system : Debian 12 (bookworm)

### Server informations
Perl version : 5.36.0
Mariadb version :  10.11

### OCS Inventory informations
Ocs server version : current master

### Problem's description
> +----------------------------------------------------------+
> |      Installing files for Administration server...       |
> +----------------------------------------------------------+
> 
> Creating PHP directory /usr/share/ocsinventory-reports/ocsreports.
> Copying PHP files to /usr/share/ocsinventory-reports/ocsreports.
> *** ERROR: Unable to copy files in /usr/share/ocsinventory-reports/ocsreports, please look at error in /home/
> tester/git/OCSInventory-Server/ocs_server_setup.log and fix !
> 
> Installation aborted !
>

**Comment by charleneauger** [comment]
@paramazo ,

If you want to install OCS, you must go through the following release archive https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/download/2.11.1/OCSNG_UNIX_SERVER-2.11.1.tar.gz and follow the installation documentation : http://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server/

Regards,
Charlene

**Comment by charleneauger** [comment]
You have the same error with the release archive ?

**Comment by charleneauger** [comment]
Can you provide me with the `ocs_server_setup.log` file info ?

**Comment by charleneauger** [comment]
The OCSInventory-Server repository is released with the OCSInventory-Reports repository.
I understand it's a bit confusing.

**Comment by charleneauger** [comment]
@paramazo, what do you mean by "magic" ?
