### ISSUE TITLE
index.php update only when logoff

### ISSUE THREAD

**Issue by cesko446** [OCSInventory-NG/OCSInventory-Server#43]
### General informations
Operating system : debian

### Server informations
Perl version : last 
Mysql / Mariadb / Percona version :  Mysql 5.5

### OCS Inventory informations
Ocs server version : 2.3

### Problem's description
All is running good except counters in the main page (index.php) i mean if i add a new computer installing one new agent i see it in "all computers" section but to see counters updated in the main page i have to logoff login

Do you know why?

**Comment by gillesdubois** [comment]
Hi,

All problems related to the webconsole must be posted in ocsinventory-ocsreports and not ocsinventory-server repo.

The dashboard data are saved in sessions that why you need to log out and log in again to refresh data.
I think we can add this add an enhancement are refresh data on page loading and not on log in / log out :)

Regards,
Gilles Dubois.
