### ISSUE TITLE
Rest API  Get last updated computers returning a 404 response

### ISSUE THREAD

**Issue by COUNTZERO-DEV** [OCSInventory-NG/OCSInventory-Server#437]
### General informations
Operating system : Windows 10

### Server informations
Perl version :Mysql
Mysql / Mariadb / Percona version :  

### OCS Inventory informations
Ocs server version :2.9

http://wiki.ocsinventory-ng.org/11.Rest-API/GET-Routes/

### Problem's description

Rest API GET route `ocsapi/v1/computers/lastupdate/172800` is returning a 404 response. Is there any configuration needs to be done?

Please advise.

**Comment by charleneauger** [comment]
Hi @COUNTZERO-DEV ,

The `lastupdate` route is available from server version 2.11. 

Best regards,
Charlène Auger

**Comment by COUNTZERO-DEV** [comment]
@charleneauger Thank you!
