### ISSUE TITLE
Upgrade from 2.11.0 to 2.12.0 Lost Static and Dinamic group

### ISSUE THREAD

**Issue by bud4** [OCSInventory-NG/OCSInventory-Server#438]
### General informations
Operating system :  CentOS Stream release 8

### Server informations
Perl version :
Mysql / Mariadb / Percona version :  

### OCS Inventory informations
Ocs server version   :2.12.0 

### Problem's description
After update i lost all dinamic and static group.

**Comment by Lea9250** [comment]
Hi @bud4,

Saw you posted a similar issue on the ocsreports repository. You seemed to have fixed your issue, should we close this one too ?

Regards,
Léa

**Comment by bud4** [comment]
yes ! Close !
Sorry.
----------------------------------------------------------------

*«L'immaginazione è più importante della conoscenza.» - Albert Einstein.*



*Alberto M.Fiaschi*



*http://it.linkedin.com/pub/alberto-fiaschi
<http://it.linkedin.com/pub/alberto-fiaschi/38/783/a5> *


Il giorno mar 19 set 2023 alle ore 14:03 Lea9250 ***@***.***>
ha scritto:
