### ISSUE TITLE
Message d'erreur lors d'export CSV

### ISSUE THREAD

**Issue by yeawyn** [OCSInventory-NG/OCSInventory-Server#44]
Bonjour,

lorsque nous voulons effectuer un export des informations dans "ALL COMPUTERS", nous avons le message suivant lorsque nous cliquons sur "Download" : 
ERROR, the requested doesn't exists.

Quand nous allons regarder le error.log de Apache, nous voyons ceci :
[Thu Feb 09 15:49:37.843710 2017] [:error] [pid 27861] [client] PHP Warning:  Invalid argument supplied for foreach() in /var/lib/ocsinventory-reports/plugins/main_sections/ms_export/ms_csv.php on line 46, referer: http://@IP/ocsreports/index.php?function=visu_computers

[Thu Feb 09 15:49:37.848237 2017] [:error] [pid 27861] [client] PHP Warning:  Invalid argument supplied for foreach() in /var/lib/ocsinventory-reports/plugins/main_sections/ms_export/ms_csv.php on line 93, referer: http://@IP/ocsreports/index.php?function=visu_computers

Pour informations, notre version d'OCS serveur est la 2.3.0 révision 1.el7.ocs

Merci d'avance pour le retour

### General informations
Operating system : CentOS

### Server informations
Mariadb

### OCS Inventory informations
Ocs server version :  2.3

**Comment by gillesdubois** [comment]
Bonjour,

Les problèmes de l'interface web doivent être crée dans le "OCSInventory-ocsreports" et non "OCSInventory-server"

Le problème a déjà été résolu, veuillez consulter ce lien pour plus d'information : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/199

Voici le patch a appliquer pour que l'export CSV re-fonctionne de nouveau : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/54da744fcd216c347858f016e1ab6293723aed78

Cordialement,
Gilles Dubois.

**Comment by yeawyn** [comment]
Bonjour,

Sincèrement désolé pour cette erreur de catégorie !

Par ailleurs, merci pour votre retour, le patch a effectivement résolu le problème.

Bien cordialement,
