### ISSUE TITLE
IpDiscover does not find machines on the network

### ISSUE THREAD

**Issue by cairoapcampos** [OCSInventory-NG/OCSInventory-Server#449]
### General informations
Operating system : Linux Debian 12

### Server informations
Perl version : 5.36.0
Mariadb: 10.11.4

### OCS Inventory informations
Ocs server version : 2.12.1

### Problem's description

I create the subnet by following the steps below in the web interface:

Manage -> Network scan -> Administer subnet -> ADD.

I run the following command on the VM that has the OCS Server and the OCS Agent:

```
perl ipdiscover-util.pl -network=192.168.2.0/24 -scantype=nmap -h=localhost  -d=ocsdb -u=ocsuser -p=ocspass
```

**Command output:**

![output](https://github.com/OCSInventory-NG/OCSInventory-Server/assets/21186839/dcb572b5-31f5-43fe-8b55-3cde200d6cf2)

I noticed that without executing the command no machines are listed. From what I saw in the documentation, some machines that have an agent are elected and scan the network. In my tests, no machine was automatically found by IpDiscover. 

I'm using virtualbox to test OCS. The VM with IP 192.168.2.2 is the OCS Server. The gateway 192.168.2.1 does not exist. The machines are on the same network. Could this be the problem? Can you help me?

**Comment by cairoapcampos** [comment]
Additional screens as per previous example:

![out1](https://github.com/OCSInventory-NG/OCSInventory-Server/assets/21186839/04b3d30e-ded1-493e-91f3-b17b9db424ab)
![out2](https://github.com/OCSInventory-NG/OCSInventory-Server/assets/21186839/cd448134-82fd-4263-87d2-9069e4ebefe4)
![out3](https://github.com/OCSInventory-NG/OCSInventory-Server/assets/21186839/69a4c232-c0e0-4a84-ac9c-8a166a47d166)

**Comment by gillesdubois** [comment]
Hi @cairoapcampos 

First, I see you are testing OCS in a virtual / test environement, that might be  the reason why you don't have automatic election. Possible reasons are multiple but if you have a infrastructure with agent you trigger from time to time to test, they won't be elected as IPDiscover agent.

OCS need the agent to come regularly to be elected, that's what we call the fidelity score. My first question abou the non election would be :

- Is IPDiscover enabled in the configuration ? 
- Are your test agent running regularly and not VM that are basically down most of the time ? 
- Are you running the agent with the service (at least for windows agent)
- You can also force a agent to scan a network in the machine detail > configuration > network scans, did you try that ? 

Concerning the script and the output in the webconsole there is two tabs : 
- Inventoried is meant to show computers that have an agent 
- Non Inventory is meant to show computers that don't have an agent

The main issue you encounter is that the 192.168.2.2 machine is reconciliated with its agent entry. This behavior can be normal as the IPDiscover script is more intended to be used in network where there is no agent (network full of net devices for example).

Regards,
Gilles DUBOIS.

**Comment by Lea9250** [comment]
Hi @cairoapcampos ,

"Non-inventoried" is pretty much self-explanatory, these are devices that do not have an OCS agent installed. "IpDiscover" refers to Ipdiscover elected devices, i.e. agent's performing the ipdisover scan.

Regards,
Léa
