### ISSUE TITLE
OcsLogon.exe missing in Archive of Windows Agent

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [OCSInventory-NG/OCSInventory-Server#45]
### OCS Inventory informations
Ocs server version :  2.3

### Problem's description
The wiki [(klick)](http://wiki.ocsinventory-ng.org/index.php?title=Documentation:WindowsAgent#OCS_Inventory_NG_Agent_2.0_on_Windows_Operating_Systems.) is telling:  

> Download and unzip the latest Windows agent from the Downloads section. This package contains 2 files: 

Unfortenately is OcsLogon.exe missing in the Archiv which is provided to download at https://github.com/OCSInventory-NG/WindowsAgent/releases/download/2.3/OCSNG-Windows-Agent-2.3.0.0.zip

**Comment by gillesdubois** [comment]
Hi,

Please, in the future create your windows agent related issues here : https://github.com/OCSInventory-NG/WindowsAgent

We are aware of the problem and we will put it in the archive soon :) 
In the mean time you can use the old releases ocsLogon.exe

Regards,
Gilles Dubois.

**Comment by vollkommenIrrelevant** [comment]
Thank you for your attention!

**Comment by gillesdubois** [comment]
@vollkommenIrrelevant ,

https://github.com/OCSInventory-NG/WindowsAgent/releases/download/2.3/OCSNG-Windows-Agent-2.3.0.0.zip

OcsLogon.exe should be there :)
