### ISSUE TITLE
Database server requirements mismatch on documentation

### ISSUE THREAD

**Issue by RomBrz** [OCSInventory-NG/OCSInventory-Server#453]
Hi, i'm reading the documentation for OCS and i found some informations mismatched about database requirements:

One page says that should be MySQL 4.1.0 or higher, BUT not work with 5.5 and upper.
> "MySQL or MariaDB version 4.1.0 or higher with InnoDB engine active. Mysql version upper than 5.5 are not supported but may work."
https://wiki.ocsinventory-ng.org/01.Prerequisites/Libraries-version/

Another page says that should be MySQL 5.4 or higher.
> Database server currently can only be MySQL 5.4 or higher.
https://wiki.ocsinventory-ng.org/03.Basic-documentation/Deploying-database-server/

I have an old 2.9 standalone server (app + database), and i want to make a new installation of OCS server 2.11 (no migration) using container + remote database, and have right now a MySQL 5.7 already installed and available to use. By link 1 i cannot use it, by link 2 i could.

Thanks!

**Comment by gillesdubois** [comment]
Hi,

The documentation will have a rework soon as some info are a bit outdated.

We recommend Mysql 8.0+ and Mariabd 10.3+ in order to be compatible and have the latest security fixes.

Regards,
Gilles DUBOIS.
