### ISSUE TITLE
WARNING *** COM SERVER => Failed to send HTTP Post request <Problem with the SSL CA cert (path? access rights?)>

### ISSUE THREAD

**Issue by Gambware** [OCSInventory-NG/OCSInventory-Server#46]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Windows 10

### Server informations
Perl version : v5.18.2
Mysql / Mariadb / Percona version :  MYSQL

### OCS Inventory informations
Ocs server version : 2.3

### Problem's description
*Describe your problem here*

After expire my SSL Certificate, I create a new one and re-deploy to my computers. 
Now the agent can't connect with OCS-Server

==============================================================================
Starting OCS Inventory NG Agent on Wednesday, February 22, 2017 15:06:56.
AGENT => Running OCS Inventory NG Agent Version 2.1.1.1
AGENT => Using OCS Inventory NG FrameWork Version 2.1.1.1
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) succesfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files (x86)\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.1.1.1>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <CMPSP1NB003-2017-02-15-09-35-04> and MACs <B8:88:E3:DC:65:1100:60:73:6C:CC:3C74:E5:43:16:C4:BC74:E5:43:16:C4:BC44:6D:57:87:29:7D02:50:41:00:00:0100:05:9A:3C:78:0054:72:F8:EE:51:0600:FF:D3:29:5B:C554:B4:39:07:55:0402:00:4C:4F:4F:50> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <C:\ProgramData\OCS Inventory NG\Agent\companyname2017.pem>
	COM SERVER => Sending HTTP Post request to URL <https://ocs.companyname.com.br/ocsinventory>
	WARNING *** COM SERVER => Failed to send HTTP Post request <Problem with the SSL CA cert (path? access rights?)>
	COM SERVER => Cleaning cURL library
================= TRACE START ===============

================= TRACE STOP ===============
ERROR *** AGENT => Failed to send Prolog <Problem with the SSL CA cert (path? access rights?)>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:02.

**Comment by Gambware** [comment]
My cert was created by the following command

openssl req -new -days 3650 -nodes -out /etc/apache2/companyname2017.pem

After that I send this certificate to be signed by Active Directory. I Change the certificate on the Apache and put the same certificate on the OCS-Agent folder.

**Comment by gillesdubois** [comment]
Hi,

Have you named your certificate properly and updated your ocsinventory.ini on the agent ?
Did you take a look at this issue, curl behavior on ssl is different on windows and can lead to ssl verification fails : https://github.com/OCSInventory-NG/WindowsAgent/issues/31

Regards,
Gilles Dubois.
