### ISSUE TITLE
Help! OCS Inventory all software Empty

### ISSUE THREAD

**Issue by jgaribaldo5** [OCSInventory-NG/OCSInventory-Server#468]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 22.04

### Server informations
Perl version : v5.34.0
Mysql / Mariadb / Percona version :  Mariadb 10.6.18

### OCS Inventory informations
Ocs server version : 2.12.3

### Problem's description
Hi,
Recently I installed OCS Inventory server 2.12.3 without any troubles, but after adding agents either with deployment tool or manual install on local machine, tab "All software" is empty. 

![image](https://github.com/user-attachments/assets/dc7a6147-50b5-467d-aa25-000b0d945ac6)

Reading the OCS Inventory forum, it was recommended to manually run the task to load the information of all the software collected by the agents. However, I encountered the following error.

![image](https://github.com/user-attachments/assets/4ee9e00c-fcf6-4e28-b736-1b66e6040654)

*********************************
# /bin/php /usr/share/ocsinventory-reports/ocsreports/crontab/cron_all_software.php
PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_report() in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php:171
Stack trace:
#0 /usr/share/ocsinventory-reports/ocsreports/crontab/cron_all_software.php(10): dbconnect()
#1 {main}
  thrown in /usr/share/ocsinventory-reports/ocsreports/require/function_commun.php on line 171
*****************************

I appreciate the support you can give me.
Regards,

**Comment by Lea9250** [comment]
Hi @jgaribaldo5 

Which PHP version are you currently running? Have the necessary PHP modules been installed, particularly php-mysql?

Regards,
Léa

**Comment by jgaribaldo5** [comment]
hi,
I'm running PHP 8.4 and the php-mysql module is installed.
![image](https://github.com/user-attachments/assets/2baff2ac-a9cb-4daa-9ed3-8ba7addcdaff)

**Comment by jgaribaldo5** [comment]
Hello, perform a new clean installation and log in to enable the crontab that updates the list of all programs,

![image](https://github.com/user-attachments/assets/8d97afa5-b6aa-49f7-9fe6-d3b267bc5522)
