### ISSUE TITLE
Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE)

### ISSUE THREAD

**Issue by nntu** [OCSInventory-NG/OCSInventory-Server#5]
[Mon Jun 15 16:11:48 2015] -e: DBD::mysql::db do failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Server/Inventory/Cache.pm line 34.
[Mon Jun 15 16:11:48 2015] -e: DBD::mysql::db do failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Server/Inventory/Cache.pm line 34.
[Mon Jun 15 16:11:48 2015] -e: DBD::mysql::db do failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Server/Inventory/Cache.pm line 34.
[Mon Jun 15 16:11:48 2015] -e: DBD::mysql::db do failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Server/Inventory/Cache.pm line 34.
[Mon Jun 15 16:11:48 2015] -e: DBD::mysql::db do failed: Illegal mix of collations (latin1_

**Comment by kapouik** [comment]
cannot be reproduce
