### ISSUE TITLE
Version 2.3.0.0 with bug in duplicate computer

### ISSUE THREAD

**Issue by fgendorf** [OCSInventory-NG/OCSInventory-Server#50]
### General informations
Operating system : Centos 6.6 x86_64

### Server informations
Perl version : v5.10.1
Mysql / Mariadb / Percona version :  Mysql 5.7.17

### OCS Inventory informations
Ocs server version : 2.3.0.0

### Problem's description
Hi, after upgraded to 2.3.0.0 a lot of computers start to get duplicated I can't find the solution.
The activity.log just appear:

OCS-NG_WINDOWS_AGENT_v2.3.0.0;duplicate;replacing_error

thanks for advance

**Comment by zufflaur** [comment]
for me it's the same problem. Many computers duplicate
Debian 8.7, OCS Inventory 2.3

**Comment by gillesdubois** [comment]
Hi @fgendorf ,

Thanks for your report. Look like a query error ( might come from your mysql server ).
I will install a server with the same configuration as yours and try to reproduce your problem.

Regards,
Gilles Dubois.

**Comment by ameurou** [comment]
Hi @gillesdubois,

Same problem with mysql 5.5.52-0ubuntu0.14.04.1. Just after the upgrade computer start being duplicated.

**Comment by ameurou** [comment]
Hi,

I add some extra debug on duplicate.pm to see witch duplicate_replace() action is causing the error.

For all computer being duplicated, the return(1) is throw by this code : 

https://github.com/OCSInventory-NG/OCSInventory-Server/blob/bf97de0a6b1ec136acbb39873e8b9b38e7246fc7/Apache/Ocsinventory/Server/Duplicate.pm#L258-L266

**Comment by ameurou** [comment]
OK, I think i found it.

Usbdevices table is missing in DB, maybe something goes wrong in 2.3 update... 

This commit https://github.com/OCSInventory-NG/OCSInventory-Server/commit/73827cd054a5067c35169caf2c211d1cccf08cd8 add the usbdevices in MAP and as the table is missing delete request failed...

@fgendorf @zufflaur can you confirm that you don't have usbdevices table ?

**Comment by ameurou** [comment]
And so this should be resolve by update 2.3.1 as sql update script 7011 is adding usb devices table :-)

**Comment by fgendorf** [comment]
Hi, last week I updated to version 2.3.0.1 and the duplicate errors seem to be solved:
Fri Mar 17 08:19:33 2017;5348;300;FLCAEWS028-2017-03-17-08-19-00;10.0.0.197;OCS-NG_WINDOWS_AGENT_v2.3.0.0;duplicate;13890 => 13896

I just checked and in version 7011 the table usbdevices is there

Thanks

**Comment by drTr0jan** [comment]
@ameurou I have an _usbdevices_ table and  a duplicate error. :(
OCSServer 2.3.1

**Comment by ameurou** [comment]
Do you mean a duplicate error in the activity.log file ?

I've check on my OCS Server log file and so far, i don't got any more duplicate error in log. I setup AUTO_DUPLICATE_LVL with hostname and serial and duplicate entries are properly merged as it was with 2.2...

**Comment by drTr0jan** [comment]
Nope. I mean AUTO_DUPLICATE doesn't work with AUTO_DUPLICATE_LVL = hostname + uuid.
There're not an errors in activity.log file. But a new hosts are created instead merging existent.

**Comment by ameurou** [comment]
Ok, so this is an other problem...

I think this issue can be closed and tag as solved with 2.3.1 and your issue #49 should be reopen !
