### ISSUE TITLE
timetable for next release?

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-Server#51]
Is there a timetable for the next release?
is nearly impossible to use ocs as an inventory system if the half of our linux client can´t send a successful inventory.
Talking about this: https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/8debb5318702b9adc91a0a5df6cf4a7a7ba6d92e

Alternatively can you give me a hint where i can fix this in my installation?

**Comment by gillesdubois** [comment]
Hi @scifire91 ,

A new version will be released really soon, we are aware of the 2.3 problems and are working atm on a minor release.
I can't give you a release date but execpt if within 2 weeks :)

Regards,
Gilles Dubois.

**Comment by scifire91** [comment]
Thanks for the information :)
