### ISSUE TITLE
Uninstall plungins delete plugins folder

### ISSUE THREAD

**Issue by totorux** [OCSInventory-NG/OCSInventory-Server#53]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian jessie

### Server informations
Perl version : v5.20.2
Mysql / Mariadb / Percona version : 5.5.54-0+deb8u1

### OCS Inventory informations
Ocs server version : 2.3

### Problem's description
When I uninstall a OCS plugins, OCS delete the folder:
/etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins

So when next you try to install a plugins you have Err_04 : Can't write in perl directory ( by default -> /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins 
And you need to recreat the folder.
So this break all other plugins, who need to be installed again.

**Comment by gillesdubois** [comment]
Hi,

This bug has been corrected :) 
Thanks for your report.

Check out this link for more informations : https://github.com/OCSInventory-NG/OCSInventory-Server/commit/b9eeb850bd144f4cd62196fee1fb3974a15311c9

Regards,
Gilles Dubois.
