### ISSUE TITLE
VMs not shown correctly

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-Server#56]
### General informations
Operating system : Ubuntu 4.4.0-67-generic

### Server informations
Perl version : 5.22.1
Mysql version :  5.7.17-0ubuntu0.16.04.1

### OCS Inventory informations
Ocs server version : 2.3.1

### Problem's description
OCS maps the virtual machines to the host systems, which is a very nice and powerful feature.
Unfortunately it isn´t working correct if we have the vms on multiple hosts (only on one host running) .
On the host that runs the vm i don´t see the name or any information about the vm, i see only that it is running. 
If the vm is tunred off i see the name, uuid, memory and processor of the vm.

So in our case the runnig vm is mapped to the wrong host cause ocs see the vm only on the on which the vm is turned off. 

I don´t now if it´s possible to fix this, but it would be very nice. 

Attached some screenshots:
VM is mapped to the wrong vhost
![image](https://cloud.githubusercontent.com/assets/17220258/24696136/b6fef802-19e8-11e7-9ebf-fce1632fd6b2.png)
Some vms are running on the host but i don´t see any information about them
![image](https://cloud.githubusercontent.com/assets/17220258/24696234/0f1efeba-19e9-11e7-93e2-071a3257c258.png)
as you can see vm is turned off on this host, and now i can see some information about it
![image](https://cloud.githubusercontent.com/assets/17220258/24696298/491cc444-19e9-11e7-8e41-834ab9489a69.png)

**Comment by ArulrajAnto** [comment]
Hi all,

 i am also facing the same issue on both version 2.2.1 and 2.3.1. Please help me to get the operating system details,

![image](https://user-images.githubusercontent.com/24372583/28819261-4446afae-76cb-11e7-93b8-1d485cb29e94.png)


![image](https://user-images.githubusercontent.com/24372583/28819411-c7637642-76cb-11e7-9484-54c9fc09e279.png)

**Comment by mfuhrmann** [comment]
Would be great to have this feature working. Any chance to push this?

**Comment by scifire91** [comment]
For us this was fixed with https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/tag/2.4.1
