### ISSUE TITLE
Local import from *.ocs files doesn't work

### ISSUE THREAD

**Issue by fgendorf** [OCSInventory-NG/OCSInventory-Server#57]
### General informations
Centos 6.9

### Server informations
Perl version : v5.10.1
Mysql / Mariadb / Percona version :  
Mysql 5.7.17

### OCS Inventory informations
Ocs server version : 2.3.0.1

### Problem's description
Hi, I think since I upgraded to version 2.3 the local import doesn't work anymore, I went to Manage -> import Local and chose the file .ocs, when I click send and message appear in a red box:

Error HTTP/1.1 403 Forbidden

The same thing occur using ocsinventory-injector.pl

[root@flinsvm006 ~]# ./ocsinventory-injector.pl -d . -u http://ocs.fln.esss.com.br/ocsinventory -r -v
Loading ./flinssv013-2017-04-04-18-21-10.ocs...ERROR: 403 Forbidden
Loading ./flinssv012-2017-04-07-12-26-24.ocs...ERROR: 403 Forbidden
Loading ./flinssv014.fln.esss.com.br-2017-02-10-11-52-35.ocs...ERROR: 403 Forbidden
Loading ./spinssv004.sp.esss.com.br-2016-12-27-17-49-39.ocs...ERROR: 403 Forbidden
Loading ./rjinssv006.fln.esss.com.br-2016-06-18-13-29-27.ocs...ERROR: 403 Forbidden

How can I trace the error? no message is showed in apache logs or ocs activity.log

Thanks for advance

**Comment by fgendorf** [comment]
Import local from ocsreports results same error, and log activity reports:

Fri May 12 19:28:50 2017;28566;318;FLINSVM011-2014-06-04-16-40-12;10.0.0.27;OCS_local_7011;session;missing
Fri May 12 19:28:50 2017;28566;114;FLINSVM011-2014-06-04-16-40-12;10.0.0.27;OCS_local_7011;inventory;no_session
Fri May 12 19:28:50 2017;28566;115;FLINSVM011-2014-06-04-16-40-12;10.0.0.27;OCS_local_7011;inventory;refused

**Comment by fgendorf** [comment]
Fixed:
the problems is in file /usr/local/share/perl5/Apache/Ocsinventory/Server/Inventory/Update/Hardware.pm on SQL on line 49

**Comment by gillesdubois** [comment]
Hi,

I just tested on my server and it's working : 
```
root@srv-ocs-glpi-dev-trunk:~/OCSInventory-Server/binutils# perl ocsinventory-injector.pl --url http://172.18.26.10/ocsinventory -d ocs_files/  --verbose
Loading ocs_files//USER-PC-2017-09-05-11-43-20.ocs...OK
```

I don't understand what you exactly fixed ?
Are you sure your problem is not related to the file your are sending?

Regards,
Gilles Dubois.

**Comment by manuelhinfante** [comment]
I had the same issue, but I fixed it executing the follow command [ root@yourserver:/home/user# perl /home/minfante/ocsinventory-injector.pl -u http://127.0.0.1/ocsinventory -v -f /home/user/ocs/file.ocs  ] note  that I put the server on 127.0.0.1 and not  localhost, dns or ip address. I can presume that 127.0.0.1 (localhost) is justly like configured on config file for apache and ocsinventory for the http or something else permission attributes
