### ISSUE TITLE
OCSLogon - SendRequest Error: Failed downloading file !

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [OCSInventory-NG/OCSInventory-Server#58]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 16.04 / Windows 7

### Server informations
Perl version : 7
Mysql / Mariadb / Percona version :  14.14

### OCS Inventory informations
Ocs server version : 2.3.0.1

### Problem's description

- Starting OCSLogon from cmd: `C:\Users\asdf\Desktop>OcsLogon.exe /SERVER=https://ocsng/ocsinventory /PACKAGER /DEBUG`
- Downloading the ocs package from Server fails with `Downloading file <https://ocsng/ocsinventory/deploy/ocspackage.exe> without server authentication...SendRequest Error: Failed downloading file !`
-Open URL with Firefox->Download start

Where is the problem?

**Comment by gillesdubois** [comment]
Hi,

Same as https://github.com/OCSInventory-NG/WindowsAgent/issues/33
I'm closing.

Gilles Dubois.
