### ISSUE TITLE
OCS Inventory Agent not Synchronizing with Server

### ISSUE THREAD

**Issue by dunknny** [OCSInventory-NG/OCSInventory-Server#59]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Windows Server 2012 
Windows NT CC-ICT-SVR01001 6.2 build 9200 (Unknow Windows version Standard Edition) i586

### Server informations
Perl version : 
Xampp 1.77/ Mysql / Apache 2.2 / Percona version : 
Apache/2.2.21 (Win32) mod_ssl/2.2.21 OpenSSL/1.0.0e PHP/5.3.8 mod_perl/2.0.4 Perl/v5.10.1
Apache HTTP Server Version 2.2
Perl 5 version 24.0 
MySQL 5.7 
Apache/2.2.21 (Win32) mod_ssl/2.2.21 OpenSSL/1.0.0e PHP/5.3.8 mod_perl/2.0.4 Perl/v5.10.1 

### OCS Inventory informations
Ocs server version : 2.1.2

### Problem's description
*OCS Inventory Agent not Synchronizing with Server*

Hi Guys/Bonjour les amis,

I've extensively read all articles and questions on this topic but i'm not making head way. The OCS Windows agent is not synchronizing to my OSC Inventory Server on Windows Server 2012.

Please see my Agent log below:

==============================================================================
Starting OCS Inventory NG Agent on Friday, April 28, 2017 22:18:11.
AGENT => Running OCS Inventory NG Agent Version 2.3.0.0
AGENT => Using OCS Inventory NG FrameWork Version 2.3.0.0
AGENT => Loading plug-in(s)
    DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
    DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
    COM PROVIDER => Loading Communication Provider <C:\Program Files (x86)\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.0.0>
    AGENT => Sending getLabel request
    COM SERVER => Initializing cURL library for getFile
    COM SERVER => Using cURL without server authentication
    COM SERVER => Disabling cURL proxy support
    COM SERVER => Disabling cURL SSL server validation support
    COM SERVER => Sending fileGet request to URL <https://X.X.X.X/ocsreports/deploy/label>
    COM SERVER => fileGet response received <HTTP Status Code #404>
    COM SERVER => Cleaning cURL library
    AGENT => Failed to retrieve Label <HTTP Status Code #404>
AGENT => Sending Prolog
    DID_CHECK => Read DeviceID <XXXX-2017-04-28-22-00-49> and MACs <XXXX> in file <ocsinventory.dat>
    COM SERVER => Initializing cURL library for sendRequest
    COM SERVER => Using cURL without server authentication
    COM SERVER => Disabling cURL proxy support
    COM SERVER => Disabling cURL SSL server validation support
    COM SERVER => Sending HTTP Post request to URL <https://X.X.X.X/ocsreports>
    COM SERVER => HTTP Post response received <HTTP Status Code #200>
    COM SERVER => Cleaning cURL library
================= TRACE START ===============

================= TRACE STOP ===============
AGENT => Prolog successfully sent
SUPPORT => No support detected, Registration key : N/A
    AGENT => Prolog Frequency set to 10 hour(s)
    AGENT => Inventory on startup option set to  
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:00.

The ocsinventory.ini is as seen below:

[OCS Inventory Agent]
ComProvider=ComHTTP.dll
Debug=2
Local=
NoSoftware=0
HKCU=0
NoTAG=0
IpDisc=
[HTTP]
Server=https://X.X.X.X/ocsreports
SSL=0
CaBundle=cacert.pem
AuthRequired=0
User=
Pwd=
ProxyType=0
Proxy=
ProxyPort=0
ProxyAuthRequired=0
ProxyUser=
ProxyPwd=
[OCS Inventory Service]
PROLOG_FREQ=10
INVENTORY_ON_STARTUP=0
OLD_PROLOG_FREQ=10
TTO_WAIT=35520

Please help anyone...pleaseeee !!

**Comment by gitdevmod** [comment]
Hi,

Try with Server=https://X.X.X.X/ocsinventory, https://X.X.X.X/ocsreports is the web managment page

**Comment by dunknny** [comment]
Hi GitDevmod,
I used it as advised and got this error below in Ocsinventory log file.
Starting OCS Inventory NG Agent on Wednesday, May 10, 2017 19:15:21.AGENT => Running OCS Inventory NG Agent Version 2.3.0.0AGENT => Using OCS Inventory NG FrameWork Version 2.3.0.0AGENT => Loading plug-in(s)AGENT => Using network connection with Communication ServerAGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.0.0>AGENT => Sending PrologERROR *** AGENT => Failed to send Prolog <Problem with the SSL CA cert (path? access rights?)>AGENT => Unloading communication providerAGENT => Unloading plug-in(s)AGENT => Execution duration: 00:00:01.
Regards,
Tayo Fatoki

**Comment by gitdevmod** [comment]
Hi,

Maybe your should replace X.X.X.X with the hostname configured in your certificate Common Name.

**Comment by dunknny** [comment]
Hi,

Thanks for the feedback.

I currently do not have a certificate Common Name.

Can you please show me how it has to be done.

Thank you.

Regards,

Tayo

**Comment by dunknny** [comment]
Hi,
Thanks for the feedback.
I currently do not have a certificate Common Name.
Can you please show me how it has to be done.
Thank you.
Regards,
Tayo

**Comment by gitdevmod** [comment]
Hi,

If you do not have a certificate why using https? try with http: Server=http://X.X.X.X/ocsinventory

**Comment by dunknny** [comment]
Well i thought it was required. I have changed it to http://X.X.X.X/ocsinventory.

Please see below:


Starting OCS Inventory NG Agent on Thursday, May 11, 2017 13:09:23.
AGENT => Running OCS Inventory NG Agent Version 2.3.0.0
AGENT => Using OCS Inventory NG FrameWork Version 2.3.0.0
AGENT => Loading plug-in(s)
AGENT => Using network connection with Communication Server
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.0.0>
AGENT => Sending Prolog
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #404>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:00.

**Comment by gitdevmod** [comment]
http 404 code is file not found (problem with your installation?), you should ask on forum or IRC for better support. btw OCS server 2.1.2 is an old release.

**Comment by dunknny** [comment]
okay thanks i already did, please see below:

https://ask.ocsinventory-ng.org/6844/ocs-inventory-agent-not-synchronizing-with-server

I will be opened to any further suggestions.

**Comment by gitdevmod** [comment]
Effectivement il doit y avoir un soucis avec mod_perl. Sur une installation type sur Debian, il y a un fichier de configuration z-ocsinventory-server.conf qui spécifie les identifiants ocs (db,user), configuration de mod_perl c'est sûrement pareil sur une installation Windows. Il faut vérifier ce fichier et les logs apache pour voir si il y a une erreur...

**Comment by dunknny** [comment]
J'ai vérifié le serveur et j'ai confirmé que la configuration de DB, DB USER, DB PASSWORD est correcte. Merci encore une fois pour votre temps.

**Comment by gitdevmod** [comment]
J'ai installé la version OCSNG-Windows-Server-Setup.exe disponible sur le site officiel (marqué obsolète) avec l'agent 2.3.0.0 sur Windows 2012 R2. Après une installation rapide, j'ai également obtenu l'erreur 404 mais après redémarrage du service apache l'erreur est devenu 400. J'ai installé une ancienne version de l'agent 2.0.5 et là ça fonctionne, j'ai bien la machine qui remonte dans ocsreports.
Je ne connais pas tes contraintes mais ce n'est pas plus compliqué d'installer OCSNG-Server sur un OCS type unix et tu auras les dernières versions.

**Comment by gillesdubois** [comment]
Bonjour,

LOrsque vous installez OCS sous Unix, il suffit de faire attention aux configuration apache et a bien penser a activer celles-ci.
Rien de bien compliqué mais il faut bien faire attention a ne rien oublier.

Cordialement,
Gilles Dubois.
