### ISSUE TITLE
Problems with all plugins

### ISSUE THREAD

**Issue by fpusersuggest** [OCSInventory-NG/OCSInventory-Server#60]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
CentOS Linux release 7.3.1611 (Core)

### Server informations
Perl version : v5.16.3
Mysql / Mariadb / Percona version :  
mariadb-server-5.5.52-1.el7.x86_64

### OCS Inventory informations
Ocs server version :
 ocsinventory-server-2.3.1-4.el7.ocs.noarch

### Problem's description
When I install a plugin I receive the following error:
![schermata da 2017-05-09 10-17-25](https://cloud.githubusercontent.com/assets/6614719/25848323/2c827b26-34ba-11e7-99d5-f2c494edbcae.png)

I have the same problem with all plugin installed and none works. The plugin I tryed to install are:
uptime, security, winupdate
I installed the plugin in the following way:

```

# cd /var/lib/ocsinventory-reports/plugins/download
# wget https://github.com/PluginsOCSInventory-NG/winupdate/releases/download/1.0/winupdate.zip
# chcon -u system_u *.zip
# chown apache winupdate.zip
# ls -laZ
drwxr-xr-x. apache root system_u:object_r:httpd_sys_rw_content_t:s0 .
drwxr-xr-x. apache root system_u:object_r:httpd_sys_rw_content_t:s0 ..
-rwxr-xr-x. apache root system_u:object_r:httpd_sys_rw_content_t:s0 README
-rw-r--r--. apache root system_u:object_r:httpd_sys_rw_content_t:s0 security.zip
-rw-r--r--. apache root system_u:object_r:httpd_sys_rw_content_t:s0 uptime.zip
-rw-r--r--. apache root system_u:object_r:httpd_sys_rw_content_t:s0 winupdate.zip
# service httpd restart
```
I go to plugin-manager then I install the plugin... and I have the error.

**Comment by eliaspizarro** [comment]
seems you need to delete plugin folder and reinstall, do it every update time
