### ISSUE TITLE
No run httpd service, Compress::Raw::Zlib version

### ISSUE THREAD

**Issue by AndrewReal0** [OCSInventory-NG/OCSInventory-Server#63]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Centos 7 minimal

### Server informations
Perl version : (v5.16.3)
Mysql / Mariadb / Percona version :  4.1

### OCS Inventory informations
Ocs server version : 2.31

### Problem's description
*Describe your problem here*

I can't run httpd service.
# systemctl restart httpd 

Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.

#systemctl status httpd

jun 08 13:18:29 localhost.localdomain systemd[1]: Starting The Apache HTTP Server...
jun 08 13:18:29 localhost.localdomain systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
jun 08 13:18:29 localhost.localdomain kill[7128]: kill: cannot find process ""
jun 08 13:18:29 localhost.localdomain systemd[1]: httpd.service: control process exited, code=exited status=1
jun 08 13:18:29 localhost.localdomain systemd[1]: Failed to start The Apache HTTP Server.
jun 08 13:18:29 localhost.localdomain systemd[1]: Unit httpd.service entered failed state.
jun 08 13:18:29 localhost.localdomain systemd[1]: httpd.service failed.

#nano /var/log/httpd/error_log

[Thu Jun 08 12:20:59.897839 2017] [perl:error] [pid 6600] Compress::Raw::Zlib version 2.074 required--this is only version 2.061 at /usr/local/lib64/perl5/Compress/$
[Thu Jun 08 12:20:59.898112 2017] [perl:error] [pid 6600] Can't load Perl module Compress::Zlib for server localhost:0, exiting...

Someone can help me!

**Comment by gillesdubois** [comment]
Hi @AndrewReal0,

Your Compress::Raw::Zlib version is too low. You need at least 2.074 but your server have 2.061.
It should run fine after updating this dependency.

Regards,
Gilles Dubois.

**Comment by AndrewReal0** [comment]
Ok but how i can updating this dependency, i try:
yum install perl-Compress-Raw-Zlib
Package 1: perl-Compress-Raw-Zlib-2.061-4.el7.x86_64 is already installed with its most recent version.
I install Compress::Raw::Zlib with CPAN, but no work.

**Comment by gillesdubois** [comment]
Could you try to remove Compress::Zlib and all his sub-dependencies and try to install it using CPAN : 
- cpan -i Compress::Zlib
