### ISSUE TITLE
Repository des sources d'install du serveur OCS

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-Server#64]
### General informations
Operating system : Debian GNU/Linux 8 (jessie)

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  (Debian) version 5.5.54-0+deb8u1

### OCS Inventory informations
Ocs server version : 2.3.1

### Problem's description

Bonjour,

serait-il possible de créer un repository "up to date", "latest" (ou un lien symbolique pointant vers) pour le téléchargement des fichiers d'installation du serveur OCS Inventory Unix / Linux ?

> En raison des différentes versions livrées à ce jour, des informations contradictoires (et la plupart obsolètes) persistent un peu partout sur Internet (cf. tuto d'internautes, ouvrages sur OCS Inventory, etc.) et lors du téléchargement / installation du serveur OCS Inventory NG, il me semble que l'on devrait pouvoir proposer en priorité la dernière version stable en date.

Bien cordialement, Stéphane

**Comment by gillesdubois** [comment]
Bonjour,

La seule source d'installation fiable de notre logiciel est notre site internet.
Nous ne pouvons pas garantir l'intégrité des liens des sites tiers.

Gilles Dubois.

**Comment by steph78630** [comment]
Bonjour Gilles,

je suis 100 % d'accord avec toi...

Ce que je voulais dire, c'est de proposer sur votre site internet + wiki d'OCS un lien "générique" de téléchargement du serveur OCS Linux/Unix "up to date" plutôt que la dernière version à la date de la rédaction d'un post / article...

> Comme c'est déjà le casp our le serveur OCS Windows : http://download.ocsinventory-ng.org/pub/Server/OCSNG-Windows-Server-Setup.exe

Par exemple :

https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases/download/**utd**/OCSNG_UNIX_SERVER-**utd**.tar.gz

Actuellement, en fonction de l'ancienneté d'un post / tuto / wiki, on télécharge et installe une version de serveur OCS qui peut être déjà obsolète (avec la nécessité de devoir mettre à jour / recommencer).

A+, Stéphane
