### ISSUE TITLE
Corriger la visualisation des logs

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-Server#65]
### General informations
Operating system : Debian GNU/Linux 8 (jessie)

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  (Debian) version 5.5.54-0+deb8u1

### OCS Inventory informations
Ocs server version : 2.3.1

### Problem's description

Bonjour,

le fichier log.csv n'est pas généré dans la zone Information > Visualisation des logs.

De même, cela a un impact sur "Nombre de Connexion par jour" de la zone Information > Statistiques qui ne fonctionne pas.

**Comment by gillesdubois** [comment]
Bonjour,

Le problème a été résolu : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/commit/060866f65519869d724b23f4794f884e504f1542

Gilles Dubois.
