### ISSUE TITLE
Install 2.3.1 -  ERROR: Unable to copy files in /usr/share/ocsinventory-reports/ocsreports

### ISSUE THREAD

**Issue by yafp** [OCSInventory-NG/OCSInventory-Server#67]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Ubunut 16.04

### Server informations
Perl version : 5.22
Mysql / Mariadb / Percona version :  5.7.18 

### OCS Inventory informations
Ocs server version : 2.3.1

### Problem's description
While running setup.sh the script throws the following error:

+----------------------------------------------------------+
|      Installing files for Administration server...       |
+----------------------------------------------------------+

```
Creating PHP directory /usr/share/ocsinventory-reports/ocsreports.
Copying PHP files to /usr/share/ocsinventory-reports/ocsreports.
*** ERROR: Unable to copy files in /usr/share/ocsinventory-reports/ocsreports, please look at error in /home/edv-administrator/OCSInventory-Server-2.3.1/ocs_server_setup.log and fix !

Installation aborted !

```

The log contains:
```
============================================================
Installing Administration server
============================================================
Checking for Administration Server directories...
Using directory /usr/share/ocsinventory-reports for static files
Using /var/lib/ocsinventory-reports as writable/cache directory
Checking for DBI PERL module
PERL module DBI is available
Checking for DBD::mysql PERL module
PERL module DBD::mysql is available
Checking for XML::Simple PERL module
PERL module XML::Simple is available
Checking for Net::IP PERL module
PERL module Net::IP is available
Creating PHP directory /usr/share/ocsinventory-reports/ocsreports
Copying PHP files to /usr/share/ocsinventory-reports/ocsreports
cp: cannot stat 'ocsreports/*': No such file or directory
```

The directory '/usr/share/ocsinventory-reports/' exists and contains the folder 'ocsreports'

Am i guessing right that the release 2.3.1 does not comes with a ocsreport folder which should be copied to my configured target? Should be around line 1446 of the install script.

**Comment by yafp** [comment]
seems similar to #22 - but i did use a release for this installation attempt (so the solution mentioned in #22 is not valid for my case)

**Comment by yafp** [comment]
A possible solution is to create a folder ocsreports inside the extracted release of OCSInventory-Server. Then download the master from the OCSInventory-ocsreports repo and extract it to the manually created ocsreports folder. Now restart setup.sh.

**Comment by gillesdubois** [comment]
@yafp ,
you need to take this file : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases
and not the one from the server ( which only contain the communication server )

Regards,
Gilles Dubois?
