### ISSUE TITLE
Can't load SOAP::Transport::HTTP* - Web service will be unavailable

### ISSUE THREAD

**Issue by vinimarcarini** [OCSInventory-NG/OCSInventory-Server#68]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  CentOS 7

### Server informations
Perl version : perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
Mysql / Mariadb / Percona version :  maridadb

### OCS Inventory informations
Ocs server version : 2.3.1

### Problem's description
*Describe your problem here*

root@ocs OCSNG_UNIX_SERVER-2.3.1]# tail -f  /var/log/httpd/error_log
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
[Mon Jul 03 14:21:22.083855 2017] [core:notice] [pid 18857] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Jul 03 14:21:22.085072 2017] [suexec:notice] [pid 18857] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable
[Mon Jul 03 14:21:22.366948 2017] [auth_digest:notice] [pid 18857] AH01757: generating secret for digest authentication ...
[Mon Jul 03 14:21:22.368177 2017] [lbmethod_heartbeat:notice] [pid 18857] AH02282: No slotmem from mod_heartmonitor
[Mon Jul 03 14:21:22.397423 2017] [mpm_prefork:notice] [pid 18857] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3 configured -- resuming normal operations
[Mon Jul 03 14:21:22.397466 2017] [core:notice] [pid 18857] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

**Comment by gillesdubois** [comment]
Hi,

You just need to install the Apache2::SOAP module.
It's not a mandatory module so you can just skip it.

Regards,
GIlles Dubois.
