### ISSUE TITLE
Illegal field name 'APR::Table=HASH(0x7f8b5cb3bea0)' 

### ISSUE THREAD

**Issue by nntu** [OCSInventory-NG/OCSInventory-Server#7]
hi,
when i connect http://127.0.0.1/ocsinterface 
return error 2015-06-16 10:36:58 ERROR 500: Internal Server Error.
apache2 config 
<location /ocsinterface>
        SetHandler perl-script
        PerlHandler "Apache::Ocsinventory::SOAP"
        Require all granted
        # By default, you can query web service from everywhere with a valid user
       # Order deny,allow
       # Allow from all
       #	AuthType Basic
	#AuthName "OCS Inventory SOAP Area"
	# Use htpasswd to create/update soap-user (or another granted user)
	#AuthUserFile "APACHE_AUTH_USER_FILE"
	#require "SOAP_USER"
  </location>

so log error Illegal field name 'APR::Table=HASH(0x7f8b5cb3bea0)' at /usr/local/share/perl/5.20.1/SOAP/Transport/HTTP2.pm line 103.\n

**Comment by gillesdubois** [comment]
Cannot be reproduce.

If you're sure that is a bug and not a configuration / installation problems you should re-post one issue with more details.
How did you produce this bug, what type of configuration are you using and what modules are installed / enabled for example.

If you want a quick and accurate answer you should give theses informations : 

* A detailed "How to reproduce" process
* Apache, Perl, php and ocs versions
* Logs from apache (error and access logs)
* Logs from ocs (activity.log)
* Output of agents debug mode (/debug in windows and --debug for unix) (If needed)

Sorry for inconvenience you met.
Regards, Gilles Dubois.

**Comment by mxroo** [comment]
I was coming up against a similar issue.
https://github.com/libwww-perl/HTTP-Message/issues/55

Looks like fields with a colon are marked as illegal in all versions of perl HTTP::Message after 6.04
https://github.com/libwww-perl/HTTP-Message/commit/5aaa8144

**Comment by derjoern** [comment]
Can confirm this bug. I have recently updated my test-system to CentOS 7.4, perl-HTTP-Message-6.06-6 and OCS 2.4.1 and ran into this bug.
