### ISSUE TITLE
Wrong formatting at the end of the file (plugins section)

### ISSUE THREAD

**Issue by steph78630** [OCSInventory-NG/OCSInventory-Server#70]
### General informations
Operating system : Debian GNU/Linux 8 (jessie)

### Server informations
Perl version : 
Mysql / Mariadb / Percona version :  (Debian) version 5.5.57-0+deb8u1

### OCS Inventory informations
Ocs server version : 2.3.1

### Problem's description
The end of the following file (section installing plugins) is wrong formatted, it lacks line back to the closing tags :
/usr/share/ocsinventory-reports/ocsreports/config/computer/plugins.xml

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed on the trunk of the ocs reports.

Regards,
Gilles Dubois.
