### ISSUE TITLE
Plugins problem runningprocess

### ISSUE THREAD

**Issue by FabulousRedPanda** [OCSInventory-NG/OCSInventory-Server#72]
### General informations
Ubuntu VERSION 17.04 (Zesty Zapus) up to date.

### Server informations
**Perl** : Summary of my perl5 (revision 5 version 24 subversion 1).
**Mysql** :  mysql  Ver 14.14 Distrib 5.7.19.
**PHP** : 7.0.22-0ubuntu0.17.04.1 (apache2handler).
**Web Server** : Apache/2.4.25 (Ubuntu).

### OCS Inventory informations
Ocs server version :  ocsinventory-server_2.2+dfsg-0.1_all.deb

### Step for Reproduce the bug ?

I have setup a fresh Install of ocs server everything is working expected the plugin "runningprocess":

What did I do: 

Install plugins server side with theses 2 steps:

-  Dowload the plugin compatible with ocsinventory server 2.2 
-` cd /usr/share/ocsinventory-reports/download`
- wget https://github.com/PluginsOCSInventory-NG/runningProcess/releases/download/runningprocess-1.1/runningprocess.zip

Enable the plugins with the GUI.

Then I have installed the agent client side (ubuntu 17.04 too)

- `apt install ocsinventory-agent`
- `locate Download.pm`
`/usr/share/perl5/Ocsinventory/Agent/Modules/Download.pm`
- `vi /usr/share/perl5/Ocsinventory/Agent/Modules/Processes.pm `and copy/paste the content provide from Processes.pm from the zip archive previously downloaded.
- Edit content from` /etc/ocsinventory/modules.conf` and add `use Ocsinventory::Agent::Modules::Processes;`
-test with command `perl module.conf`

Finaly launch the ocs-agent:
```
ocsinventory-agent 
[info] No support detected. Registration key: N/A
[info] [download] Download is off.

comment OCS
startvm 4aff21d8-8237-4435-88cd-9c4069b70f48
no-startvm-errormsgbox

[info] [download] Beginning work. I am 26393.
[info] [download] Option turned off. Exiting.
```
Looks like Ok but I dont saw any information about process, is it normal ?

Now the problem:
When I try to show the process in the GUI this is the error message, with no error log on apache2

![capture du 2017-08-29 17-28-24](https://user-images.githubusercontent.com/30699675/29829355-81810cc8-8cdf-11e7-98a5-1edeba89bb8d.png)

**Comment by gillesdubois** [comment]
Hi,

Please can you adresse your issue to this address : 
https://github.com/PluginsOCSInventory-NG/runningProcess

Regards,
Gilles Dubois.
