### ISSUE TITLE
Error Count on Microsoft Office Standard

### ISSUE THREAD

**Issue by erwinvr** [OCSInventory-NG/OCSInventory-Server#73]
Hi everyone
### General informations
Operating system : 
    Linux x86_64
    3.10.0-229.el7.x86_64
    3778 MB
    2461 MB
    Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    CentOS Linux 7 (Core)
### Server informations
Perl version : 
Mysql / Mariadb / Percona version : 

PHP   5.4.16
WEB  Apache/2.4.6 (CentOS) PHP/5.4.16 mod_perl/2.0.10 Perl/v5.16.3
DB;MariaDB Server version 5.5.52-MariaDB
    

### OCS Inventory informations
Ocs server version : 2.3.1

### Problem's description
When i go to Inventory / All Software / M, write in Search: Microsoft Office Standard. The results are correct: 3 opciones 2010, 2013 and 2016, but the count is incorrect, because the result is *2.

Anyone can fix this?
Thanks!

![captura](https://user-images.githubusercontent.com/32521009/31195251-adef8a38-a917-11e7-9caf-7a00b2f0a092.PNG)

**Comment by gillesdubois** [comment]
Hi,

This problem has been fixed in the trunk and will be available in the next version.

Regards,
Gilles Dubois.
