### ISSUE TITLE
Locks problem on computer update

### ISSUE THREAD

**Issue by gillesdubois** [OCSInventory-NG/OCSInventory-Server#75]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : all

### Server informations
Perl version : all
Mysql / Mariadb / Percona version :  5,7

### OCS Inventory informations
Ocs server version : 2,3,1

### Problem's description
From @drtrojan

403 error was caused by next code from `Apache/Ocsinventory/Server/System.pm:212`:
```
  if($dbh->do('INSERT INTO locks(HARDWARE_ID, ID, SINCE) VALUES(?,?,NOW())', {} , $device, $$ )){
    ...
    return(0);
  }else{
    ...
    return 1;
  }
```
`$dbh->do()` had caused an error on the `locks` (MEMORY-type) table : `Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.`

I had the environment with enabled `enforce-gtid-consistency` feature in MySQL 5.7. This feature doesn't allow simple update to memory tables.

**Comment by rrajesh011** [comment]
@gillesdubois Hi,
How this issue is resolved, do we need to upgrade ocs server or anything extract i have to. I don't see any commit related to this. I'm also facing same issue here
https://github.com/OCSInventory-NG/OCSInventory-Server/issues/218#issuecomment-676559133
