### ISSUE TITLE
Problem with LDAP authentication

### ISSUE THREAD

**Issue by combasdg** [OCSInventory-NG/OCSInventory-Server#80]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Linux CentOS 5.11, kernel 2.6.18

### Server informations
Perl version : 5.8.8
Mysql version :  5.0.95

### OCS Inventory informations
Ocs server version : 2.3.1

### Problem's description
There's a problem in LDAP authentication (menu Config -> Config -> LDAP configuration).
When setting up the LDAP server parameters and (only) these options:
- CONEX_LDAP_CHECK_FIELD1_NAME = gidNumber
- CONEX_LDAP_CHECK_FIELD1_VALUE = 1000
- CONEX_LDAP_CHECK_FIELD1_ROLE = Super administrators
I'm expecting to be able to connect to OCS Inventory Server as a Super administrator, provided that my LDAP account (identified by the CONEX_LOGIN_FIELD = uid in my case) has a gidNumber (primary Samba group) equal to 1000.

Instead, my LDAP users can log in but can't do nothing, since it has no privileges assigned.

Work-around until fixed: set the same values in the fields CONEX_LDAP_CHECK_FIELD2_NAME, CONEX_LDAP_CHECK_FIELD2_VALUE and CONEX_LDAP_CHECK_FIELD2_ROLE. This way a LDAP user with primary Samba group equal to 1000 can log in as a Super administrator as expected.

**Comment by gillesdubois** [comment]
Hi,

LDAP has been reworked in the latest version thus i'm closing the issue.

Regards,
Gilles Dubois.
