### ISSUE TITLE
Custom plugin not executed by Apache

### ISSUE THREAD

**Issue by soundcha0s** [OCSInventory-NG/OCSInventory-Server#82]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian Jessie 8.4

### Server informations
Perl version : 5.20.2
Mysql  version :  5.6

### OCS Inventory informations
Ocs server version : 2.3.1

### Problem's description
OCS Agent is well sending what I want from my custom agent plugin.
OCS inventory is well made for all OCS "default" parts (OS, hardware, etc...). 
But OCS inventory doesn't any content from my custom plugin.

After investigations, I don't see any related SQL request to the database.
OCS_PLUGINS_PERL|CONF_DIR as set as default:
  PerlSetEnv OCS_PLUGINS_PERL_DIR "/etc/ocsinventory-server/perl"
  PerlSetEnv OCS_PLUGINS_CONF_DIR "/etc/ocsinventory-server/plugins"
If I add my Map.pm content to the default /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Map.pm file, everything works fine.
So it seems that the custom perl conf/map files are not taken in count by Apache ocsinventory configuration.

**Comment by gillesdubois** [comment]
Hi, 

This problem has been fixed for the 2.6 release.

Regards,
Gilles Dubois.
