### ISSUE TITLE
LDAP configuration

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/OCSInventory-Server#85]
### General informations
Operating system :  Ubuntu 16.04.3 LTS

### Server informations
Perl version : v5.22.1
Mysql version :  (Ubuntu) version 5.7.20-0ubuntu0.16.04.1

### Server installation method ( Only one choice )
Manual installation

### OCS Inventory informations
Ocs server version :  2.3.1

### Problem's description
Hey,

i tried to setup LDAP with the guides i [found.](https://github.com/OCSInventory-NG/Wiki/blob/a77704d01be0ffad61872a8711c578c7c6c6eef8/english/03.Management-console-and-its-advanced-features/Synchronization-between-OCS-and-LDAP.md) 

Unfortunately it´s not working cause i get some fatal php errors. 
`[Wed Nov 29 11:32:33.748175 2017] [:error] [pid 30893] [client 10.30.10.16:65524] PHP Fatal error:  Uncaught Error: Call to undefined function ldap_connect() in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php:124\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(74): ldap_connection()\n#1 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(50): search_on_loginnt('pg1042')\n#2 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(45): verif_pw_ldap('pg1042', 'mypassword')\n#3 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php(71): require_once('/usr/share/ocsi...')\n#4 /usr/share/ocsinventory-reports/ocsreports/require/header.php(323): require_once('/usr/share/ocsi...')\n#5 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#6 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 124, referer: http://ocs/ocsreports/
`
Maybe this is caused by some wrong configuration on my site but i didn´t found any other setup, so maybe you can help me with that.

I´m also not really happy with that how to so after it´s working i´ll update this guide ;-)

Thanks,

**Comment by kmstory** [comment]
I know this is old, but I found this while looking for an answer to the same error, so hopefully this answer will help someone else.

The fix for this is to make sure you have the PHP LDAP module installed and enabled. The "Call to undefined function ldap_connect()" part means that your php installation doesn't have the ldap_connect function, which is part of the LDAP module.

**Comment by scifire91** [comment]
@kmstory thanks so much for this hint. This was the main problem what hold to get it working :)

**Comment by gillesdubois** [comment]
Hi @kmstory, thx for contributing and helping our users :) 
@scifire91 sorry for the delay, sometimes it's a bit hard to anwser in time.
