### ISSUE TITLE
client pc doesn't show up in inventory

### ISSUE THREAD

**Issue by testerusername** [OCSInventory-NG/OCSInventory-Server#86]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  ubuntu 16.04 x86_64

### OCS Inventory informations
Ocs server version :  2.3.1

### Problem's description

client pc doesn't show up in inventory

**> `ocsinventory.ini**
> 
> [OCS Inventory Agent]
> ComProvider=ComHTTP.dll
> Debug=1
> Local=
> NoSoftware=0
> HKCU=0
> NoTAG=0
> IpDisc=
> [HTTP]
> Server=http://192.168.56.101/ocsinventory

> SSL=0
> CaBundle=cacert.pem
> AuthRequired=0
> User=
> Pwd=
> ProxyType=0
> Proxy=
> ProxyPort=0
> ProxyAuthRequired=0
> ProxyUser=
> ProxyPwd=
> [OCS Inventory Service]
> PROLOG_FREQ=10
> INVENTORY_ON_STARTUP=0
> OLD_PROLOG_FREQ=10
> TTO_WAIT=36000`

`

**> agent log**
> 
> Starting OCS Inventory NG Agent on Wednesday, December 06, 2017 10:19:04.
> AGENT => Running OCS Inventory NG Agent Version 2.3.1.1
> AGENT => Using OCS Inventory NG FrameWork Version 2.3.1.1
> AGENT => Loading plug-in(s)
> 	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
> 	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
> AGENT => Using network connection with Communication Server
> 	COM PROVIDER => Loading Communication Provider <C:\Program Files (x86)\OCS Inventory Agent\ComHTTP.dll>
> AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.1.1>
> AGENT => Sending Prolog
> 	DID_CHECK => Read DeviceID <QPKJ1-198C-2017-12-05-14-52-10> and MACs <50:65:F3:1B:A6:7602:02:54:53:32:3200:00:00:00:00:0000:00:00:00:00:0000:00:00:00:00:00> in file <ocsinventory.dat>
> 	COM SERVER => Initializing cURL library for sendRequest
> 	COM SERVER => Using cURL without server authentication
> 	COM SERVER => Disabling cURL proxy support
> 	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <C:\ProgramData\OCS Inventory NG\Agent\cacert.pem>
> 	COM SERVER => Sending HTTP Post request to URL <http://192.168.56.101/ocsinventory>
> 	COM SERVER => HTTP Post response received <HTTP Status Code #500>
> 	COM SERVER => Cleaning cURL library
> ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #500>
> AGENT => Unloading communication provider
> AGENT => Unloading plug-in(s)
> AGENT => Execution duration: 00:00:00.
> `
> [OCSInventory.log](https://github.com/OCSInventory-NG/OCSInventory-Server/files/1534749/OCSInventory.log)

**Comment by kapouik** [comment]
Most of the time, error 500 is cause by a bad mysql login/password.

http://wiki.ocsinventory-ng.org/index.php?title=Documentation:Main#FAQ
http://ask.ocsinventory-ng.org/1/i-got-an-error-500-when-my-agent-contact-the-server

**Comment by testerusername** [comment]
tested it did not do it for me

**Comment by testerusername** [comment]
solved
forgot to restart apache service
thank you
