### ISSUE TITLE
Latest install tutorial - WHERE?

### ISSUE THREAD

**Issue by Dennis1993** [OCSInventory-NG/OCSInventory-Server#88]
Hello,

I will install OCS-Inventory server and reports 2.4 on ubuntu 17.10. Where is a Installation tutorial for that?
In your Wiki I find only "outdatet" tutorials. In Google I found Million ways and no one works, because some modules are not installed or somethings. I tested three tutorials and nothing works.

Is there an tutorial from OCS Inventory itself which is works?
Or where I can find a list of modules which I must install?
It is very confusing and chaotic...

Thanks in advance! :)

**Comment by scifire91** [comment]
@Dennis1993 hey last year i updated some documentation here on github. In my opinion the most helpful docu you´ll find in that repo:
https://github.com/OCSInventory-NG/Wiki/blob/a77704d01be0ffad61872a8711c578c7c6c6eef8/english/02.Basic-documentation/Setting-up-a-OCS-Inventory-Server.md

**Comment by Dennis1993** [comment]
Thank you! I will test it!
