### ISSUE TITLE
/etc/httpd/conf.d/z-ocsinventory-server.conf not updated with custom db connection

### ISSUE THREAD

**Issue by Laurent-1971** [OCSInventory-NG/OCSInventory-Server#89]
### General informations
Operating system : CentOS Linux 7 (Core) / 3.10.0-693.11.1.el7.x86_64

### Server informations
Perl version :  4:5.16.3-292.el7
Mysql / Mariadb / Percona version :  MariaDB Server version 5.5.56-MariaDB

### Server installation method ( Only one choice )
- [ ] RPM Package
- [X] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4

### Problem's description
Upgrade issue.
I have updated my OCS Server using the setup.sh and everything worked but I still have a issue.
I have a custom user and password for the connection to mysql.
On the first gui connection, when install.php runs, if i put my custom informations (user different from the default 'ocs' and password different from 'ocs'), the file "/usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php" is updated.
But the file "/etc/httpd/conf.d/z-ocsinventory-server.conf" is not, so all my agents get a HTTP 500 error code.
I have to manually edit "/etc/httpd/conf.d/z-ocsinventory-server.conf" to change OCS_DB_USER and OCS_DB_OWD values.

Is it possible that this file get updated as the dbconfig.inc.php ?

**Comment by gillesdubois** [comment]
Hi,

For the moment we don't want to make the z-ocsinventory-server.conf editable trough webscripts since it can lead to serious security issues. Also editing it need to restart the service which require a priviliged access to the machine.

Regards,
Gilles Dubois.

**Comment by leandroramoss** [comment]
hi, good afternoon.

Gilles, I'm doing the OCS invetory installation as a college activity, i just wanna know, i changed the admin password, so the security alert still appearing releating to database will persist them, once you said that is not editable for the moment.

**Comment by leandroramoss** [comment]
i dont want to use de default user name at OCS, how can i change this?
