### ISSUE TITLE
using an ORM for the persistance layer

### ISSUE THREAD

**Issue by mtbadi39** [OCSInventory-NG/OCSInventory-Server#9]
Any roadmap for using an [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) (ex: [Doctrine](http://www.doctrine-project.org/)) for the persistance layer ? it's important to switch between different databases.

**Comment by gillesdubois** [comment]
Hello,

For the 2.2 there is nothing planned about using an ORM.
Using an ORM is planned in the 3.0 (Which is the next version after the 2.2)
At the moment we don't have decided which ORM will we be using tho.

Regards,
Gilles Dubois.
