### ISSUE TITLE
Cannot establish communication : 500 Internal Server Error

### ISSUE THREAD

**Issue by llljackll** [OCSInventory-NG/OCSInventory-Server#92]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Red Hat Enterprise Linux Server release 7.2 (Maipo)

### Server informations
Perl version : v5.16.3
Mysql / Mariadb / Percona version :   MariaDB Server version 5.5.44-MariaDB 2.3.1

### Server installation method ( Only one choice )
- [ ] RPM Package
- [ ] Install SH
- [X ] Manual installation

### OCS Inventory informations
Ocs server version : OCSNG_UNIX_SERVER-2.4

### Problem's description
Hi,

I have a problem when I update from version 2.3.1 to 2.4. 

The agents can't communicate with the server, when I force this communication with the command:

ocsinventory-agent --force --debug --server=<server>
.....
[error] Cannot establish communication : 500 Internal Server Error

In apache log appear:

[Wed Feb 07 12:47:27.547668 2018] [perl:error] [pid 29572] [client XX.XXX.XXX.XX:3910] Can't call method "do" on an undefined value at /usr/share/perl5/vendor_perl/Apache/Ocsinventory/Server/System.pm line 189.\n

This line in the file containe:

  my $dbh = DBI->connect("DBI:mysql:database=$database;host=$host;port=$port", $user, $password, \%params);
  $dbh->do("SET NAMES 'utf8'") if($dbh && $ENV{'OCS_OPT_UNICODE_SUPPORT'});
  $dbh->do("SET sql_mode='NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'");
  return $dbh;

My ocs database haven't the defaults values.

I have correctly change from the file /etc/httpd/conf.d/z-ocsinventory-server.conf the value of the next variables:

  PerlSetEnv OCS_DB_NAME XXXX
  PerlSetEnv OCS_DB_LOCAL XXXX
  PerlSetEnv OCS_DB_USER XXXX
  PerlSetVar OCS_DB_PWD XXXX

I have correctly change from the file /usr/share/ocsinventory-reports/ocsreports/dbconfig.inc.php the value of the next variables:

define("DB_NAME", "XXXX");
define("COMPTE_BASE","XXXX");
define("PSWD_BASE","XXXX");

I have updated many time and I never have problem with this.

I do some test and I see that the communication works if I use the default values:

  PerlSetEnv OCS_DB_USER ocs
  PerlSetVar OCS_DB_PWD ocs

and

define("COMPTE_BASE","ocs");
define("PSWD_BASE","ocs");

Thank so much.

Regards,

Víctor.

**Comment by gillesdubois** [comment]
Hi,

You have a new configuration file in 2.4.
There is a zz-ocsinventory-restapi.conf file to update :)

Regards,
Gilles Dubois.

**Comment by giz83** [comment]
As gillesdubois said, "zz-ocsinventory-restapi.conf file to update"
Check that the database username, password, hostname are correct.
Update/Install will create the "zz-ocsinventory-restapi.conf" file with default values.

**Comment by TontonLud** [comment]
@gillesdubois documentation needs to be updated http://wiki.ocsinventory-ng.org/02.Basic-documentation/Deploying-database-server/ and http://wiki.ocsinventory-ng.org/08.Extras/Secure-your-OCS-Inventory-NG-Server/

**Comment by itdeparment** [comment]
As per the suggestion update the /etc/apache2/conf-enabled/zz-ocsinventory-restapi.conf, but no scucess

**Comment by mariaczi** [comment]
I have exactly the same issue. OCSReports and OCSServer are up from the latest version - 2.7.0 and OCSAgent 2.6.0

When I run
` curl http://127.0.0.1/ocsinventory`
I got
```
 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at 127.0.0.1 Port 80</address>
</body></html>
```
so for me it means, that ocsinventory server is working.
In apache log file
`127.0.0.1 - - [23/Mar/2020:22:06:11 +0100] "GET /ocsinventory HTTP/1.1" 400 483 "-" "curl/7.65.3"`
It looks OK.
But when I run OCS Agent the agent collect all data but can't communicate with ocsserver. In agent.log file as a last line I received:
`[Mon Mar 23 22:11:23 2020][error] Cannot establish communication : 500 Internal Server Error`
and in apache log
`127.0.0.1 - - [23/Mar/2020:22:11:23 +0100] "POST /ocsinventory HTTP/1.1" 500 799 "-" "OCS-NG_unified_unix_agent_v2.6.0"`

I run OCS Agent in this way:
` ./ocsinventory-agent --devlib --debug --ssl=0 --nosoftware -s http://localhost/ocsinventory --force`

Now, where is the problem or/and where I made a mistake in configuration?

**Comment by mariaczi** [comment]
**FOR THE OTHERS WHICH CAN HAVE THE SAME KIND OF ISSUE**
OK, after a few minutes... :D I found the reason of my problem.
The reason was... DB Schema. When I started OCS  setup I have had a old DB version. OCSReports informed me about it and updated the DB as required (via web gui), but... not fully correctly :/. The old DB was from OCS Reports v2.3.1 based on "Changes" file from root directory.
In "ocsreports/files/update/" was:
```
-rw-r--r-- 1 www-data root  713 Jul  4  2017 7007.sql
-rw-r--r-- 1 www-data root  224 Jul  4  2017 7008.sql
-rw-r--r-- 1 www-data root  878 Jul  4  2017 7009.sql
-rw-r--r-- 1 www-data root  358 Jul  4  2017 7010.sql
-rw-r--r-- 1 www-data root 1160 Jul  4  2017 7011.sql
```

I found the reason after enabling OCS_OPT_DBI_PRINT_ERROR option. In apache error log i got
`DBD::mysql::db do failed: Unknown column 'CATEGORY_ID' in 'field list' at /path_to_webdir/ocsinventory/ocsinventory-server/Apache/Ocsinventory/Server/Inventory/Update/Hardware.pm line 78.`
I make this setup on test server, so I could drop all tables from ocs DB and made install from WebGUI. After finished installation OCS informed about required update:
```
Existing database updated
Current version:7017=>Expected version:7028
```
and done it with success.

And after this, OCS Agent connecting to the OCS Server with success :)

**Comment by shubham949** [comment]
> I have exactly the same issue. OCSReports and OCSServer are up from the latest version - 2.7.0 and OCSAgent 2.6.0
> 
> When I run ` curl http://127.0.0.1/ocsinventory` I got
> 
> ```
>  <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>400 Bad Request</title>
> </head><body>
> <h1>Bad Request</h1>
> <p>Your browser sent a request that this server could not understand.<br />
> </p>
> <hr>
> <address>Apache/2.4.41 (Ubuntu) Server at 127.0.0.1 Port 80</address>
> </body></html>
> ```
> 
> so for me it means, that ocsinventory server is working. In apache log file `127.0.0.1 - - [23/Mar/2020:22:06:11 +0100] "GET /ocsinventory HTTP/1.1" 400 483 "-" "curl/7.65.3"` It looks OK. But when I run OCS Agent the agent collect all data but can't communicate with ocsserver. In agent.log file as a last line I received: `[Mon Mar 23 22:11:23 2020][error] Cannot establish communication : 500 Internal Server Error` and in apache log `127.0.0.1 - - [23/Mar/2020:22:11:23 +0100] "POST /ocsinventory HTTP/1.1" 500 799 "-" "OCS-NG_unified_unix_agent_v2.6.0"`
> 
> I run OCS Agent in this way: ` ./ocsinventory-agent --devlib --debug --ssl=0 --nosoftware -s http://localhost/ocsinventory --force`
> 
> Now, where is the problem or/and where I made a mistake in configuration?

Sir I'm also facing same issue when i [Click here to enter OCS-NG GUI] (http://172.20.1.239/ocsreports/index.php) it shows error 500 i also edit this  /etc/apache2/conf-enabled\zz-ocsinventory-restapi.conf file.  could you please help .

**Comment by shubham949** [comment]
> I have exactly the same issue. OCSReports and OCSServer are up from the latest version - 2.7.0 and OCSAgent 2.6.0
> 
> When I run ` curl http://127.0.0.1/ocsinventory` I got
> 
> ```
>  <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>400 Bad Request</title>
> </head><body>
> <h1>Bad Request</h1>
> <p>Your browser sent a request that this server could not understand.<br />
> </p>
> <hr>
> <address>Apache/2.4.41 (Ubuntu) Server at 127.0.0.1 Port 80</address>
> </body></html>
> ```
> 
> so for me it means, that ocsinventory server is working. In apache log file `127.0.0.1 - - [23/Mar/2020:22:06:11 +0100] "GET /ocsinventory HTTP/1.1" 400 483 "-" "curl/7.65.3"` It looks OK. But when I run OCS Agent the agent collect all data but can't communicate with ocsserver. In agent.log file as a last line I received: `[Mon Mar 23 22:11:23 2020][error] Cannot establish communication : 500 Internal Server Error` and in apache log `127.0.0.1 - - [23/Mar/2020:22:11:23 +0100] "POST /ocsinventory HTTP/1.1" 500 799 "-" "OCS-NG_unified_unix_agent_v2.6.0"`
> 
> I run OCS Agent in this way: ` ./ocsinventory-agent --devlib --debug --ssl=0 --nosoftware -s http://localhost/ocsinventory --force`
> 
> Now, where is the problem or/and where I made a mistake in configuration?



> Hi,
> 
> You have a new configuration file in 2.4. There is a zz-ocsinventory-restapi.conf file to update :)
> 
> Regards, Gilles Dubois.

Sir I'm also facing same issue when i [Click here to enter OCS-NG GUI] (http://172.20.1.239/ocsreports/index.php) it shows error 500 i also edit this  /etc/apache2/conf-enabled\zz-ocsinventory-restapi.conf file.
