### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by sbellassai** [OCSInventory-NG/OCSInventory-Server#93]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Ubuntu 16.04 64bit

### Server informations
Perl version : 5.22.1
Mysql / Mariadb / Percona version :  MySQL 14.4

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4

### Problem's description
When trying to upload a file in the "local import" section, I get an error that says "Error HTTP/1.1 400 Bad Request ​"
The issue also exists on the official demo located on the OCS website.
I have tried using Chrome, Firefox, and Edge, all with the same error.

**Comment by gillesdubois** [comment]
Hi,

The local import is not recommend its a really old feature that isn't updated anymore.
We recommend you to use the perl injector which is more automated / stable way to inject OCS files.

Regards,
Gilles.
