### ISSUE TITLE
Question about TAG Lost

### ISSUE THREAD

**Issue by wiltonsr** [OCSInventory-NG/OCSInventory-Server#95]
Hi everyone,

First of all, thank you for OCS.

I would like to know what happens to a host be saved with the TAG = Lost even if the host's agent has a correct tag configured.

Thanks.

**Comment by wiltonsr** [comment]
Someone?
@gillesdubois

**Comment by alacn1** [comment]
I did see it happen when `INVENTORY_SESSION_ONLY` is enabled and the machine sent inventory with `--force`.

**Comment by wiltonsr** [comment]
@alacn1 in my case, `INVENTORY_SESSION_ONLY` is disabled and my agents doesn't send inventory with `--force` and this behaviour still happens.

**Comment by gillesdubois** [comment]
Hi,

Most of our tests cames to the same conclusion, the latest agent versions are not impacted with this behavior anymore.

Regards,
Gilles.
