### ISSUE TITLE
Option -m for ocsinventory-injector.pl missing

### ISSUE THREAD

**Issue by jagarsoft** [OCSInventory-NG/OCSInventory-Server#98]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : All

### Server informations
Perl version : All
Mysql / Mariadb / Percona version :  All

### OCS Inventory informations
Ocs server version : Latest

### Problem's description

Have a look at OCSInventory-Server/binutils/ocsinventory-injector.pl
on line 115 says -m --msg	: show message returned my ocsinventory
but on line 125 GetOptions function has no option for it

How to reproduce:
cd /opt/OCSNG_UNIX_SERVER-x.y.z/binutils/
./ocsinventory-injector.pl -m
Unknown option: m

**Comment by Wilyton** [comment]
Hi,
Can I run the perl script with the master server address in https? What would the synchronization with ssl and certificate look like? For example:

perl ocsinventory-injector.pl  -v -r -d /my/specific/directory -u **https**://OCSmasterServer/ocsinventory
